# Wrangle Pisa 2012
#### By Gabriela Sikora


### Abstract



### Table of Contents

<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
    <ul>
    <li><a href="#gathering">Gathering Data</a></li>
    <li><a href="#assessing1">Initial Assessment</a></li>
        <ul>
          <li><a href="#issues1">Identified Issues</a></li>
        </ul>
    <li><a href="#cleaning1">Cleaning Data</a></li>
    <li><a href="#assessing2">Final Assessment</a></li>
    </ul>
<li><a href="#sav">Store</a></li>
<li><a href="#conclusion">Conclusion</a></li>
<li><a href="#references">References</a></li>    
</ul>

<a id='intro'></a>
## Introduction



To begin, we first need to import all the relevant libraries:
#### Import

In [1]:
# import all packages
import numpy as np
import pandas as pd

<a id='wrangling'></a>
## Data Wrangling

In this section of the report, we will load in the data, check it for cleanliness, and then trim and clean the datasets for analysis.

<a id='gathering'></a>
### Gathering Data

Unfortunately the Pisa dataset is too large to be uploaded to github, but if you would like to work with it yourself then place follow this link: https://s3.amazonaws.com/udacity-hosted-downloads/ud507/pisa2012.csv.zip

In [2]:
# Encoding help found here: https://stackoverflow.com/questions/30462807/encoding-error-in-panda-read-csv

# Load in the Pisa dataframe
pisa = pd.read_csv('pisa2012.csv', encoding="cp1252", sep=',')

# Load in the Pisa dictionary
pisa_dict = pd.read_csv('pisadict2012.csv', encoding="cp1252", sep=',')

/Users/gabriela/Desktop/Code/myenv/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (15,16,17,21,22,23,24,25,26,30,31,36,37,45,65,123,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,284,285,286,287,288,289,290,291,292,293,294,295,296,297,298,299,300,301,302,303,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,326,327,328,329,330,331,332,333,334,335,336,337,338,339,340,341,342,343,344,345,346,347,348,349,350,351,352,353,354,355,356,357,376,377,378,379,380,381,382,383,384,385,386,387,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,475) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

<a id='assessing1'></a>
### First Assessment

In this section, we will do the preliminary visual and programmatic assessment of the pisa datasets to determine whether or not it holds any major quality or tidiness issues.

In [3]:
pisa

,Unnamed: 0,CNT,SUBNATIO,STRATUM,OECD,NC,SCHOOLID,STIDSTD,ST01Q01,ST02Q01,...,W_FSTR75,W_FSTR76,W_FSTR77,W_FSTR78,W_FSTR79,W_FSTR80,WVARSTRR,VAR_UNIT,SENWGT_STU,VER_STU
0,1,Albania,80000,ALB0006,Non-OECD,Albania,1,1,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
1,2,Albania,80000,ALB0006,Non-OECD,Albania,1,2,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
2,3,Albania,80000,ALB0006,Non-OECD,Albania,1,3,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
3,4,Albania,80000,ALB0006,Non-OECD,Albania,1,4,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
4,5,Albania,80000,ALB0006,Non-OECD,Albania,1,5,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
5,6,Albania,80000,ALB0006,Non-OECD,Albania,1,6,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
6,7,Albania,80000,ALB0006,Non-OECD,Albania,1,7,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
7,8,Albania,80000,ALB0006,Non-OECD,Albania,1,8,10,1.0,...,14.4599,14.6374,15.8728,15.8728,5.2248,15.2579,19,1,0.2322,22NOV13
8,9,Albania,80000,ALB0006,Non-OECD,Albania,1,9,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
9,10,Albania,80000,ALB0005,Non-OECD,Albania,2,10,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
10,11,Albania,80000,ALB0005,Non-OECD,Albania,2,11,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
11,12,Albania,80000,ALB0005,Non-OECD,Albania,2,12,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
12,13,Albania,80000,ALB0005,Non-OECD,Albania,2,13,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
13,14,Albania,80000,ALB0005,Non-OECD,Albania,2,14,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
14,15,Albania,80000,ALB0005,Non-OECD,Albania,2,15,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
15,16,Albania,80000,ALB0005,Non-OECD,Albania,2,16,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
16,17,Albania,80000,ALB0005,Non-OECD,Albania,2,17,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
17,18,Albania,80000,ALB0005,Non-OECD,Albania,2,18,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
18,19,Albania,80000,ALB0005,Non-OECD,Albania,2,19,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
19,20,Albania,80000,ALB0005,Non-OECD,Albania,2,20,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
20,21,Albania,80000,ALB0005,Non-OECD,Albania,2,21,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
21,22,Albania,80000,ALB0005,Non-OECD,Albania,2,22,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
22,23,Albania,80000,ALB0005,Non-OECD,Albania,2,23,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
23,24,Albania,80000,ALB0005,Non-OECD,Albania,2,24,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
24,25,Albania,80000,ALB0005,Non-OECD,Albania,2,25,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
25,26,Albania,80000,ALB0005,Non-OECD,Albania,2,26,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
26,27,Albania,80000,ALB0005,Non-OECD,Albania,2,27,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
27,28,Albania,80000,ALB0005,Non-OECD,Albania,2,28,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
28,29,Albania,80000,ALB0005,Non-OECD,Albania,2,29,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
29,30,Albania,80000,ALB0005,Non-OECD,Albania,2,30,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485460,485461,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4930,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485461,485462,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4931,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485462,485463,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4932,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485463,485464,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4933,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485464,485465,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4934,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485465,485466,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4935,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485466,485467,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4936,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485467,485468,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4937,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485468,485469,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4938,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485469,485470,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4939,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485470,485471,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4940,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485471,485472,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4941,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485472,485473,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4942,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485473,485474,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4943,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485474,485475,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4944,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485475,485476,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4945,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485476,485477,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4946,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485477,485478,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4947,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485478,485479,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4948,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485479,485480,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4949,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485480,485481,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4950,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485481,485482,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4951,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485482,485483,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4952,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485483,485484,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4953,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485484,485485,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4954,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485485,485486,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4955,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485486,485487,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4956,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485487,485488,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4957,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485488,485489,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4958,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485489,485490,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4959,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13

In [4]:
pisa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485490 entries, 0 to 485489
Columns: 636 entries, Unnamed: 0 to VER_STU
dtypes: float64(250), int64(18), object(368)
memory usage: 2.3+ GB

In [5]:
pisa_dict

     Unnamed: 0                                                  x
0           CNT                           Country code 3-character
1      SUBNATIO  Adjudicated sub-region code 7-digit code (3-di...
2       STRATUM  Stratum ID 7-character (cnt + region ID + orig...
3          OECD                                       OECD country
4            NC                       National Centre 6-digit Code
5      SCHOOLID  School ID 7-digit (region ID + stratum ID + 3-...
6       STIDSTD                                         Student ID
7       ST01Q01                                International Grade
8       ST02Q01                           National Study Programme
9       ST03Q01                                      Birth - Month
10      ST03Q02                                        Birth -Year
11      ST04Q01                                             Gender
12      ST05Q01                                   Attend <ISCED 0>
13      ST06Q01                                   Age at <ISCED 1>
14      ST07Q01                                 Repeat - <ISCED 1>
15      ST07Q02                                 Repeat - <ISCED 2>
16      ST07Q03                                 Repeat - <ISCED 3>
17      ST08Q01                          Truancy - Late for School
18      ST09Q01                    Truancy - Skip whole school day
19     ST115Q01           Truancy - Skip classes within school day
20      ST11Q01                                   At Home - Mother
21      ST11Q02                                   At Home - Father
22      ST11Q03                                 At Home - Brothers
23      ST11Q04                                  At Home - Sisters
24      ST11Q05                             At Home - Grandparents
25      ST11Q06                                   At Home - Others
26      ST13Q01                          Mother<Highest Schooling>
27      ST14Q01            Mother Qualifications - <ISCED level 6>
28      ST14Q02           Mother Qualifications - <ISCED level 5A>
29      ST14Q03           Mother Qualifications - <ISCED level 5B>
..          ...                                                ...
605    W_FSTR55           FINAL STUDENT REPLICATE BRR-FAY WEIGHT55
606    W_FSTR56           FINAL STUDENT REPLICATE BRR-FAY WEIGHT56
607    W_FSTR57           FINAL STUDENT REPLICATE BRR-FAY WEIGHT57
608    W_FSTR58           FINAL STUDENT REPLICATE BRR-FAY WEIGHT58
609    W_FSTR59           FINAL STUDENT REPLICATE BRR-FAY WEIGHT59
610    W_FSTR60           FINAL STUDENT REPLICATE BRR-FAY WEIGHT60
611    W_FSTR61           FINAL STUDENT REPLICATE BRR-FAY WEIGHT61
612    W_FSTR62           FINAL STUDENT REPLICATE BRR-FAY WEIGHT62
613    W_FSTR63           FINAL STUDENT REPLICATE BRR-FAY WEIGHT63
614    W_FSTR64           FINAL STUDENT REPLICATE BRR-FAY WEIGHT64
615    W_FSTR65           FINAL STUDENT REPLICATE BRR-FAY WEIGHT65
616    W_FSTR66           FINAL STUDENT REPLICATE BRR-FAY WEIGHT66
617    W_FSTR67           FINAL STUDENT REPLICATE BRR-FAY WEIGHT67
618    W_FSTR68           FINAL STUDENT REPLICATE BRR-FAY WEIGHT68
619    W_FSTR69           FINAL STUDENT REPLICATE BRR-FAY WEIGHT69
620    W_FSTR70           FINAL STUDENT REPLICATE BRR-FAY WEIGHT70
621    W_FSTR71           FINAL STUDENT REPLICATE BRR-FAY WEIGHT71
622    W_FSTR72           FINAL STUDENT REPLICATE BRR-FAY WEIGHT72
623    W_FSTR73           FINAL STUDENT REPLICATE BRR-FAY WEIGHT73
624    W_FSTR74           FINAL STUDENT REPLICATE BRR-FAY WEIGHT74
625    W_FSTR75           FINAL STUDENT REPLICATE BRR-FAY WEIGHT75
626    W_FSTR76           FINAL STUDENT REPLICATE BRR-FAY WEIGHT76
627    W_FSTR77           FINAL STUDENT REPLICATE BRR-FAY WEIGHT77
628    W_FSTR78           FINAL STUDENT REPLICATE BRR-FAY WEIGHT78
629    W_FSTR79           FINAL STUDENT REPLICATE BRR-FAY WEIGHT79
630    W_FSTR80           FINAL STUDENT REPLICATE BRR-FAY WEIGHT80
631    WVARSTRR           RANDOMIZED FINAL VARIANCE STRATUM (1-80)
632    VAR_UNIT                    RANDOMLY ASSIGNED VARIANCE UNIT
633  SENWGT_STU  Senate weight - sum of weight within the count...
634     VER_STU                      Date of the database creation

[635 rows x 2 columns]

In [6]:
# Check for null values in relevant columns
columns = ['STIDSTD', 'ST01Q01', 'ST04Q01', 'ST13Q01', 
            'ST17Q01', 'ST28Q01', 'ST57Q01', 'ST57Q02', 'ST57Q03', 
            'ST57Q04', 'ST57Q05', 'MMINS', 'LMINS', 'SMINS',
            'PV1MATH', 'PV2MATH', 'PV3MATH', 'PV4MATH', 'PV5MATH',  
            'PV1READ', 'PV2READ',  'PV3READ', 'PV4READ', 'PV5READ',
            'PV1SCIE', 'PV2SCIE', 'PV3SCIE', 'PV4SCIE', 'PV5SCIE']

for x in columns:
    print(x, pisa[x].isna().sum())

STIDSTD 0
ST01Q01 0
ST04Q01 0
ST13Q01 27511
ST17Q01 42229
ST28Q01 11725
ST57Q01 184123
ST57Q02 215682
ST57Q03 201677
ST57Q04 205833
ST57Q05 195988
MMINS 202187
LMINS 202624
SMINS 214576
PV1MATH 0
PV2MATH 0
PV3MATH 0
PV4MATH 0
PV5MATH 0
PV1READ 0
PV2READ 0
PV3READ 0
PV4READ 0
PV5READ 0
PV1SCIE 0
PV2SCIE 0
PV3SCIE 0
PV4SCIE 0
PV5SCIE 0

In [7]:
pisa['CNT'].value_counts()

Mexico                      33806
Italy                       31073
Spain                       25313
Canada                      21544
Brazil                      19204
Australia                   14481
United Kingdom              12659
United Arab Emirates        11500
Switzerland                 11229
Qatar                       10966
Colombia                     9073
Finland                      8829
Belgium                      8597
Denmark                      7481
Jordan                       7038
Chile                        6856
Thailand                     6606
Japan                        6351
Chinese Taipei               6046
Peru                         6035
Slovenia                     5911
Argentina                    5908
Kazakhstan                   5808
Portugal                     5722
Indonesia                    5622
Singapore                    5546
Macao-China                  5335
Czech Republic               5327
Uruguay                      5315
Bulgaria                     5282
                            ...
Ireland                      5016
Croatia                      5008
Germany                      5001
United States of America     4978
Vietnam                      4959
Turkey                       4848
Hungary                      4810
Estonia                      4779
Austria                      4755
Montenegro                   4744
Albania                      4743
Sweden                       4736
Norway                       4686
Serbia                       4684
Slovak Republic              4678
Hong Kong-China              4670
Lithuania                    4618
France                       4613
Poland                       4607
Costa Rica                   4602
Netherlands                  4460
Tunisia                      4407
Latvia                       4306
New Zealand                  4291
Iceland                      3508
Florida (USA)                1896
Perm(Russian Federation)     1761
Massachusetts (USA)          1723
Connecticut (USA)            1697
Liechtenstein                 293
Name: CNT, Length: 68, dtype: int64

In [8]:
pisa.duplicated().sum()

0

<a id='issues1'></a>
### Identified Issues
Here we can see some of the issues noticed in the dataframes. These quality issues will be cleaned in the following section.

1. Narrow down the dataframe by only looking at variables of interest since there are more variables than needed
2. Make the variable names readable since they are codes that can only be read with the dictionary
3. Create an average of all Math, Reading, and Science scores since all 5 scores for each are not necessary
4. Missing values in relevant columns ('Mother Highest Schooling', 'Father Highest Schooling', 'How many books at home', 'Out-of-School Study Time - Homework', 'Out-of-School Study Time - Guided Homework', 'Out-of-School Study Time - Personal Tutor','Out-of-School Study Time - Commercial Company', 'Out-of-School Study Time - With Parent', 'Learning time (minutes per week)- Mathematics', 'Learning time (minutes per week)  - test language', 'Learning time (minutes per week) - Science')
5. Create a total for Out-of-School Study Time and Learning time (minutes per week)
6. Single countries have various entries in the country column (Florida (USA), Massachusetts (USA), Connecticut (USA) and United States of America)

<a id='cleaning1'></a>
### First Cleaning

In [9]:
# Create a copy to preserve the original dataframe
pisa_clean = pisa.copy()

### Narrow down the dataframe by only looking at variables of interest

There are 636 columns available in the original dataframe, which is far more than what is necessary. We will rather look at just the following variables.

In [10]:
pisa_clean = pisa_clean[['STIDSTD', 'ST04Q01', 'ST13Q01', 'ST14Q01', 'ST14Q02', 'ST14Q03', 'ST14Q04', 
                         'ST17Q01', 'ST18Q01', 'ST18Q02', 'ST18Q03', 'ST18Q04', 
                         'ST28Q01', 
                         'ST57Q01', 'ST57Q02', 'ST57Q03', 'ST57Q04', 'ST57Q05', 'MMINS', 
                         'LMINS', 'SMINS', 'PV1MATH', 'PV2MATH', 'PV3MATH', 'PV4MATH', 
                         'PV5MATH', 'PV1READ', 'PV2READ',  'PV3READ', 'PV4READ', 'PV5READ',
                         'PV1SCIE', 'PV2SCIE', 'PV3SCIE', 'PV4SCIE', 'PV5SCIE']]

In [11]:
# Check to see if the columns are correctly reduced
list(pisa_clean)

['STIDSTD',
 'ST04Q01',
 'ST13Q01',
 'ST14Q01',
 'ST14Q02',
 'ST14Q03',
 'ST14Q04',
 'ST17Q01',
 'ST18Q01',
 'ST18Q02',
 'ST18Q03',
 'ST18Q04',
 'ST28Q01',
 'ST57Q01',
 'ST57Q02',
 'ST57Q03',
 'ST57Q04',
 'ST57Q05',
 'MMINS',
 'LMINS',
 'SMINS',
 'PV1MATH',
 'PV2MATH',
 'PV3MATH',
 'PV4MATH',
 'PV5MATH',
 'PV1READ',
 'PV2READ',
 'PV3READ',
 'PV4READ',
 'PV5READ',
 'PV1SCIE',
 'PV2SCIE',
 'PV3SCIE',
 'PV4SCIE',
 'PV5SCIE']

### Create an average of all Math, Reading, and Science scores

For each of the Math, Reading, and Science scores, there are 5 scores provided. The variation between these scores is not needed, so rather we will look at the average for each of these major categories and remove the individual scores.

In [12]:
# Create average of Math scores
pisa_clean['Average Math Score']    = (pisa_clean['PV1MATH'] + pisa_clean['PV2MATH'] + pisa_clean['PV3MATH'] + pisa_clean['PV4MATH'] + pisa_clean['PV5MATH']) / 5

# Create average of Reading scores
pisa_clean['Average Reading Score'] = (pisa_clean['PV1READ'] + pisa_clean['PV2READ'] + pisa_clean['PV3READ'] + pisa_clean['PV4READ'] + pisa_clean['PV5READ']) / 5

# Create average of Science scores
pisa_clean['Average Science Score'] = (pisa_clean['PV1SCIE'] + pisa_clean['PV2SCIE'] + pisa_clean['PV3SCIE'] + pisa_clean['PV4SCIE'] + pisa_clean['PV5SCIE']) / 5

# Create average score
pisa_clean['Average Total Score']   = (pisa_clean['Average Math Score'] + pisa_clean['Average Reading Score'] + pisa_clean['Average Science Score'] +pisa_clean['Average Math Score']) / 3

In [13]:
# Remove the individual scores for Math, Reading, and Science
pisa_clean.drop(columns=['PV1MATH',  'PV2MATH', 'PV3MATH', 'PV4MATH', 'PV5MATH',   
                         'PV1READ', 'PV2READ',  'PV3READ', 'PV4READ',  'PV5READ',
                         'PV1SCIE',  'PV2SCIE', 'PV3SCIE',  'PV4SCIE', 'PV5SCIE'], inplace=True)

In [14]:
# Test to see accuracy of the Math score
print(pisa_clean['Average Math Score'].describe())
print('-'*22)

# Test to see accuracy of the Reading score
print(pisa_clean['Average Reading Score'].describe())
print('-'*22)

# Test to see accuracy of the Science score
print(pisa_clean['Average Science Score'].describe())

# Test to see accuracy of the Total score
print(pisa_clean['Average Total Score'].describe())

count    485490.000000
mean        469.651234
std         100.786610
min          54.767080
25%         396.019620
50%         465.734520
75%         540.123060
max         903.107960
Name: Average Math Score, dtype: float64
----------------------
count    485490.000000
mean        472.006964
std          98.863310
min           6.445400
25%         405.044200
50%         475.477980
75%         542.831195
max         849.359740
Name: Average Reading Score, dtype: float64
----------------------
count    485490.000000
mean        475.808094
std          97.998470
min          25.158540
25%         405.762800
50%         475.512860
75%         546.381920
max         857.832900
Name: Average Science Score, dtype: float64
count    485490.000000
mean        629.039175
std         128.839689
min         105.496473
25%         536.312167
50%         627.318087
75%         721.099990
max        1123.882273
Name: Average Total Score, dtype: float64

In [15]:
pisa_clean.sample(10)

,STIDSTD,ST04Q01,ST13Q01,ST14Q01,ST14Q02,ST14Q03,ST14Q04,ST17Q01,ST18Q01,ST18Q02,...,ST57Q03,ST57Q04,ST57Q05,MMINS,LMINS,SMINS,Average Math Score,Average Reading Score,Average Science Score,Average Total Score
437159,4154,Male,<ISCED level 2>,No,No,No,No,<ISCED level 2>,No,No,...,0.0,1.0,0.0,135.0,135.0,45.0,355.59276,326.93474,365.47930,467.866520
436644,3639,Male,<ISCED level 3A>,No,No,No,NaN,<ISCED level 3A>,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,514.65184,463.34562,499.29132,663.980207
19543,3301,Female,<ISCED level 1>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,234.15640,247.19326,219.73144,311.745833
369007,412,Female,<ISCED level 3A>,No,Yes,No,No,<ISCED level 3A>,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,609.37060,771.67624,722.99512,904.470853
371359,2764,Female,"<ISCED level 3B, 3C>",No,No,No,No,"<ISCED level 3B, 3C>",No,No,...,0.0,0.0,1.0,180.0,180.0,180.0,452.80420,531.07970,535.84484,657.510980
423315,540,Female,<ISCED level 3A>,No,No,No,Yes,<ISCED level 3A>,No,No,...,NaN,NaN,NaN,NaN,NaN,NaN,604.22964,564.52016,600.46622,791.148553
180950,5276,Male,"<ISCED level 3B, 3C>",NaN,Yes,NaN,NaN,<ISCED level 3A>,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,561.07648,524.29344,566.98992,737.812107
71769,16504,Male,She did not complete <ISCED level 1>,NaN,NaN,NaN,NaN,He did not complete <ISCED level 1>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,293.97882,282.26640,317.26966,395.831233
434157,1152,Female,<ISCED level 3A>,No,No,No,Yes,<ISCED level 3A>,No,Yes,...,NaN,NaN,NaN,NaN,NaN,NaN,492.29630,509.63334,477.75084,657.325593
15284,10542,Male,<ISCED level 3A>,No,No,No,No,<ISCED level 3A>,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,352.71068,364.22520,343.47258,471.039713

### Make the variable names readable

In the original dataframe, the variable names are all codes and unreadable without the dictionary. Therefore, we will change them to accurately reflect the information within the column.

In [16]:
# Rename columns
pisa_clean.rename({'STIDSTD': 'Student ID',
                   'ST04Q01': 'Gender', 
                   'ST13Q01': 'Mother - Highest Schooling', 
                   'ST14Q01': 'Mother Qualifications - ISCED level 6',
                   'ST14Q02': 'Mother Qualifications - ISCED level 5A',
                   'ST14Q03': 'Mother Qualifications - ISCED level 5B',
                   'ST14Q04': 'Mother Qualifications - ISCED level 4',
                   'ST17Q01': 'Father - Highest Schooling',
                   'ST18Q01': 'Father Qualifications - ISCED level 6',
                   'ST18Q02': 'Father Qualifications - ISCED level 5A',
                   'ST18Q03': 'Father Qualifications - ISCED level 5B',
                   'ST18Q04': 'Father Qualifications - ISCED level 4',
                   'ST28Q01': 'How many books at home', 
                   'ST57Q01': 'Out-of-School Study Time - Homework',
                   'ST57Q02': 'Out-of-School Study Time - Guided Homework',
                   'ST57Q03': 'Out-of-School Study Time - Personal Tutor',
                   'ST57Q04': 'Out-of-School Study Time - Commercial Company',
                   'ST57Q05': 'Out-of-School Study Time - With Parent',
                   'MMINS': 'Learning time (minutes per week)- <Mathematics>',
                   'LMINS': 'Learning time (minutes per week)  - <test language>',
                   'SMINS': 'Learning time (minutes per week) - <Science>'}, axis='columns', inplace=True)

In [17]:
# Check to see if the columns are correctly renamed
list(pisa_clean)

['Student ID',
 'Gender',
 'Mother - Highest Schooling',
 'Mother Qualifications - ISCED level 6',
 'Mother Qualifications - ISCED level 5A',
 'Mother Qualifications - ISCED level 5B',
 'Mother Qualifications - ISCED level 4',
 'Father - Highest Schooling',
 'Father Qualifications - ISCED level 6',
 'Father Qualifications - ISCED level 5A',
 'Father Qualifications - ISCED level 5B',
 'Father Qualifications - ISCED level 4',
 'How many books at home',
 'Out-of-School Study Time - Homework',
 'Out-of-School Study Time - Guided Homework',
 'Out-of-School Study Time - Personal Tutor',
 'Out-of-School Study Time - Commercial Company',
 'Out-of-School Study Time - With Parent',
 'Learning time (minutes per week)- <Mathematics>',
 'Learning time (minutes per week)  - <test language>',
 'Learning time (minutes per week) - <Science>',
 'Average Math Score',
 'Average Reading Score',
 'Average Science Score',
 'Average Total Score']

# Null

In [18]:
pisa_clean.replace(["NaN"], np.nan, inplace = True)
pisa_clean.dropna(inplace = True)

### Education
Multiple columns with the single variable. 

http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-isced-2011-en.pdf

In [19]:
father_edu = pisa_clean.copy()

In [20]:
father_edu[['<ISCED level 1>', 
            '<ISCED level 2>', 
            '<ISCED level 3A>', 
            '<ISCED level 3B, 3C>', 
            'He did not complete <ISCED level 1>']] = pd.get_dummies(father_edu['Father - Highest Schooling'])

In [21]:
father_edu.rename({'He did not complete <ISCED level 1>': '<ISCED level 0>',
                   '<ISCED level 3A>': '<ISCED level 3>', 
                   '<ISCED level 3B, 3C>': '<ISCED level 3>',
                   'Father Qualifications - ISCED level 4': '<ISCED level 4>',
                   'Father Qualifications - ISCED level 5A': '<ISCED level 5>',
                   'Father Qualifications - ISCED level 5B': '<ISCED level 5>',
                   'Father Qualifications - ISCED level 6': '<ISCED level 6>'}, axis='columns', inplace=True)

In [22]:
father_edu['<ISCED level 0>'] = father_edu['<ISCED level 0>'].astype(str)
father_edu['<ISCED level 1>'] = father_edu['<ISCED level 1>'].astype(str)
father_edu['<ISCED level 2>'] = father_edu['<ISCED level 2>'].astype(str)
father_edu['<ISCED level 3>'] = father_edu['<ISCED level 3>'].astype(str)

In [23]:
father_edu['<ISCED level 0>'] = father_edu['<ISCED level 0>'].replace(regex='1', value='<ISCED level 0>')
father_edu['<ISCED level 1>'] = father_edu['<ISCED level 1>'].replace(regex='1', value='<ISCED level 1>')
father_edu['<ISCED level 2>'] = father_edu['<ISCED level 2>'].replace(regex='1', value='<ISCED level 2>')
father_edu['<ISCED level 3>'] = father_edu['<ISCED level 3>'].replace(regex='1', value='<ISCED level 3>')
father_edu['<ISCED level 4>'] = father_edu['<ISCED level 4>'].replace(regex='Yes', value='<ISCED level 4>')
father_edu['<ISCED level 5>'] = father_edu['<ISCED level 5>'].replace(regex='Yes', value='<ISCED level 5>')
father_edu['<ISCED level 6>'] = father_edu['<ISCED level 6>'].replace(regex='Yes', value='<ISCED level 6>')

In [24]:
father_edu.sample(10)

,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Father - Highest Schooling,<ISCED level 6>,<ISCED level 5>,...,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,<ISCED level 1>,<ISCED level 2>,<ISCED level 3>,<ISCED level 3>,<ISCED level 0>
148573,2991,Male,She did not complete <ISCED level 1>,No,No,No,No,<ISCED level 1>,No,No,...,275.0,453.58312,455.72714,494.90864,619.267340,<ISCED level 1>,0,0,0,0
23211,1061,Female,<ISCED level 3A>,No,No,No,No,<ISCED level 2>,No,No,...,180.0,370.62626,412.33032,389.63074,514.404527,0,<ISCED level 2>,0,0,0
62421,7156,Male,<ISCED level 3A>,No,No,No,No,<ISCED level 3A>,No,No,...,90.0,289.53888,340.56782,378.44090,432.695493,0,0,<ISCED level 3>,0,0
183432,7758,Female,<ISCED level 3A>,No,Yes,No,No,"<ISCED level 3B, 3C>",No,No,...,180.0,594.10342,612.09930,622.93922,807.748453,0,0,0,<ISCED level 3>,0
153207,7625,Female,<ISCED level 2>,No,No,No,No,<ISCED level 2>,No,No,...,150.0,471.73236,447.67714,451.36142,614.167760,0,<ISCED level 2>,0,0,0
48751,7365,Male,"<ISCED level 3B, 3C>",No,No,Yes,No,<ISCED level 3A>,No,<ISCED level 5>,...,200.0,666.23306,579.06628,633.28980,848.274067,0,0,<ISCED level 3>,0,0
249940,9351,Female,<ISCED level 3A>,No,Yes,No,No,<ISCED level 3A>,No,<ISCED level 5>,...,100.0,510.28976,581.59782,483.81202,695.329787,0,0,<ISCED level 3>,0,0
433166,161,Female,"<ISCED level 3B, 3C>",No,No,No,No,"<ISCED level 3B, 3C>",No,No,...,45.0,482.63748,485.24800,492.57740,647.700120,0,0,0,<ISCED level 3>,0
235390,3364,Female,<ISCED level 3A>,No,No,No,Yes,<ISCED level 3A>,No,No,...,120.0,392.67020,435.04760,451.82768,557.405227,0,0,<ISCED level 3>,0,0
262258,21669,Female,<ISCED level 2>,No,No,No,Yes,<ISCED level 2>,No,No,...,110.0,484.74062,489.53728,471.22342,643.413980,0,<ISCED level 2>,0,0,0

In [25]:
father_edu = pd.melt(father_edu, 
                     id_vars=['Student ID', 'Gender',
                            'Mother - Highest Schooling', 
                            'Mother Qualifications - ISCED level 6', 
                            'Mother Qualifications - ISCED level 5A',
                            'Mother Qualifications - ISCED level 5B',
                            'Mother Qualifications - ISCED level 4',
                            'How many books at home',
                            'Out-of-School Study Time - Homework',
                            'Out-of-School Study Time - Guided Homework',
                            'Out-of-School Study Time - Personal Tutor',
                            'Out-of-School Study Time - Commercial Company',
                            'Out-of-School Study Time - With Parent',
                            'Learning time (minutes per week)- <Mathematics>',
                            'Learning time (minutes per week)  - <test language>',
                            'Learning time (minutes per week) - <Science>',
                            'Average Math Score',
                            'Average Reading Score',
                            'Average Science Score',
                            'Average Total Score'], var_name='Completed_edu - Father', value_name='Education - Father')

In [26]:
father_edu.sample(10)

,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Completed_edu - Father,Education - Father
102897,1624,Male,<ISCED level 2>,No,No,No,Yes,26-100 books,10.0,0.0,...,0.0,200.0,200.0,350.0,557.80496,532.31292,570.53338,739.485407,Father - Highest Schooling,"<ISCED level 3B, 3C>"
739764,844,Female,<ISCED level 2>,No,No,No,No,26-100 books,1.0,1.0,...,1.0,245.0,245.0,175.0,525.86850,516.06724,550.67138,706.158540,<ISCED level 2>,0
529019,19085,Male,<ISCED level 3A>,No,Yes,No,No,26-100 books,2.0,0.0,...,1.0,300.0,240.0,120.0,513.71710,509.69802,497.42634,678.186187,<ISCED level 4>,<ISCED level 4>
208301,3808,Male,"<ISCED level 3B, 3C>",No,No,No,No,11-25 books,0.0,0.0,...,0.0,180.0,180.0,180.0,434.26546,420.92270,445.48676,578.313460,<ISCED level 6>,No
181960,5608,Female,"<ISCED level 3B, 3C>",No,No,No,Yes,201-500 books,5.0,3.0,...,1.0,240.0,360.0,120.0,494.63312,582.78926,531.92838,701.327960,<ISCED level 6>,No
1127220,612,Female,<ISCED level 3A>,No,No,No,Yes,26-100 books,8.0,2.0,...,2.0,225.0,225.0,225.0,457.94516,478.09920,464.32302,619.437513,<ISCED level 0>,0
1083130,3984,Male,<ISCED level 2>,No,No,No,No,201-500 books,8.0,2.0,...,0.0,210.0,210.0,140.0,626.42934,543.37974,585.91942,794.052613,<ISCED level 0>,0
1038628,58,Female,<ISCED level 1>,No,No,No,No,0-10 books,5.0,1.0,...,0.0,135.0,135.0,135.0,405.67848,454.19048,436.53486,567.360767,<ISCED level 0>,0
911452,3640,Male,<ISCED level 2>,No,No,No,No,26-100 books,1.0,0.0,...,0.0,225.0,225.0,250.0,528.36112,567.27770,561.76798,728.589307,<ISCED level 3>,<ISCED level 3>
288177,1367,Female,<ISCED level 3A>,No,Yes,No,No,More than 500 books,20.0,1.0,...,0.0,180.0,180.0,180.0,546.66614,548.31622,541.71954,727.789347,<ISCED level 5>,<ISCED level 5>

In [27]:
father_edu = father_edu[(father_edu['Education - Father'] != '0')] 
father_edu = father_edu[(father_edu['Education - Father'] != 'No')]

In [28]:
father_edu.sample(70)

,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Completed_edu - Father,Education - Father
898853,1437,Male,<ISCED level 3A>,Yes,No,No,No,26-100 books,5.0,1.0,...,1.0,60.0,60.0,60.0,463.63140,570.88646,543.39800,680.515753,<ISCED level 3>,<ISCED level 3>
833448,3464,Female,<ISCED level 3A>,No,No,Yes,No,More than 500 books,3.0,1.0,...,1.0,180.0,270.0,180.0,471.34288,503.27884,437.18762,627.717407,<ISCED level 3>,<ISCED level 3>
99656,4593,Female,<ISCED level 3A>,No,No,No,No,11-25 books,7.0,0.0,...,0.0,180.0,180.0,90.0,599.47812,532.90660,577.52704,769.796627,Father - Highest Schooling,<ISCED level 1>
77407,30829,Male,<ISCED level 2>,No,No,No,No,26-100 books,8.0,0.0,...,0.0,180.0,360.0,120.0,528.90636,449.47196,534.91234,680.732340,Father - Highest Schooling,<ISCED level 2>
993125,627,Female,"<ISCED level 3B, 3C>",No,Yes,No,No,201-500 books,3.0,1.0,...,2.0,200.0,200.0,200.0,591.22138,602.64704,596.27004,793.786613,<ISCED level 3>,<ISCED level 3>
17527,3474,Female,<ISCED level 3A>,No,No,No,Yes,More than 500 books,4.0,0.0,...,1.0,180.0,180.0,180.0,523.14222,550.54030,522.41702,706.413920,Father - Highest Schooling,<ISCED level 3A>
808729,6942,Male,<ISCED level 3A>,No,Yes,No,No,11-25 books,4.0,1.0,...,0.0,250.0,200.0,100.0,528.51690,520.20352,522.51026,699.915860,<ISCED level 3>,<ISCED level 3>
537072,408,Female,<ISCED level 3A>,No,No,No,No,201-500 books,5.0,0.0,...,0.0,200.0,200.0,200.0,590.05296,545.93328,551.23088,759.090027,<ISCED level 4>,<ISCED level 4>
104444,1026,Male,<ISCED level 3A>,No,Yes,No,No,More than 500 books,11.0,2.0,...,3.0,225.0,135.0,360.0,549.70398,576.09908,594.03208,756.513040,Father - Highest Schooling,<ISCED level 3A>
328036,453,Female,"<ISCED level 3B, 3C>",No,Yes,No,No,11-25 books,28.0,0.0,...,0.0,200.0,160.0,320.0,553.52078,549.03108,594.40508,750.159240,<ISCED level 5>,<ISCED level 5>
85069,3662,Male,"<ISCED level 3B, 3C>",No,No,No,No,26-100 books,24.0,4.0,...,0.0,315.0,315.0,270.0,587.56036,575.85850,580.51100,777.163407,Father - Highest Schooling,"<ISCED level 3B, 3C>"
107345,4216,Male,<ISCED level 3A>,No,No,No,Yes,26-100 books,20.0,0.0,...,0.0,270.0,180.0,360.0,668.10250,603.92662,624.71092,854.947513,Father - Highest Schooling,<ISCED level 3A>
439888,797,Male,<ISCED level 2>,No,No,Yes,No,101-200 books,26.0,0.0,...,0.0,320.0,280.0,320.0,648.47328,599.59608,615.94554,837.496060,<ISCED level 5>,<ISCED level 5>
99373,3970,Male,<ISCED level 2>,No,No,No,No,11-25 books,16.0,1.0,...,1.0,240.0,160.0,120.0,706.73780,615.07360,672.17458,900.241260,Father - Highest Schooling,"<ISCED level 3B, 3C>"
378986,7285,Male,"<ISCED level 3B, 3C>",No,No,Yes,Yes,101-200 books,5.0,0.0,...,0.0,232.0,295.0,80.0,444.93690,467.67614,462.92428,606.824740,<ISCED level 5>,<ISCED level 5>
992658,3846,Male,"<ISCED level 3B, 3C>",No,No,Yes,No,0-10 books,2.0,2.0,...,1.0,180.0,180.0,315.0,451.86946,379.86314,449.58970,577.730587,<ISCED level 3>,<ISCED level 3>
108399,1372,Male,<ISCED level 3A>,No,No,No,No,11-25 books,1.0,1.0,...,0.0,225.0,225.0,90.0,466.43558,379.38194,453.22642,588.493173,Father - Highest Schooling,"<ISCED level 3B, 3C>"
919563,1598,Female,"<ISCED level 3B, 3C>",No,No,No,No,0-10 books,1.0,1.0,...,1.0,100.0,100.0,250.0,415.10362,415.66644,424.03952,556.637733,<ISCED level 3>,<ISCED level 3>
1977,5139,Female,<ISCED level 3A>,No,Yes,Yes,Yes,26-100 books,21.0,0.0,...,2.0,180.0,180.0,270.0,486.14270,512.96942,550.11190,678.455573,Father - Highest Schooling,<ISCED level 3A>
700088,18215,Male,<ISCED level 3A>,No,No,No,Yes,101-200 books,4.0,2.0,...,0.0,240.0,180.0,180.0,457.47780,444.74048,475.60612,611.767400,<ISCED level 2>,<ISCED level 2>
129579,15316,Male,<ISCED level 3A>,No,Yes,No,Yes,11-25 books,2.0,0.0,...,0.0,360.0,135.0,135.0,411.20892,413.30424,432.89816,556.206747,<ISCED level 6>,<ISCED level 6>
513730,604,Male,<ISCED level 3A>,Yes,Yes,Yes,Yes,201-500 books,6.0,1.0,...,3.0,180.0,180.0,270.0,669.11514,601.68114,642.52144,860.810953,<ISCED level 4>,<ISCED level 4>
31689,2461,Male,<ISCED level 3A>,No,No,Yes,No,26-100 books,1.0,0.0,...,0.0,315.0,225.0,315.0,516.75494,502.07954,510.29466,681.961360,Father - Highest Schooling,<ISCED level 3A>
428822,521,Male,<ISCED level 3A>,No,No,Yes,No,101-200 books,7.0,0.0,...,0.0,150.0,150.0,0.0,639.35974,591.97760,601.21222,823.969767,<ISCED level 5>,<ISCED level 5>
32418,4155,Male,<ISCED level 3A>,No,No,No,No,201-500 books,1.0,1.0,...,1.0,180.0,135.0,360.0,646.21436,624.13560,612.40208,842.988800,Father - Highest Schooling,<ISCED level 3A>
238343,5590,Male,<ISCED level 3A>,No,No,No,No,101-200 books,12.0,0.0,...,2.0,200.0,200.0,150.0,551.65134,537.84632,529.59716,723.582053,<ISCED level 5>,<ISCED level 5>
861377,296,Female,<ISCED level 3A>,No,No,No,No,101-200 books,6.0,0.0,...,0.0,240.0,240.0,160.0,538.72098,557.60964,555.52032,730.190640,<ISCED level 3>,<ISCED level 3>
446107,4939,Female,"<ISCED level 3B, 3C>",No,No,Yes,Yes,101-200 books,7.0,4.0,...,0.0,200.0,200.0,200.0,543.86196,540.13482,555.33382,727.730853,<ISCED level 5>,<ISCED level 5>
35920,4548,Male,<ISCED level 2>,No,No,No,No,0-10 books,5.0,4.0,...,0.0,160.0,270.0,225.0,412.61100,384.83518,428.51548,546.190887,Father - Highest Schooling,<ISCED level 2>
82207,3928,Female,"<ISCED level 3B, 3C>",No,Yes,Yes,No,26-100 books,6.0,0.0,...,1.0,180.0,180.0,180.0,515.19708,564.59958,506.93770,700.643813,Father - Highest Schooling,"<ISCED level 3B, 3C>"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
911044,2562,Female,<ISCED level 3A>,No,No,Yes,No,0-10 books,17.0,0.0,...,0.0,275.0,275.0,275.0,564.42592,567.61796,545.54270,747.337500,<ISCED level 3>,<ISCED level 3>
89316,3563,Female,<ISCED level 3A>,No,No,Yes,No,101-200 books,3.0,0.0,...,0.0,180.0,225.0,135.0,499.85200,576.83194,548.15368,708.229873,Father - Highest Schooling,<ISCED level 3A>
446980,3124,Female,"<ISCED level 3B, 3C>",No,No,Yes,No,More than 500 books,10.0,3.0,...,0.0,270.0,180.0,405.0,521.19490,629.01816,587.59794,753.001967,<ISCED level 5>,<ISCED level 5>
79874,1490,Female,<ISCED level 3A>,No,Yes,No,No,201-500 books,3.0,0.0,...,1.0,180.0,180.0,270.0,566.13960,576.83196,583.02872,764.046627,Father - Highest Schooling,<ISCED level 3A>
40,235,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,0-10 books,4.0,0.0,...,1.0,215.0,135.0,90.0,503.51300,592.93992,494.16262,698.042847,Father - Highest Schooling,"<ISCED level 3B, 3C>"
946270,471,Male,"<ISCED level 3B, 3C>",No,No,No,No,101-200 books,10.0,0.0,...,0.0,180.0,270.0,180.0,547.83454,553.40404,586.47894,745.184020,<ISCED level 3>,<ISCED level 3>
195039,252,Male,<ISCED level 3A>,No,No,Yes,No,More than 500 books,3.0,0.0,...,0.0,250.0,200.0,200.0,680.40972,553.56442,647.46364,853.949167,<ISCED level 6>,<ISCED level 6>
81083,382,Male,<ISCED level 3A>,No,No,No,No,201-500 books,4.0,0.0,...,0.0,200.0,200.0,100.0,544.79670,536.96418,565.03170,730.529760,Father - Highest Schooling,<ISCED level 3A>
86913,684,Female,<ISCED level 2>,No,No,No,Yes,11-25 books,6.0,0.0,...,1.0,150.0,150.0,300.0,633.82926,578.42060,651.84634,832.641820,Father - Highest Schooling,<ISCED level 2>
103396,3046,Female,<ISCED level 1>,No,No,No,No,11-25 books,4.0,3.0,...,4.0,180.0,180.0,150.0,307.22078,298.18796,348.13500,420.254840,Father - Highest Schooling,<ISCED level 2>
71803,15814,Male,<ISCED level 3A>,No,No,No,No,101-200 books,12.0,0.0,...,0.0,220.0,275.0,110.0,583.19834,576.66046,583.49496,775.517367,Father - Highest Schooling,<ISCED level 3A>
921157,1661,Female,"<ISCED level 3B, 3C>",No,No,No,No,0-10 books,4.0,0.0,...,0.0,100.0,200.0,100.0,498.29412,517.17926,501.06304,671.610180,<ISCED level 3>,<ISCED level 3>
13861,6436,Male,She did not complete <ISCED level 1>,No,No,No,No,26-100 books,1.0,1.0,...,1.0,255.0,200.0,150.0,358.86430,356.28592,336.29242,470.102313,Father - Highest Schooling,<ISCED level 1>
26299,6590,Male,<ISCED level 3A>,No,No,Yes,No,101-200 books,4.0,0.0,...,3.0,180.0,180.0,90.0,470.95342,430.46586,482.78626,618.386320,Father - Highest Schooling,"<ISCED level 3B, 3C>"
563691,5055,Male,<ISCED level 3A>,No,Yes,Yes,Yes,0-10 books,5.0,2.0,...,0.0,200.0,200.0,200.0,533.34632,502.07956,514.30436,694.358853,<ISCED level 4>,<ISCED level 4>
24460,1839,Male,<ISCED level 3A>,No,Yes,No,Yes,26-100 books,8.0,5.0,...,1.0,180.0,180.0,90.0,594.49290,557.33356,562.98024,769.766533,Father - Highest Schooling,<ISCED level 2>
790984,3437,Female,<ISCED level 3A>,No,No,Yes,Yes,26-100 books,3.0,0.0,...,0.0,150.0,180.0,180.0,529.45164,495.81230,458.07536,670.930313,<ISCED level 2>,<ISCED level 2>
845512,1024,Male,"<ISCED level 3B, 3C>",No,Yes,Yes,No,201-500 books,0.0,0.0,...,0.0,180.0,135.0,90.0,540.35676,544.26188,579.95150,734.975633,<ISCED level 3>,<ISCED level 3>
51709,3991,Male,<ISCED level 3A>,No,No,Yes,Yes,101-200 books,12.0,1.0,...,1.0,150.0,138.0,300.0,467.83768,462.70406,509.17566,635.851693,Father - Highest Schooling,"<ISCED level 3B, 3C>"
784965,1730,Female,<ISCED level 3A>,No,No,No,No,11-25 books,3.0,0.0,...,0.0,270.0,270.0,270.0,466.66926,440.13120,423.85302,599.107580,<ISCED level 2>,<ISCED level 2>
472699,1162,Female,<ISCED level 3A>,Yes,No,Yes,No,26-100 books,2.0,1.0,...,3.0,300.0,300.0,300.0,352.94438,412.17144,387.48602,501.848740,<ISCED level 4>,<ISCED level 4>
404105,1562,Female,<ISCED level 2>,No,No,No,No,26-100 books,10.0,2.0,...,1.0,240.0,200.0,140.0,449.61052,488.58410,419.09734,602.300827,<ISCED level 5>,<ISCED level 5>
20132,10937,Male,<ISCED level 3A>,No,No,Yes,Yes,101-200 books,9.0,0.0,...,0.0,300.0,300.0,300.0,587.32670,578.82570,588.71688,780.731993,Father - Highest Schooling,<ISCED level 3A>
51370,3033,Female,<ISCED level 3A>,No,No,No,No,0-10 books,3.0,1.0,...,0.0,200.0,250.0,150.0,464.72192,482.30904,500.31704,637.356640,Father - Highest Schooling,<ISCED level 2>
55159,2957,Female,<ISCED level 3A>,No,No,No,No,101-200 books,4.0,2.0,...,0.0,225.0,180.0,270.0,476.87332,575.95822,547.87394,692.526267,Father - Highest Schooling,<ISCED level 3A>
359638,3864,Male,<ISCED level 3A>,No,Yes,No,No,201-500 books,1.0,1.0,...,0.0,350.0,350.0,350.0,594.72660,622.53174,591.32786,801.104267,<ISCED level 5>,<ISCED level 5>
848995,2022,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,26-100 books,2.0,0.0,...,4.0,180.0,180.0,135.0,534.59262,487.96532,504.23350,687.128020,<ISCED level 3>,<ISCED level 3>
956725,23737,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,26-100 books,30.0,0.0,...,0.0,180.0,180.0,180.0,675.65820,666.95948,693.43528,903.903720,<ISCED level 3>,<ISCED level 3>
282375,11402,Female,<ISCED level 3A>,No,Yes,No,No,26-100 books,1.0,0.0,...,0.0,200.0,200.0,300.0,608.66958,675.48524,658.09400,850.306133,<ISCED level 5>,<ISCED level 5>
676308,1846,Female,<ISCED level 1>,No,No,No,No,11-25 books,3.0,3.0,...,4.0,210.0,210.0,240.0,543.47250,497.16264,460.59308,681.566907,<ISCED level 1>,<ISCED level 1>

In [29]:
father_edu = father_edu[(father_edu['Completed_edu - Father'] != 'Father - Highest Schooling')]

In [30]:
father_edu['Education - Father'].value_counts()

<ISCED level 3>    84016
<ISCED level 5>    48776
<ISCED level 4>    26281
<ISCED level 2>    21813
<ISCED level 6>     6672
<ISCED level 1>     5901
<ISCED level 0>     2264
Name: Education - Father, dtype: int64

In [31]:
father_edu.drop(columns=['Completed_edu - Father'], axis=1, inplace=True)

In [32]:
father_edu.sample(10)

,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father
448249,1688,Female,<ISCED level 3A>,No,Yes,No,No,101-200 books,5.0,0.0,...,7.0,0.0,350.0,210.0,350.0,650.03116,600.82010,623.49870,841.460373,<ISCED level 5>
915143,11434,Male,<ISCED level 3A>,No,Yes,No,No,11-25 books,1.0,0.0,...,0.0,0.0,225.0,225.0,540.0,489.33636,514.99088,520.83178,671.498460,<ISCED level 3>
263884,4499,Female,<ISCED level 3A>,No,Yes,Yes,Yes,26-100 books,6.0,2.0,...,0.0,0.0,180.0,420.0,240.0,449.92212,488.02810,475.51288,621.128407,<ISCED level 5>
898380,173,Female,<ISCED level 3A>,No,No,No,Yes,26-100 books,1.0,1.0,...,0.0,1.0,225.0,225.0,225.0,492.76366,524.48694,507.49722,672.503827,<ISCED level 3>
845628,1349,Female,<ISCED level 3A>,Yes,Yes,No,No,201-500 books,1.0,1.0,...,0.0,1.0,180.0,135.0,180.0,575.25316,553.24092,541.71954,748.488927,<ISCED level 3>
819685,15710,Male,<ISCED level 3A>,No,No,No,No,More than 500 books,12.0,10.0,...,0.0,0.0,375.0,375.0,375.0,557.57126,557.01278,521.95078,731.368693,<ISCED level 3>
268369,10274,Female,<ISCED level 3A>,No,No,No,No,101-200 books,5.0,1.0,...,0.0,1.0,220.0,165.0,330.0,519.71492,523.29546,509.17570,690.633667,<ISCED level 5>
784806,1282,Male,<ISCED level 2>,No,No,No,No,0-10 books,2.0,1.0,...,0.0,1.0,250.0,250.0,250.0,382.62190,422.04546,413.50242,533.597227,<ISCED level 2>
886402,656,Female,"<ISCED level 3B, 3C>",No,No,No,Yes,26-100 books,4.0,0.0,...,0.0,1.0,180.0,180.0,120.0,353.80122,412.01262,395.69190,505.102320,<ISCED level 3>
721831,2425,Male,<ISCED level 3A>,No,No,No,No,0-10 books,3.0,2.0,...,0.0,0.0,240.0,240.0,240.0,453.97258,404.88382,443.34204,585.390340,<ISCED level 2>

In [33]:
father_edu.duplicated().sum()

6901

In [34]:
# https://stackoverflow.com/questions/33042777/removing-duplicates-from-pandas-dataframe-with-condition-for-retaining-original
father_edu['Education - Father'] = father_edu['Education - Father'].astype('category')

father_edu['Education - Father'] = father_edu['Education - Father'].cat.set_categories(['<ISCED level 0>', 
                                                                                        '<ISCED level 1>', 
                                                                                        '<ISCED level 2>', 
                                                                                        '<ISCED level 3>',
                                                                                        '<ISCED level 4>', 
                                                                                        '<ISCED level 5>', 
                                                                                        '<ISCED level 6>'], ordered=True)
father_edu.sort_values(['Education - Father'], inplace=True)
father_edu_clean = father_edu.drop_duplicates(subset='Student ID', keep='last')

In [35]:
father_edu_clean.duplicated().sum()

0

In [36]:
father_edu.shape

(195723, 21)

### Mother Edu

In [37]:
mother_edu = father_edu_clean.copy()

In [38]:
mother_edu.head()

,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father
1055573,6301,Female,She did not complete <ISCED level 1>,No,No,No,No,0-10 books,0.0,0.0,...,0.0,1.0,540.0,720.0,90.0,301.69028,311.29408,287.52330,400.732647,<ISCED level 0>
1048110,16914,Male,<ISCED level 3A>,No,Yes,No,No,26-100 books,0.0,0.0,...,0.0,0.0,280.0,280.0,280.0,497.43728,474.25206,511.50690,660.211173,<ISCED level 0>
1047956,16487,Male,<ISCED level 3A>,No,No,No,No,11-25 books,1.0,1.0,...,0.0,1.0,400.0,400.0,400.0,389.00920,406.72830,441.38380,542.043500,<ISCED level 0>
1047644,15611,Female,<ISCED level 3A>,No,No,No,No,26-100 books,2.0,0.0,...,0.0,0.0,375.0,375.0,375.0,383.71240,405.57868,411.73070,528.244727,<ISCED level 0>
1047154,14175,Male,<ISCED level 3A>,No,Yes,No,No,201-500 books,1.0,1.0,...,0.0,1.0,400.0,0.0,0.0,636.16608,622.45152,627.97466,840.919447,<ISCED level 0>

In [39]:
mother_edu['Mother - Highest Schooling'].value_counts()

<ISCED level 3A>                         15433
<ISCED level 3B, 3C>                      3798
<ISCED level 2>                           3605
<ISCED level 1>                            532
She did not complete <ISCED level 1>       152
Name: Mother - Highest Schooling, dtype: int64

In [40]:
pisa_clean['Mother - Highest Schooling'].value_counts()

<ISCED level 3A>                         63289
<ISCED level 3B, 3C>                     23470
<ISCED level 2>                          19733
<ISCED level 1>                           5149
She did not complete <ISCED level 1>      2353
Name: Mother - Highest Schooling, dtype: int64

In [41]:
mother_edu[['<ISCED level 1>', 
            '<ISCED level 2>', 
            '<ISCED level 3A>', 
            '<ISCED level 3B, 3C>', 
            'She did not complete <ISCED level 1>']] = pd.get_dummies(mother_edu['Mother - Highest Schooling'])

In [42]:
mother_edu.rename({'She did not complete <ISCED level 1>': '<ISCED level 0>',
                   '<ISCED level 3A>': '<ISCED level 3>', 
                   '<ISCED level 3B, 3C>': '<ISCED level 3>',
                   'Mother Qualifications - ISCED level 4': '<ISCED level 4>',
                   'Mother Qualifications - ISCED level 5A': '<ISCED level 5>',
                   'Mother Qualifications - ISCED level 5B': '<ISCED level 5>',
                   'Mother Qualifications - ISCED level 6': '<ISCED level 6>'}, axis='columns', inplace=True)

In [43]:
mother_edu['<ISCED level 0>'] = mother_edu['<ISCED level 0>'].astype(str)
mother_edu['<ISCED level 1>'] = mother_edu['<ISCED level 1>'].astype(str)
mother_edu['<ISCED level 2>'] = mother_edu['<ISCED level 2>'].astype(str)
mother_edu['<ISCED level 3>'] = mother_edu['<ISCED level 3>'].astype(str)

In [44]:
mother_edu['<ISCED level 0>'] = mother_edu['<ISCED level 0>'].replace(regex='1', value='<ISCED level 0>')
mother_edu['<ISCED level 1>'] = mother_edu['<ISCED level 1>'].replace(regex='1', value='<ISCED level 1>')
mother_edu['<ISCED level 2>'] = mother_edu['<ISCED level 2>'].replace(regex='1', value='<ISCED level 2>')
mother_edu['<ISCED level 3>'] = mother_edu['<ISCED level 3>'].replace(regex='1', value='<ISCED level 3>')
mother_edu['<ISCED level 4>'] = mother_edu['<ISCED level 4>'].replace(regex='Yes', value='<ISCED level 4>')
mother_edu['<ISCED level 5>'] = mother_edu['<ISCED level 5>'].replace(regex='Yes', value='<ISCED level 5>')
mother_edu['<ISCED level 6>'] = mother_edu['<ISCED level 6>'].replace(regex='Yes', value='<ISCED level 6>')

In [45]:
mother_edu.sample(10)

,Student ID,Gender,Mother - Highest Schooling,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>,<ISCED level 4>,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,<ISCED level 1>,<ISCED level 2>,<ISCED level 3>,<ISCED level 3>,<ISCED level 0>
870885,18748,Male,<ISCED level 3A>,No,No,No,No,11-25 books,9.0,0.0,...,569.02166,544.18166,600.18650,760.803827,<ISCED level 3>,0,0,<ISCED level 3>,0,0
210761,4342,Female,<ISCED level 3A>,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>,No,11-25 books,10.0,0.0,...,661.16996,634.18112,605.68816,854.069733,<ISCED level 6>,0,0,<ISCED level 3>,0,0
248339,11624,Male,<ISCED level 3A>,<ISCED level 6>,<ISCED level 5>,No,No,0-10 books,3.0,1.0,...,425.85294,381.46704,399.04886,544.073927,<ISCED level 5>,0,0,<ISCED level 3>,0,0
302277,22418,Male,<ISCED level 3A>,No,<ISCED level 5>,No,No,More than 500 books,30.0,0.0,...,509.90028,542.81838,544.79670,702.471880,<ISCED level 5>,0,0,<ISCED level 3>,0,0
178084,2244,Female,<ISCED level 3A>,<ISCED level 6>,<ISCED level 5>,No,No,101-200 books,4.0,2.0,...,524.07696,504.62918,497.70608,683.496393,<ISCED level 6>,0,0,<ISCED level 3>,0,0
281689,9405,Male,"<ISCED level 3B, 3C>",No,No,<ISCED level 5>,<ISCED level 4>,26-100 books,1.0,0.0,...,569.87850,557.01280,558.13130,751.633700,<ISCED level 5>,0,0,0,<ISCED level 3>,0
874111,27372,Male,"<ISCED level 3B, 3C>",No,<ISCED level 5>,No,No,26-100 books,4.0,1.0,...,456.85466,452.84012,426.65052,597.733320,<ISCED level 3>,0,0,0,<ISCED level 3>,0
385728,20642,Male,<ISCED level 3A>,No,No,No,<ISCED level 4>,201-500 books,8.0,1.0,...,438.16016,413.54480,435.78890,575.218007,<ISCED level 5>,0,0,<ISCED level 3>,0,0
363127,13981,Female,<ISCED level 3A>,No,<ISCED level 5>,No,No,201-500 books,6.0,0.0,...,586.85932,574.13128,639.44424,795.764720,<ISCED level 5>,0,0,<ISCED level 3>,0,0
217681,3824,Female,<ISCED level 3A>,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>,<ISCED level 4>,201-500 books,20.0,0.0,...,595.19398,654.35664,552.62962,799.124740,<ISCED level 6>,0,0,<ISCED level 3>,0,0

In [46]:
mother_edu = pd.melt(mother_edu, 
                     id_vars=['Student ID', 'Gender',
                            'How many books at home',
                            'Out-of-School Study Time - Homework',
                            'Out-of-School Study Time - Guided Homework',
                            'Out-of-School Study Time - Personal Tutor',
                            'Out-of-School Study Time - Commercial Company',
                            'Out-of-School Study Time - With Parent',
                            'Learning time (minutes per week)- <Mathematics>',
                            'Learning time (minutes per week)  - <test language>',
                            'Learning time (minutes per week) - <Science>',
                            'Average Math Score',
                            'Average Reading Score',
                            'Average Science Score',
                            'Average Total Score',
                             'Education - Father'], var_name='Completed_edu - Mother', value_name='Education - Mother')

In [47]:
mother_edu.sample(10)

,Student ID,Gender,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Completed_edu - Mother,Education - Mother
231297,11342,Female,11-25 books,3.0,2.0,2.0,1.0,1.0,225.0,45.0,90.0,365.64106,394.61720,364.36030,496.753207,<ISCED level 6>,<ISCED level 0>,0
129125,10887,Female,101-200 books,12.0,0.0,0.0,0.0,1.0,300.0,240.0,420.0,610.85060,614.87942,636.27376,824.284793,<ISCED level 5>,<ISCED level 1>,0
181962,4682,Male,26-100 books,3.0,0.0,0.0,0.0,0.0,200.0,160.0,0.0,576.81102,583.47698,614.17382,783.757613,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
95094,24426,Female,0-10 books,6.0,0.0,0.0,0.0,0.0,150.0,200.0,400.0,474.77024,439.97232,487.63520,625.716000,<ISCED level 2>,<ISCED level 4>,No
216823,17743,Male,26-100 books,2.0,0.0,0.0,0.0,0.0,300.0,375.0,300.0,506.08350,534.31776,550.85788,699.114213,<ISCED level 3>,<ISCED level 0>,0
12461,2578,Male,26-100 books,2.0,0.0,0.0,0.0,0.0,270.0,270.0,405.0,599.78968,516.27400,573.79708,763.216813,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
175667,7029,Male,101-200 books,1.0,0.0,0.0,0.0,0.0,360.0,315.0,450.0,483.26066,501.75880,530.99588,666.425333,<ISCED level 5>,<ISCED level 3>,0
1955,14789,Male,26-100 books,10.0,9.0,0.0,0.0,0.0,240.0,420.0,180.0,465.65664,417.31396,407.62776,585.418333,<ISCED level 2>,Mother - Highest Schooling,<ISCED level 3A>
195689,20872,Male,201-500 books,15.0,0.0,0.0,1.0,1.0,231.0,154.0,231.0,653.22482,644.10400,640.46994,863.674527,<ISCED level 4>,<ISCED level 3>,0
172777,9845,Male,101-200 books,2.0,0.0,0.0,0.0,1.0,150.0,150.0,200.0,365.17372,370.80114,443.99478,515.047787,<ISCED level 4>,<ISCED level 3>,0

In [48]:
mother_edu = mother_edu[(mother_edu['Education - Mother'] != '0')] 
mother_edu = mother_edu[(mother_edu['Education - Mother'] != 'No')]

In [49]:
mother_edu.sample(70)

,Student ID,Gender,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Completed_edu - Mother,Education - Mother
172195,20134,Male,11-25 books,4.0,1.0,0.0,0.0,0.0,325.0,325.0,325.0,326.61630,388.20336,380.02612,473.820693,<ISCED level 4>,<ISCED level 3>,<ISCED level 3>
9113,8694,Male,101-200 books,3.0,2.0,0.0,8.0,0.0,15.0,0.0,0.0,384.10188,380.34428,431.87244,526.806827,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
45665,4651,Female,101-200 books,17.0,7.0,0.0,0.0,3.0,520.0,260.0,260.0,519.32544,541.40570,551.32416,710.460247,<ISCED level 6>,<ISCED level 6>,<ISCED level 6>
4844,16070,Male,11-25 books,2.0,0.0,0.0,0.0,0.0,180.0,180.0,120.0,491.82894,485.47930,502.55500,657.230727,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 3A>
111685,5071,Male,26-100 books,5.0,0.0,1.0,0.0,0.0,210.0,210.0,300.0,562.47860,604.40774,612.58860,780.651180,<ISCED level 5>,<ISCED level 4>,<ISCED level 4>
14880,5783,Female,11-25 books,2.0,2.0,0.0,0.0,2.0,180.0,240.0,120.0,363.07056,366.73692,369.20926,487.362433,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
8258,19102,Female,101-200 books,4.0,1.0,6.0,6.0,0.0,180.0,135.0,0.0,487.23320,508.75954,511.87990,665.035280,<ISCED level 4>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
861,14332,Female,26-100 books,10.0,0.0,0.0,0.0,0.0,300.0,300.0,300.0,651.51114,640.29732,649.79486,864.371487,<ISCED level 2>,Mother - Highest Schooling,<ISCED level 3A>
194508,31064,Female,201-500 books,20.0,6.0,2.0,0.0,1.0,240.0,300.0,60.0,522.75276,520.27706,528.38494,698.055840,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
91758,20337,Male,26-100 books,1.0,1.0,5.0,0.0,1.0,240.0,180.0,180.0,460.43778,473.45012,446.51248,613.612720,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>
58281,15362,Male,201-500 books,6.0,0.0,0.0,0.0,0.0,300.0,300.0,300.0,645.59122,665.27538,595.24432,850.567380,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
104568,20813,Male,0-10 books,10.0,0.0,0.0,0.0,0.0,200.0,200.0,300.0,582.10780,508.73572,522.41702,731.789447,<ISCED level 5>,<ISCED level 4>,<ISCED level 4>
176148,10444,Male,101-200 books,5.0,1.0,0.0,0.0,2.0,165.0,275.0,165.0,589.50770,597.27044,624.71096,800.332267,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
180561,4949,Female,101-200 books,5.0,0.0,0.0,0.0,0.0,225.0,225.0,180.0,622.37888,634.02230,628.25440,835.678153,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
60176,7485,Female,0-10 books,1.0,1.0,0.0,0.0,0.0,240.0,240.0,240.0,469.78500,466.66114,423.85308,610.028073,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
211594,1517,Male,101-200 books,2.0,0.0,0.0,0.0,2.0,240.0,240.0,180.0,552.81976,568.64100,641.49570,771.925407,<ISCED level 6>,<ISCED level 3>,<ISCED level 3>
8782,18018,Male,11-25 books,16.0,16.0,0.0,0.0,0.0,240.0,240.0,120.0,580.31624,549.39434,532.86088,747.629233,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 2>
78152,18847,Male,11-25 books,2.0,0.0,0.0,0.0,0.0,300.0,300.0,300.0,567.07430,503.60324,561.48826,733.080033,<ISCED level 4>,<ISCED level 5>,<ISCED level 5>
185538,1977,Female,11-25 books,1.0,0.0,0.0,0.0,0.0,270.0,315.0,405.0,495.10048,554.75014,529.97016,691.640420,<ISCED level 6>,<ISCED level 3>,<ISCED level 3>
1637,28889,Male,26-100 books,6.0,0.0,0.0,0.0,0.0,275.0,220.0,110.0,595.58340,524.69442,538.64230,751.501173,<ISCED level 2>,Mother - Highest Schooling,<ISCED level 2>
97504,24047,Female,0-10 books,21.0,0.0,0.0,0.0,0.0,240.0,240.0,120.0,500.94252,543.07378,503.48750,682.815440,<ISCED level 3>,<ISCED level 4>,<ISCED level 4>
101376,11288,Female,26-100 books,18.0,1.0,0.0,0.0,2.0,300.0,300.0,225.0,513.01606,500.02216,541.43974,689.164673,<ISCED level 4>,<ISCED level 4>,<ISCED level 4>
70314,3451,Male,26-100 books,5.0,5.0,3.0,3.0,2.0,250.0,250.0,250.0,401.62798,371.20210,372.00674,515.488267,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>
19997,1165,Female,101-200 books,2.0,2.0,3.0,6.0,0.0,225.0,270.0,225.0,546.82194,542.27946,515.70310,717.208813,<ISCED level 6>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
57503,20559,Male,26-100 books,3.0,0.0,0.0,0.0,0.0,240.0,240.0,180.0,630.55772,616.27652,595.05782,824.149927,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
62087,4689,Male,More than 500 books,1.0,0.0,0.0,0.0,0.0,180.0,135.0,90.0,488.79110,540.01158,491.27190,669.621893,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
102204,5922,Male,101-200 books,3.0,1.0,0.0,0.0,0.0,300.0,300.0,250.0,621.98940,594.06266,557.66504,798.568833,<ISCED level 4>,<ISCED level 4>,<ISCED level 4>
90695,1981,Female,26-100 books,10.0,1.0,1.0,0.0,0.0,120.0,120.0,360.0,500.63094,539.26108,567.26966,702.597540,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>
23299,1628,Female,11-25 books,3.0,3.0,0.0,0.0,2.0,180.0,180.0,180.0,516.67706,509.15674,514.77060,685.760487,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
185484,3875,Female,More than 500 books,9.0,0.0,0.0,0.0,0.0,160.0,240.0,80.0,607.34540,632.27482,583.21522,810.060280,<ISCED level 6>,<ISCED level 3>,<ISCED level 3>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10114,16585,Male,26-100 books,4.0,2.0,3.0,0.0,0.0,180.0,240.0,180.0,620.58732,536.72358,643.17418,807.024133,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
64802,7033,Male,101-200 books,1.0,0.0,0.0,0.0,1.0,150.0,150.0,150.0,538.95468,526.61908,589.27642,731.268287,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
180592,6177,Male,201-500 books,0.0,0.0,0.0,1.0,0.0,180.0,135.0,90.0,608.82536,637.20732,662.29018,839.049407,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
20928,9799,Male,0-10 books,2.0,0.0,0.0,0.0,0.0,270.0,270.0,90.0,392.12494,310.25430,368.18350,487.562560,<ISCED level 6>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
17465,312,Female,More than 500 books,4.0,1.0,1.0,0.0,0.0,140.0,105.0,70.0,546.43246,564.04356,526.79972,727.902733,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
209701,12061,Male,101-200 books,11.0,6.0,6.0,6.0,0.0,200.0,200.0,150.0,536.46208,519.16102,527.26594,706.450373,<ISCED level 6>,<ISCED level 3>,<ISCED level 3>
84315,17451,Male,11-25 books,12.0,0.0,0.0,0.0,0.0,300.0,240.0,120.0,538.87676,455.08558,517.56808,683.469060,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
174135,16462,Male,More than 500 books,0.0,0.0,0.0,0.0,0.0,300.0,300.0,0.0,485.83112,466.63358,479.98880,639.428207,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
172180,21168,Male,26-100 books,2.0,1.0,0.0,0.0,0.0,375.0,375.0,375.0,571.28056,508.17434,507.87020,719.535220,<ISCED level 4>,<ISCED level 3>,<ISCED level 3>
21238,3841,Female,More than 500 books,1.0,0.0,0.0,1.0,0.0,135.0,135.0,270.0,603.68438,637.99382,634.68854,826.683707,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
179661,7333,Male,101-200 books,1.0,1.0,0.0,1.0,1.0,200.0,250.0,100.0,378.49352,338.80352,373.31222,489.700927,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
19599,9704,Male,101-200 books,4.0,1.0,0.0,0.0,1.0,400.0,400.0,400.0,523.84330,508.65550,498.35882,684.900307,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
3257,17558,Male,26-100 books,3.0,0.0,0.0,0.0,0.0,300.0,360.0,120.0,419.54354,384.27384,501.62254,574.994487,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 3A>
24102,24091,Female,More than 500 books,7.0,0.0,0.0,0.0,0.0,220.0,165.0,165.0,625.96200,523.37488,569.13466,781.477847,<ISCED level 1>,<ISCED level 6>,<ISCED level 6>
167001,16420,Female,0-10 books,6.0,0.0,0.0,0.0,0.0,200.0,250.0,100.0,478.04174,662.45858,528.94442,715.828827,<ISCED level 2>,<ISCED level 3>,<ISCED level 3>
142246,25468,Female,26-100 books,15.0,2.0,2.0,0.0,0.0,165.0,220.0,110.0,436.60226,504.62916,442.31630,606.716660,<ISCED level 2>,<ISCED level 2>,<ISCED level 2>
134480,14305,Male,More than 500 books,2.0,1.0,2.0,2.0,0.0,220.0,220.0,165.0,539.57782,546.50732,594.87130,740.178087,<ISCED level 5>,<ISCED level 1>,<ISCED level 1>
176622,8804,Male,11-25 books,4.0,0.0,0.0,0.0,0.0,200.0,150.0,600.0,585.69090,496.46596,575.75532,747.867693,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
23017,3045,Female,More than 500 books,15.0,0.0,0.0,0.0,0.0,220.0,220.0,440.0,723.71864,746.73488,737.72846,977.300207,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
15091,27,Female,101-200 books,4.0,1.0,0.0,0.0,1.0,140.0,210.0,140.0,493.93208,503.83486,507.40394,666.367653,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
144493,24770,Female,26-100 books,10.0,10.0,0.0,0.0,0.0,300.0,360.0,120.0,446.33900,465.31084,466.18800,608.058947,<ISCED level 3>,<ISCED level 2>,<ISCED level 2>
6960,13997,Female,26-100 books,6.0,4.0,0.0,0.0,4.0,165.0,165.0,110.0,383.32296,468.32920,438.49312,557.822747,<ISCED level 4>,Mother - Highest Schooling,<ISCED level 2>
11858,19595,Female,101-200 books,7.0,7.0,0.0,5.0,0.0,240.0,240.0,240.0,647.92802,710.35550,604.10296,870.104833,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
21972,10263,Female,26-100 books,1.0,0.0,2.0,2.0,0.0,270.0,270.0,360.0,361.74640,397.07956,344.96458,488.512313,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
51423,9172,Female,101-200 books,4.0,0.0,0.0,0.0,1.0,150.0,150.0,300.0,650.81010,668.09818,640.19022,869.969533,<ISCED level 3>,<ISCED level 5>,<ISCED level 5>
165826,24883,Female,201-500 books,2.0,1.0,2.0,0.0,5.0,150.0,250.0,100.0,493.93210,567.45910,563.63298,706.318760,<ISCED level 2>,<ISCED level 3>,<ISCED level 3>
8246,16925,Male,26-100 books,10.0,2.0,4.0,0.0,0.0,240.0,240.0,240.0,419.77724,449.47196,398.30286,562.443100,<ISCED level 4>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
22998,187,Male,26-100 books,2.0,2.0,0.0,0.0,10.0,240.0,240.0,240.0,403.96480,382.50952,421.24208,537.227067,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
15269,4559,Female,101-200 books,6.0,0.0,0.0,0.0,0.0,180.0,240.0,120.0,610.38322,652.21200,636.36704,836.448493,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
21947,8525,Male,0-10 books,7.0,7.0,4.0,0.0,0.0,220.0,220.0,275.0,437.45912,494.78186,456.67660,608.792233,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>

In [50]:
mother_edu = mother_edu[(mother_edu['Completed_edu - Mother'] != 'Mother - Highest Schooling')]

In [51]:
mother_edu['Education - Mother'].value_counts()

<ISCED level 3>    19231
<ISCED level 5>    14533
<ISCED level 4>     5094
<ISCED level 2>     3605
<ISCED level 6>     2611
<ISCED level 1>      532
<ISCED level 0>      152
Name: Education - Mother, dtype: int64

In [52]:
mother_edu.drop(columns=['Completed_edu - Mother'], axis=1, inplace=True)

In [53]:
mother_edu.sample(10)

,Student ID,Gender,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother
172201,20555,Female,101-200 books,15.0,2.0,0.0,0.0,0.0,375.0,300.0,375.0,609.13696,655.23038,546.56844,806.690913,<ISCED level 4>,<ISCED level 3>
196447,18619,Male,101-200 books,10.0,0.0,7.0,0.0,0.0,240.0,240.0,180.0,440.96432,423.32854,470.85042,592.035867,<ISCED level 4>,<ISCED level 3>
68874,2823,Female,11-25 books,5.0,5.0,3.0,2.0,2.0,265.0,212.0,265.0,382.15454,491.84076,414.24842,556.799420,<ISCED level 6>,<ISCED level 5>
110542,8527,Female,26-100 books,10.0,5.0,7.0,2.0,10.0,200.0,200.0,250.0,524.77802,556.89478,553.65534,720.035387,<ISCED level 5>,<ISCED level 4>
101135,20265,Male,26-100 books,1.0,0.0,0.0,0.0,0.0,250.0,250.0,100.0,529.21796,469.60078,510.38792,679.474873,<ISCED level 4>,<ISCED level 4>
171354,30893,Male,201-500 books,2.0,0.0,0.0,0.0,0.0,100.0,150.0,0.0,568.78796,522.28856,565.68444,741.849640,<ISCED level 4>,<ISCED level 3>
168533,13055,Female,More than 500 books,5.0,2.0,0.0,0.0,2.0,150.0,200.0,100.0,482.55962,542.35890,566.61692,691.365020,<ISCED level 3>,<ISCED level 3>
172258,19745,Male,11-25 books,2.0,2.0,0.0,0.0,0.0,195.0,325.0,260.0,529.60740,552.12090,541.16002,717.498573,<ISCED level 4>,<ISCED level 3>
55825,17802,Male,201-500 books,0.0,0.0,1.0,0.0,0.0,300.0,200.0,100.0,614.27792,568.56080,597.48228,798.199640,<ISCED level 5>,<ISCED level 5>
93311,15497,Male,201-500 books,7.0,2.0,0.0,0.0,2.0,150.0,250.0,100.0,479.13226,437.52298,535.47184,643.753113,<ISCED level 6>,<ISCED level 5>

In [75]:
mother_edu['Student ID'].duplicated().sum()

22238

In [55]:
# mother_edu.replace(["NaN"], np.nan, inplace = True)
# mother_edu.dropna(inplace = True)

In [77]:
mother_edu['Education - Mother'] = mother_edu['Education - Mother'].astype('category')

mother_edu['Education - Mother'] = mother_edu['Education - Mother'].cat.set_categories(['<ISCED level 0>', 
                                                                                        '<ISCED level 1>', 
                                                                                        '<ISCED level 2>', 
                                                                                        '<ISCED level 3>',
                                                                                        '<ISCED level 4>', 
                                                                                        '<ISCED level 5>', 
                                                                                        '<ISCED level 6>'], ordered=True)
mother_edu.sort_values(['Education - Mother'], inplace=True)
mother_edu_clean = mother_edu.drop_duplicates(subset='Student ID', keep='last')

In [78]:
mother_edu['Student ID'].duplicated().sum()

22238

In [58]:
mother_edu.shape

(45758, 17)

In [59]:
mother_edu_clean.shape

(23520, 17)

In [60]:
mother_edu_clean.duplicated().sum()

0

In [61]:
mother_edu_clean.sample(10)

,Student ID,Gender,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother
65070,12115,Male,0-10 books,1.0,1.0,0.0,0.0,0.0,120.0,120.0,150.0,393.21546,373.92872,353.07720,504.478947,<ISCED level 5>,<ISCED level 5>
61797,24192,Female,0-10 books,2.0,0.0,0.0,0.0,0.0,240.0,240.0,240.0,526.25800,485.00972,556.07982,697.868513,<ISCED level 5>,<ISCED level 5>
79846,10937,Male,101-200 books,9.0,0.0,0.0,0.0,0.0,300.0,300.0,300.0,587.32670,578.82570,588.71688,780.731993,<ISCED level 5>,<ISCED level 5>
45279,6206,Female,201-500 books,1.0,1.0,2.0,2.0,0.0,250.0,150.0,250.0,323.50054,431.07606,358.95188,479.009673,<ISCED level 6>,<ISCED level 6>
104101,24966,Female,101-200 books,4.0,0.0,0.0,0.0,0.0,165.0,220.0,330.0,567.07430,567.45910,496.40060,732.669433,<ISCED level 5>,<ISCED level 4>
46814,2350,Male,26-100 books,12.0,8.0,4.0,6.0,12.0,240.0,240.0,180.0,395.31860,374.57028,394.19990,519.802460,<ISCED level 6>,<ISCED level 6>
82751,9239,Female,101-200 books,4.0,2.0,0.0,0.0,1.0,300.0,300.0,300.0,628.45460,610.03412,627.69488,831.546067,<ISCED level 5>,<ISCED level 5>
166578,14448,Female,26-100 books,19.0,19.0,0.0,0.0,2.0,165.0,220.0,110.0,380.67458,440.44892,402.77884,534.858973,<ISCED level 2>,<ISCED level 3>
100805,30765,Male,26-100 books,7.0,5.0,2.0,0.0,5.0,200.0,200.0,100.0,446.49478,449.31158,486.70272,609.667953,<ISCED level 4>,<ISCED level 4>
63463,4231,Male,More than 500 books,2.0,0.0,0.0,0.0,0.0,150.0,200.0,150.0,588.33932,562.22546,554.77434,764.559480,<ISCED level 5>,<ISCED level 5>

In [62]:
pisa_clean = mother_edu_clean.copy()

In [63]:
pisa_clean.shape

(23520, 17)

In [64]:
pisa_clean = mother_edu.copy()

In [65]:
pisa_clean.shape

(45758, 17)

### 4. Missing values in relevant columns 
('Mother Highest Schooling', 'Father Highest Schooling', 'How many books at home', 'Out-of-School Study Time - Homework', 'Out-of-School Study Time - Guided Homework', 'Out-of-School Study Time - Personal Tutor','Out-of-School Study Time - Commercial Company', 'Out-of-School Study Time - With Parent', 'Learning time (minutes per week)- Mathematics', 'Learning time (minutes per week)  - test language', 'Learning time (minutes per week) - Science')

Due to the amount of rows in this dataframe, we can comfortably remove the rows with missing values.

In [66]:

# pisa_clean.replace(["NaN"], np.nan, inplace = True)
# pisa_clean.dropna(inplace = True)

In [67]:
# Check to see if null values correctly dropped
pisa_clean

,Student ID,Gender,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother
235181,1647,Male,0-10 books,2.0,1.0,0.0,0.0,0.0,150.0,200.0,350.0,449.53266,478.18156,474.20738,617.151420,<ISCED level 6>,<ISCED level 0>
212053,14280,Male,11-25 books,3.0,0.0,0.0,0.0,0.0,160.0,160.0,120.0,399.21326,383.87284,344.96456,509.087973,<ISCED level 1>,<ISCED level 0>
212039,18805,Female,0-10 books,0.0,0.0,0.0,0.0,0.0,150.0,150.0,150.0,438.93906,495.01800,456.39686,609.764327,<ISCED level 1>,<ISCED level 0>
212037,18913,Male,11-25 books,2.0,1.0,0.0,0.0,1.0,200.0,150.0,150.0,486.99952,524.61420,498.26558,665.626273,<ISCED level 1>,<ISCED level 0>
212019,12822,Male,11-25 books,30.0,30.0,30.0,30.0,30.0,360.0,240.0,120.0,284.08632,287.23844,312.23424,389.215107,<ISCED level 1>,<ISCED level 0>
212011,9143,Male,11-25 books,4.0,2.0,0.0,0.0,6.0,250.0,250.0,100.0,334.32778,415.54968,389.07126,491.092167,<ISCED level 1>,<ISCED level 0>
212009,10479,Male,0-10 books,2.0,0.0,0.0,0.0,0.0,200.0,200.0,600.0,376.85780,329.09998,330.04476,470.953447,<ISCED level 1>,<ISCED level 0>
211995,16142,Female,11-25 books,5.0,3.0,2.0,0.0,1.0,200.0,200.0,150.0,434.49916,365.22774,362.68184,532.302633,<ISCED level 1>,<ISCED level 0>
211994,16295,Female,0-10 books,1.0,1.0,0.0,1.0,0.0,140.0,220.0,110.0,355.74856,424.95988,393.73368,510.063560,<ISCED level 1>,<ISCED level 0>
211993,17846,Male,0-10 books,2.0,0.0,0.0,0.0,1.0,225.0,180.0,180.0,422.03614,430.94704,468.61244,581.210587,<ISCED level 1>,<ISCED level 0>
211987,17761,Male,0-10 books,1.0,1.0,1.0,0.0,1.0,300.0,300.0,150.0,319.21638,331.18504,326.12832,431.915373,<ISCED level 1>,<ISCED level 0>
211974,14327,Female,0-10 books,1.0,1.0,1.0,1.0,1.0,90.0,120.0,80.0,365.17370,386.35636,432.43196,516.378573,<ISCED level 1>,<ISCED level 0>
211972,13635,Male,0-10 books,2.0,1.0,0.0,0.0,1.0,300.0,300.0,250.0,408.48262,452.75994,384.68852,551.471233,<ISCED level 1>,<ISCED level 0>
211957,15437,Female,101-200 books,8.0,5.0,8.0,0.0,2.0,270.0,270.0,180.0,345.46660,405.97586,373.87170,490.260253,<ISCED level 1>,<ISCED level 0>
211952,15337,Male,0-10 books,2.0,0.0,0.0,0.0,0.0,118.0,177.0,118.0,482.09224,526.21812,487.72844,659.377013,<ISCED level 1>,<ISCED level 0>
211838,21333,Male,26-100 books,7.0,0.0,1.0,0.0,0.0,220.0,330.0,110.0,429.28024,310.25430,427.95600,532.256927,<ISCED level 1>,<ISCED level 0>
212089,19354,Female,0-10 books,5.0,5.0,0.0,0.0,0.0,220.0,220.0,165.0,476.56180,445.61192,529.59718,642.777567,<ISCED level 1>,<ISCED level 0>
211817,6640,Male,0-10 books,1.0,1.0,1.0,1.0,1.0,180.0,360.0,0.0,210.16514,195.81670,258.42968,291.525553,<ISCED level 0>,<ISCED level 0>
212140,22540,Female,11-25 books,2.0,1.0,0.0,0.0,0.0,250.0,200.0,150.0,410.66368,409.23252,457.88886,562.816247,<ISCED level 1>,<ISCED level 0>
212206,17718,Female,0-10 books,7.0,1.0,2.0,1.0,3.0,200.0,220.0,165.0,422.65930,408.83536,481.76056,578.638173,<ISCED level 1>,<ISCED level 0>
213611,27839,Male,26-100 books,10.0,0.0,0.0,0.0,0.0,300.0,300.0,120.0,381.60926,421.24350,468.61246,551.024827,<ISCED level 2>,<ISCED level 0>
213067,22804,Female,11-25 books,5.0,0.0,0.0,0.0,0.0,200.0,200.0,100.0,474.84810,510.18934,491.36518,650.416907,<ISCED level 2>,<ISCED level 0>
212698,24651,Female,26-100 books,7.0,2.0,0.0,0.0,0.0,110.0,220.0,110.0,360.26640,405.10208,443.90152,523.178800,<ISCED level 2>,<ISCED level 0>
212471,12825,Male,0-10 books,2.0,1.0,0.0,0.0,0.0,240.0,240.0,120.0,334.32778,351.55446,409.21298,476.474333,<ISCED level 2>,<ISCED level 0>
212468,13375,Male,26-100 books,1.0,0.0,0.0,0.0,0.0,90.0,90.0,90.0,321.55320,314.66500,307.47854,421.749980,<ISCED level 2>,<ISCED level 0>
212465,13203,Female,11-25 books,10.0,5.0,3.0,3.0,2.0,150.0,200.0,150.0,360.57798,429.72570,396.90416,515.928607,<ISCED level 2>,<ISCED level 0>
212448,13900,Male,11-25 books,3.0,2.0,2.0,0.0,0.0,150.0,150.0,150.0,405.05530,438.32492,410.42522,552.953580,<ISCED level 2>,<ISCED level 0>
212369,10904,Female,0-10 books,9.0,1.0,0.0,0.0,2.0,270.0,315.0,180.0,388.61972,454.11104,421.52180,550.957427,<ISCED level 2>,<ISCED level 0>
212367,11498,Male,26-100 books,7.0,3.0,6.0,8.0,1.0,315.0,180.0,270.0,386.28290,343.29442,389.53748,501.799233,<ISCED level 2>,<ISCED level 0>
212294,10648,Female,101-200 books,5.0,2.0,2.0,2.0,0.0,240.0,180.0,240.0,380.12930,413.91896,334.14772,502.775093,<ISCED level 1>,<ISCED level 0>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42790,14415,Male,26-100 books,10.0,6.0,0.0,0.0,0.0,350.0,350.0,350.0,627.51988,577.54258,626.38942,819.657253,<ISCED level 6>,<ISCED level 6>
42792,14413,Female,26-100 books,12.0,5.0,0.0,0.0,5.0,350.0,350.0,350.0,583.27620,581.91552,582.37596,776.947960,<ISCED level 6>,<ISCED level 6>
42793,14401,Male,26-100 books,5.0,0.0,0.0,0.0,0.0,360.0,360.0,360.0,536.22836,503.12210,522.41700,699.331940,<ISCED level 6>,<ISCED level 6>
42795,14395,Female,0-10 books,1.0,1.0,0.0,0.0,1.0,750.0,750.0,750.0,486.29850,465.54912,497.33308,645.159733,<ISCED level 6>,<ISCED level 6>
42796,14277,Female,26-100 books,4.0,0.0,0.0,0.0,0.0,720.0,180.0,720.0,508.96558,499.46614,429.54122,648.979507,<ISCED level 6>,<ISCED level 6>
42800,14165,Male,0-10 books,5.0,1.0,1.0,0.0,0.0,225.0,300.0,300.0,488.32372,454.68460,483.62552,638.319187,<ISCED level 6>,<ISCED level 6>
42804,14999,Female,101-200 books,8.0,0.0,0.0,0.0,0.0,400.0,400.0,400.0,633.36190,663.80892,676.37076,868.967827,<ISCED level 6>,<ISCED level 6>
42805,14957,Male,101-200 books,3.0,3.0,0.0,0.0,4.0,60.0,60.0,60.0,403.03006,376.25438,399.42186,527.245453,<ISCED level 6>,<ISCED level 6>
42777,15714,Male,26-100 books,10.0,1.0,5.0,4.0,0.0,375.0,375.0,375.0,661.94890,589.01042,640.28346,851.063893,<ISCED level 6>,<ISCED level 6>
42776,15718,Female,101-200 books,10.0,5.0,2.0,0.0,7.0,375.0,0.0,0.0,596.44024,666.50958,614.64006,824.676707,<ISCED level 6>,<ISCED level 6>
42775,15785,Female,More than 500 books,14.0,4.0,0.0,0.0,6.0,375.0,375.0,375.0,541.99252,606.14200,560.64900,750.258680,<ISCED level 6>,<ISCED level 6>
42773,15055,Female,26-100 books,2.0,2.0,1.0,1.0,2.0,375.0,375.0,375.0,336.19722,368.24610,333.77472,458.138420,<ISCED level 6>,<ISCED level 6>
42739,12665,Male,26-100 books,16.0,5.0,0.0,0.0,2.0,300.0,300.0,300.0,636.78922,606.09184,629.83962,836.503300,<ISCED level 6>,<ISCED level 6>
42740,12624,Female,0-10 books,0.0,0.0,0.0,0.0,0.0,408.0,408.0,408.0,420.01090,452.60184,424.78554,572.469727,<ISCED level 6>,<ISCED level 6>
42742,12566,Male,26-100 books,28.0,0.0,0.0,0.0,0.0,445.0,445.0,445.0,679.86446,625.17814,685.69564,890.200900,<ISCED level 6>,<ISCED level 6>
42744,12504,Male,11-25 books,1.0,0.0,0.0,0.0,0.0,300.0,300.0,300.0,557.10390,472.48778,536.49758,707.731053,<ISCED level 6>,<ISCED level 6>
42745,12496,Female,More than 500 books,4.0,1.0,0.0,0.0,0.0,300.0,300.0,300.0,556.16918,540.29368,505.16598,719.266007,<ISCED level 6>,<ISCED level 6>
42749,20493,Male,101-200 books,2.0,0.0,0.0,0.0,0.0,400.0,400.0,400.0,672.07510,651.72252,704.62516,900.165960,<ISCED level 6>,<ISCED level 6>
42750,14156,Female,26-100 books,8.0,3.0,0.0,0.0,3.0,225.0,225.0,225.0,447.42950,451.96640,498.35882,615.061407,<ISCED level 6>,<ISCED level 6>
42809,14580,Male,101-200 books,30.0,1.0,2.0,0.0,0.0,375.0,375.0,375.0,652.05640,580.99094,607.18016,830.761300,<ISCED level 6>,<ISCED level 6>
42752,15082,Male,26-100 books,10.0,0.0,0.0,0.0,1.0,375.0,375.0,375.0,557.96074,546.98850,544.70346,735.871147,<ISCED level 6>,<ISCED level 6>
42756,15237,Male,26-100 books,3.0,1.0,0.0,0.0,4.0,300.0,300.0,300.0,567.38590,521.80738,578.08654,744.888573,<ISCED level 6>,<ISCED level 6>
42762,15456,Female,26-100 books,7.0,7.0,3.0,0.0,7.0,180.0,120.0,120.0,385.19240,412.48918,435.41588,539.429953,<ISCED level 6>,<ISCED level 6>
42764,15537,Male,201-500 books,0.0,0.0,0.0,0.0,0.0,375.0,375.0,375.0,572.52686,528.22296,549.92542,741.067367,<ISCED level 6>,<ISCED level 6>
42766,15544,Male,101-200 books,8.0,1.0,0.0,0.0,1.0,375.0,375.0,375.0,609.13696,608.49768,607.08690,811.286167,<ISCED level 6>,<ISCED level 6>
42767,16106,Male,101-200 books,4.0,3.0,4.0,0.0,4.0,300.0,400.0,250.0,545.03038,567.83906,579.57850,745.826107,<ISCED level 6>,<ISCED level 6>
42769,15992,Female,26-100 books,2.0,2.0,0.0,0.0,1.0,0.0,420.0,385.0,384.25768,432.50580,403.71128,534.910813,<ISCED level 6>,<ISCED level 6>
42771,15940,Male,11-25 books,2.0,1.0,2.0,0.0,4.0,240.0,240.0,240.0,431.92866,389.64686,416.20664,556.570273,<ISCED level 6>,<ISCED level 6>
42754,15089,Female,More than 500 books,10.0,1.0,0.0,0.0,3.0,300.0,300.0,300.0,571.35848,527.66416,552.16334,740.848153,<ISCED level 6>,<ISCED level 6>
23582,23884,Male,More than 500 books,6.0,1.0,1.0,1.0,0.0,240.0,240.0,240.0,402.09534,371.60310,413.87542,529.889733,<ISCED level 0>,<ISCED level 6>

In [68]:
# Confirm with smaller shape of dataframe
pisa_clean.shape

(45758, 17)

### 5. Create a total for Out-of-School Study Time and Learning time (minutes per week)

In [69]:
# Create total of Out-of-School Study Time
pisa_clean['Out-of-School Study Time - Total'] = pisa_clean['Out-of-School Study Time - Homework'] + pisa_clean['Out-of-School Study Time - Guided Homework'] + pisa_clean['Out-of-School Study Time - Personal Tutor'] + pisa_clean['Out-of-School Study Time - Commercial Company'] + pisa_clean['Out-of-School Study Time - With Parent']

# Create total of Learning time (minutes per week)
pisa_clean['Learning time (minutes per week) - Total'] = pisa_clean['Learning time (minutes per week)- <Mathematics>'] + pisa_clean['Learning time (minutes per week)  - <test language>'] + pisa_clean['Learning time (minutes per week) - <Science>']

In [70]:
list(pisa_clean)

['Student ID',
 'Gender',
 'How many books at home',
 'Out-of-School Study Time - Homework',
 'Out-of-School Study Time - Guided Homework',
 'Out-of-School Study Time - Personal Tutor',
 'Out-of-School Study Time - Commercial Company',
 'Out-of-School Study Time - With Parent',
 'Learning time (minutes per week)- <Mathematics>',
 'Learning time (minutes per week)  - <test language>',
 'Learning time (minutes per week) - <Science>',
 'Average Math Score',
 'Average Reading Score',
 'Average Science Score',
 'Average Total Score',
 'Education - Father',
 'Education - Mother',
 'Out-of-School Study Time - Total',
 'Learning time (minutes per week) - Total']

<a id='assessing2'></a>
### Final Assessment

In this section, we will do the preliminary visual and programmatic assessment of the pisa datasets to determine whether or not it holds any major quality or tidiness issues.

In [71]:
pisa_clean

,Student ID,Gender,How many books at home,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning time (minutes per week)- <Mathematics>,Learning time (minutes per week) - <test language>,Learning time (minutes per week) - <Science>,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother,Out-of-School Study Time - Total,Learning time (minutes per week) - Total
235181,1647,Male,0-10 books,2.0,1.0,0.0,0.0,0.0,150.0,200.0,350.0,449.53266,478.18156,474.20738,617.151420,<ISCED level 6>,<ISCED level 0>,3.0,700.0
212053,14280,Male,11-25 books,3.0,0.0,0.0,0.0,0.0,160.0,160.0,120.0,399.21326,383.87284,344.96456,509.087973,<ISCED level 1>,<ISCED level 0>,3.0,440.0
212039,18805,Female,0-10 books,0.0,0.0,0.0,0.0,0.0,150.0,150.0,150.0,438.93906,495.01800,456.39686,609.764327,<ISCED level 1>,<ISCED level 0>,0.0,450.0
212037,18913,Male,11-25 books,2.0,1.0,0.0,0.0,1.0,200.0,150.0,150.0,486.99952,524.61420,498.26558,665.626273,<ISCED level 1>,<ISCED level 0>,4.0,500.0
212019,12822,Male,11-25 books,30.0,30.0,30.0,30.0,30.0,360.0,240.0,120.0,284.08632,287.23844,312.23424,389.215107,<ISCED level 1>,<ISCED level 0>,150.0,720.0
212011,9143,Male,11-25 books,4.0,2.0,0.0,0.0,6.0,250.0,250.0,100.0,334.32778,415.54968,389.07126,491.092167,<ISCED level 1>,<ISCED level 0>,12.0,600.0
212009,10479,Male,0-10 books,2.0,0.0,0.0,0.0,0.0,200.0,200.0,600.0,376.85780,329.09998,330.04476,470.953447,<ISCED level 1>,<ISCED level 0>,2.0,1000.0
211995,16142,Female,11-25 books,5.0,3.0,2.0,0.0,1.0,200.0,200.0,150.0,434.49916,365.22774,362.68184,532.302633,<ISCED level 1>,<ISCED level 0>,11.0,550.0
211994,16295,Female,0-10 books,1.0,1.0,0.0,1.0,0.0,140.0,220.0,110.0,355.74856,424.95988,393.73368,510.063560,<ISCED level 1>,<ISCED level 0>,3.0,470.0
211993,17846,Male,0-10 books,2.0,0.0,0.0,0.0,1.0,225.0,180.0,180.0,422.03614,430.94704,468.61244,581.210587,<ISCED level 1>,<ISCED level 0>,3.0,585.0
211987,17761,Male,0-10 books,1.0,1.0,1.0,0.0,1.0,300.0,300.0,150.0,319.21638,331.18504,326.12832,431.915373,<ISCED level 1>,<ISCED level 0>,4.0,750.0
211974,14327,Female,0-10 books,1.0,1.0,1.0,1.0,1.0,90.0,120.0,80.0,365.17370,386.35636,432.43196,516.378573,<ISCED level 1>,<ISCED level 0>,5.0,290.0
211972,13635,Male,0-10 books,2.0,1.0,0.0,0.0,1.0,300.0,300.0,250.0,408.48262,452.75994,384.68852,551.471233,<ISCED level 1>,<ISCED level 0>,4.0,850.0
211957,15437,Female,101-200 books,8.0,5.0,8.0,0.0,2.0,270.0,270.0,180.0,345.46660,405.97586,373.87170,490.260253,<ISCED level 1>,<ISCED level 0>,23.0,720.0
211952,15337,Male,0-10 books,2.0,0.0,0.0,0.0,0.0,118.0,177.0,118.0,482.09224,526.21812,487.72844,659.377013,<ISCED level 1>,<ISCED level 0>,2.0,413.0
211838,21333,Male,26-100 books,7.0,0.0,1.0,0.0,0.0,220.0,330.0,110.0,429.28024,310.25430,427.95600,532.256927,<ISCED level 1>,<ISCED level 0>,8.0,660.0
212089,19354,Female,0-10 books,5.0,5.0,0.0,0.0,0.0,220.0,220.0,165.0,476.56180,445.61192,529.59718,642.777567,<ISCED level 1>,<ISCED level 0>,10.0,605.0
211817,6640,Male,0-10 books,1.0,1.0,1.0,1.0,1.0,180.0,360.0,0.0,210.16514,195.81670,258.42968,291.525553,<ISCED level 0>,<ISCED level 0>,5.0,540.0
212140,22540,Female,11-25 books,2.0,1.0,0.0,0.0,0.0,250.0,200.0,150.0,410.66368,409.23252,457.88886,562.816247,<ISCED level 1>,<ISCED level 0>,3.0,600.0
212206,17718,Female,0-10 books,7.0,1.0,2.0,1.0,3.0,200.0,220.0,165.0,422.65930,408.83536,481.76056,578.638173,<ISCED level 1>,<ISCED level 0>,14.0,585.0
213611,27839,Male,26-100 books,10.0,0.0,0.0,0.0,0.0,300.0,300.0,120.0,381.60926,421.24350,468.61246,551.024827,<ISCED level 2>,<ISCED level 0>,10.0,720.0
213067,22804,Female,11-25 books,5.0,0.0,0.0,0.0,0.0,200.0,200.0,100.0,474.84810,510.18934,491.36518,650.416907,<ISCED level 2>,<ISCED level 0>,5.0,500.0
212698,24651,Female,26-100 books,7.0,2.0,0.0,0.0,0.0,110.0,220.0,110.0,360.26640,405.10208,443.90152,523.178800,<ISCED level 2>,<ISCED level 0>,9.0,440.0
212471,12825,Male,0-10 books,2.0,1.0,0.0,0.0,0.0,240.0,240.0,120.0,334.32778,351.55446,409.21298,476.474333,<ISCED level 2>,<ISCED level 0>,3.0,600.0
212468,13375,Male,26-100 books,1.0,0.0,0.0,0.0,0.0,90.0,90.0,90.0,321.55320,314.66500,307.47854,421.749980,<ISCED level 2>,<ISCED level 0>,1.0,270.0
212465,13203,Female,11-25 books,10.0,5.0,3.0,3.0,2.0,150.0,200.0,150.0,360.57798,429.72570,396.90416,515.928607,<ISCED level 2>,<ISCED level 0>,23.0,500.0
212448,13900,Male,11-25 books,3.0,2.0,2.0,0.0,0.0,150.0,150.0,150.0,405.05530,438.32492,410.42522,552.953580,<ISCED level 2>,<ISCED level 0>,7.0,450.0
212369,10904,Female,0-10 books,9.0,1.0,0.0,0.0,2.0,270.0,315.0,180.0,388.61972,454.11104,421.52180,550.957427,<ISCED level 2>,<ISCED level 0>,12.0,765.0
212367,11498,Male,26-100 books,7.0,3.0,6.0,8.0,1.0,315.0,180.0,270.0,386.28290,343.29442,389.53748,501.799233,<ISCED level 2>,<ISCED level 0>,25.0,765.0
212294,10648,Female,101-200 books,5.0,2.0,2.0,2.0,0.0,240.0,180.0,240.0,380.12930,413.91896,334.14772,502.775093,<ISCED level 1>,<ISCED level 0>,11.0,660.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42790,14415,Male,26-100 books,10.0,6.0,0.0,0.0,0.0,350.0,350.0,350.0,627.51988,577.54258,626.38942,819.657253,<ISCED level 6>,<ISCED level 6>,16.0,1050.0
42792,14413,Female,26-100 books,12.0,5.0,0.0,0.0,5.0,350.0,350.0,350.0,583.27620,581.91552,582.37596,776.947960,<ISCED level 6>,<ISCED level 6>,22.0,1050.0
42793,14401,Male,26-100 books,5.0,0.0,0.0,0.0,0.0,360.0,360.0,360.0,536.22836,503.12210,522.41700,699.331940,<ISCED level 6>,<ISCED level 6>,5.0,1080.0
42795,14395,Female,0-10 books,1.0,1.0,0.0,0.0,1.0,750.0,750.0,750.0,486.29850,465.54912,497.33308,645.159733,<ISCED level 6>,<ISCED level 6>,3.0,2250.0
42796,14277,Female,26-100 books,4.0,0.0,0.0,0.0,0.0,720.0,180.0,720.0,508.96558,499.46614,429.54122,648.979507,<ISCED level 6>,<ISCED level 6>,4.0,1620.0
42800,14165,Male,0-10 books,5.0,1.0,1.0,0.0,0.0,225.0,300.0,300.0,488.32372,454.68460,483.62552,638.319187,<ISCED level 6>,<ISCED level 6>,7.0,825.0
42804,14999,Female,101-200 books,8.0,0.0,0.0,0.0,0.0,400.0,400.0,400.0,633.36190,663.80892,676.37076,868.967827,<ISCED level 6>,<ISCED level 6>,8.0,1200.0
42805,14957,Male,101-200 books,3.0,3.0,0.0,0.0,4.0,60.0,60.0,60.0,403.03006,376.25438,399.42186,527.245453,<ISCED level 6>,<ISCED level 6>,10.0,180.0
42777,15714,Male,26-100 books,10.0,1.0,5.0,4.0,0.0,375.0,375.0,375.0,661.94890,589.01042,640.28346,851.063893,<ISCED level 6>,<ISCED level 6>,20.0,1125.0
42776,15718,Female,101-200 books,10.0,5.0,2.0,0.0,7.0,375.0,0.0,0.0,596.44024,666.50958,614.64006,824.676707,<ISCED level 6>,<ISCED level 6>,24.0,375.0
42775,15785,Female,More than 500 books,14.0,4.0,0.0,0.0,6.0,375.0,375.0,375.0,541.99252,606.14200,560.64900,750.258680,<ISCED level 6>,<ISCED level 6>,24.0,1125.0
42773,15055,Female,26-100 books,2.0,2.0,1.0,1.0,2.0,375.0,375.0,375.0,336.19722,368.24610,333.77472,458.138420,<ISCED level 6>,<ISCED level 6>,8.0,1125.0
42739,12665,Male,26-100 books,16.0,5.0,0.0,0.0,2.0,300.0,300.0,300.0,636.78922,606.09184,629.83962,836.503300,<ISCED level 6>,<ISCED level 6>,23.0,900.0
42740,12624,Female,0-10 books,0.0,0.0,0.0,0.0,0.0,408.0,408.0,408.0,420.01090,452.60184,424.78554,572.469727,<ISCED level 6>,<ISCED level 6>,0.0,1224.0
42742,12566,Male,26-100 books,28.0,0.0,0.0,0.0,0.0,445.0,445.0,445.0,679.86446,625.17814,685.69564,890.200900,<ISCED level 6>,<ISCED level 6>,28.0,1335.0
42744,12504,Male,11-25 books,1.0,0.0,0.0,0.0,0.0,300.0,300.0,300.0,557.10390,472.48778,536.49758,707.731053,<ISCED level 6>,<ISCED level 6>,1.0,900.0
42745,12496,Female,More than 500 books,4.0,1.0,0.0,0.0,0.0,300.0,300.0,300.0,556.16918,540.29368,505.16598,719.266007,<ISCED level 6>,<ISCED level 6>,5.0,900.0
42749,20493,Male,101-200 books,2.0,0.0,0.0,0.0,0.0,400.0,400.0,400.0,672.07510,651.72252,704.62516,900.165960,<ISCED level 6>,<ISCED level 6>,2.0,1200.0
42750,14156,Female,26-100 books,8.0,3.0,0.0,0.0,3.0,225.0,225.0,225.0,447.42950,451.96640,498.35882,615.061407,<ISCED level 6>,<ISCED level 6>,14.0,675.0
42809,14580,Male,101-200 books,30.0,1.0,2.0,0.0,0.0,375.0,375.0,375.0,652.05640,580.99094,607.18016,830.761300,<ISCED level 6>,<ISCED level 6>,33.0,1125.0
42752,15082,Male,26-100 books,10.0,0.0,0.0,0.0,1.0,375.0,375.0,375.0,557.96074,546.98850,544.70346,735.871147,<ISCED level 6>,<ISCED level 6>,11.0,1125.0
42756,15237,Male,26-100 books,3.0,1.0,0.0,0.0,4.0,300.0,300.0,300.0,567.38590,521.80738,578.08654,744.888573,<ISCED level 6>,<ISCED level 6>,8.0,900.0
42762,15456,Female,26-100 books,7.0,7.0,3.0,0.0,7.0,180.0,120.0,120.0,385.19240,412.48918,435.41588,539.429953,<ISCED level 6>,<ISCED level 6>,24.0,420.0
42764,15537,Male,201-500 books,0.0,0.0,0.0,0.0,0.0,375.0,375.0,375.0,572.52686,528.22296,549.92542,741.067367,<ISCED level 6>,<ISCED level 6>,0.0,1125.0
42766,15544,Male,101-200 books,8.0,1.0,0.0,0.0,1.0,375.0,375.0,375.0,609.13696,608.49768,607.08690,811.286167,<ISCED level 6>,<ISCED level 6>,10.0,1125.0
42767,16106,Male,101-200 books,4.0,3.0,4.0,0.0,4.0,300.0,400.0,250.0,545.03038,567.83906,579.57850,745.826107,<ISCED level 6>,<ISCED level 6>,15.0,950.0
42769,15992,Female,26-100 books,2.0,2.0,0.0,0.0,1.0,0.0,420.0,385.0,384.25768,432.50580,403.71128,534.910813,<ISCED level 6>,<ISCED level 6>,5.0,805.0
42771,15940,Male,11-25 books,2.0,1.0,2.0,0.0,4.0,240.0,240.0,240.0,431.92866,389.64686,416.20664,556.570273,<ISCED level 6>,<ISCED level 6>,9.0,720.0
42754,15089,Female,More than 500 books,10.0,1.0,0.0,0.0,3.0,300.0,300.0,300.0,571.35848,527.66416,552.16334,740.848153,<ISCED level 6>,<ISCED level 6>,14.0,900.0
23582,23884,Male,More than 500 books,6.0,1.0,1.0,1.0,0.0,240.0,240.0,240.0,402.09534,371.60310,413.87542,529.889733,<ISCED level 0>,<ISCED level 6>,9.0,720.0

In [72]:
pisa_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45758 entries, 235181 to 23582
Data columns (total 19 columns):
Student ID                                             45758 non-null int64
Gender                                                 45758 non-null object
How many books at home                                 45758 non-null object
Out-of-School Study Time - Homework                    45758 non-null float64
Out-of-School Study Time - Guided Homework             45758 non-null float64
Out-of-School Study Time - Personal Tutor              45758 non-null float64
Out-of-School Study Time - Commercial Company          45758 non-null float64
Out-of-School Study Time - With Parent                 45758 non-null float64
Learning time (minutes per week)- <Mathematics>        45758 non-null float64
Learning time (minutes per week)  - <test language>    45758 non-null float64
Learning time (minutes per week) - <Science>           45758 non-null float64
Average Math Score                                     45758 non-null float64
Average Reading Score                                  45758 non-null float64
Average Science Score                                  45758 non-null float64
Average Total Score                                    45758 non-null float64
Education - Father                                     45758 non-null category
Education - Mother                                     45758 non-null category
Out-of-School Study Time - Total                       45758 non-null float64
Learning time (minutes per week) - Total               45758 non-null float64
dtypes: category(2), float64(14), int64(1), object(2)
memory usage: 6.4+ MB

In [73]:
pisa_clean.shape

(45758, 19)

<a id='sav'></a>
## Store

In [74]:
# Store the clean DataFrame in a CSV file
pisa_clean.to_csv("pisa_df.csv", index=False, encoding='utf8')

<a id='conclusion'></a>
## Conclusion

<a id='references'></a>
## References