# Wrangle Pisa 2012
#### By Gabriela Sikora


### Abstract



### Table of Contents

<ul>
<li><a href="#intro">Introduction</a></li>
<li><a href="#wrangling">Data Wrangling</a></li>
    <ul>
    <li><a href="#gathering">Gathering Data</a></li>
    <li><a href="#assessing1">Initial Assessment</a></li>
        <ul>
          <li><a href="#issues1">Identified Issues</a></li>
        </ul>
    <li><a href="#cleaning1">Cleaning Data</a></li>
    <li><a href="#assessing2">Final Assessment</a></li>
    </ul>
<li><a href="#sav">Store</a></li>
<li><a href="#conclusion">Conclusion</a></li>
<li><a href="#references">References</a></li>    
</ul>

<a id='intro'></a>
## Introduction



To begin, we first need to import all the relevant libraries:
#### Import

In [83]:
# import all packages
import numpy as np
import pandas as pd

<a id='wrangling'></a>
## Data Wrangling

In this section of the report, we will load in the data, check it for cleanliness, and then trim and clean the datasets for analysis.

<a id='gathering'></a>
### Gathering Data

Unfortunately the Pisa dataset is too large to be uploaded to github, but if you would like to work with it yourself then place follow this link: https://s3.amazonaws.com/udacity-hosted-downloads/ud507/pisa2012.csv.zip

In [84]:
# Encoding help found here: https://stackoverflow.com/questions/30462807/encoding-error-in-panda-read-csv

# Load in the Pisa dataframe
pisa = pd.read_csv('pisa2012.csv', encoding="cp1252", sep=',')

# Load in the Pisa dictionary
pisa_dict = pd.read_csv('pisadict2012.csv', encoding="cp1252", sep=',')

<a id='assessing1'></a>
### First Assessment

In this section, we will do the preliminary visual and programmatic assessment of the pisa datasets to determine whether or not it holds any major quality or tidiness issues.

In [85]:
pisa

,Unnamed: 0,CNT,SUBNATIO,STRATUM,OECD,NC,SCHOOLID,STIDSTD,ST01Q01,ST02Q01,...,W_FSTR75,W_FSTR76,W_FSTR77,W_FSTR78,W_FSTR79,W_FSTR80,WVARSTRR,VAR_UNIT,SENWGT_STU,VER_STU
0,1,Albania,80000,ALB0006,Non-OECD,Albania,1,1,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
1,2,Albania,80000,ALB0006,Non-OECD,Albania,1,2,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
2,3,Albania,80000,ALB0006,Non-OECD,Albania,1,3,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
3,4,Albania,80000,ALB0006,Non-OECD,Albania,1,4,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
4,5,Albania,80000,ALB0006,Non-OECD,Albania,1,5,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
5,6,Albania,80000,ALB0006,Non-OECD,Albania,1,6,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
6,7,Albania,80000,ALB0006,Non-OECD,Albania,1,7,10,1.0,...,13.7954,13.9235,13.1249,13.1249,4.3389,13.0829,19,1,0.2098,22NOV13
7,8,Albania,80000,ALB0006,Non-OECD,Albania,1,8,10,1.0,...,14.4599,14.6374,15.8728,15.8728,5.2248,15.2579,19,1,0.2322,22NOV13
8,9,Albania,80000,ALB0006,Non-OECD,Albania,1,9,9,1.0,...,12.7307,12.7307,12.7307,12.7307,4.2436,12.7307,19,1,0.1999,22NOV13
9,10,Albania,80000,ALB0005,Non-OECD,Albania,2,10,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
10,11,Albania,80000,ALB0005,Non-OECD,Albania,2,11,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
11,12,Albania,80000,ALB0005,Non-OECD,Albania,2,12,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
12,13,Albania,80000,ALB0005,Non-OECD,Albania,2,13,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
13,14,Albania,80000,ALB0005,Non-OECD,Albania,2,14,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
14,15,Albania,80000,ALB0005,Non-OECD,Albania,2,15,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
15,16,Albania,80000,ALB0005,Non-OECD,Albania,2,16,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
16,17,Albania,80000,ALB0005,Non-OECD,Albania,2,17,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
17,18,Albania,80000,ALB0005,Non-OECD,Albania,2,18,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
18,19,Albania,80000,ALB0005,Non-OECD,Albania,2,19,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
19,20,Albania,80000,ALB0005,Non-OECD,Albania,2,20,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
20,21,Albania,80000,ALB0005,Non-OECD,Albania,2,21,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
21,22,Albania,80000,ALB0005,Non-OECD,Albania,2,22,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
22,23,Albania,80000,ALB0005,Non-OECD,Albania,2,23,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
23,24,Albania,80000,ALB0005,Non-OECD,Albania,2,24,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
24,25,Albania,80000,ALB0005,Non-OECD,Albania,2,25,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
25,26,Albania,80000,ALB0005,Non-OECD,Albania,2,26,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
26,27,Albania,80000,ALB0005,Non-OECD,Albania,2,27,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
27,28,Albania,80000,ALB0005,Non-OECD,Albania,2,28,10,1.0,...,3.5254,11.8663,3.5254,11.8663,11.8663,11.8663,74,2,0.1746,22NOV13
28,29,Albania,80000,ALB0005,Non-OECD,Albania,2,29,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
29,30,Albania,80000,ALB0005,Non-OECD,Albania,2,30,10,1.0,...,3.3844,10.1533,3.3844,10.1533,10.1533,10.1533,74,2,0.1594,22NOV13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
485460,485461,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4930,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485461,485462,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4931,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485462,485463,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4932,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485463,485464,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4933,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485464,485465,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4934,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485465,485466,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4935,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485466,485467,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4936,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485467,485468,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4937,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485468,485469,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4938,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485469,485470,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4939,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485470,485471,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4940,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485471,485472,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4941,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485472,485473,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4942,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485473,485474,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4943,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485474,485475,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4944,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485475,485476,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4945,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485476,485477,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4946,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485477,485478,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4947,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485478,485479,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4948,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485479,485480,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4949,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485480,485481,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4950,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485481,485482,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4951,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485482,485483,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4952,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485483,485484,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4953,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485484,485485,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4954,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485485,485486,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4955,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13
485486,485487,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4956,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485487,485488,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4957,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485488,485489,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4958,10,3.0,...,33.9163,96.0036,96.0036,96.0036,96.0036,33.9163,41,1,0.0688,22NOV13
485489,485490,Vietnam,7040000,VNM0317,Non-OECD,Viet Nam,162,4959,10,3.0,...,31.2413,93.7238,93.7238,93.7238,93.7238,31.2413,41,1,0.0653,22NOV13

In [86]:
pisa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 485490 entries, 0 to 485489
Columns: 636 entries, Unnamed: 0 to VER_STU
dtypes: float64(250), int64(18), object(368)
memory usage: 2.3+ GB

In [87]:
pisa.dtypes[400:]

ST23Q08        object
ST24Q01        object
ST24Q02        object
ST24Q03        object
CLCUSE1        object
CLCUSE301       int64
CLCUSE302       int64
DEFFORT         int64
QUESTID        object
BOOKID         object
EASY           object
AGE           float64
GRADE         float64
PROGN          object
ANXMAT        float64
ATSCHL        float64
ATTLNACT      float64
BELONG        float64
BFMJ2         float64
BMMJ1         float64
CLSMAN        float64
COBN_F         object
COBN_M         object
COBN_S         object
COGACT        float64
CULTDIST      float64
CULTPOS       float64
DISCLIMA      float64
ENTUSE        float64
ESCS          float64
               ...
W_FSTR55      float64
W_FSTR56      float64
W_FSTR57      float64
W_FSTR58      float64
W_FSTR59      float64
W_FSTR60      float64
W_FSTR61      float64
W_FSTR62      float64
W_FSTR63      float64
W_FSTR64      float64
W_FSTR65      float64
W_FSTR66      float64
W_FSTR67      float64
W_FSTR68      float64
W_FSTR69      float64
W_FSTR70      float64
W_FSTR71      float64
W_FSTR72      float64
W_FSTR73      float64
W_FSTR74      float64
W_FSTR75      float64
W_FSTR76      float64
W_FSTR77      float64
W_FSTR78      float64
W_FSTR79      float64
W_FSTR80      float64
WVARSTRR        int64
VAR_UNIT        int64
SENWGT_STU    float64
VER_STU        object
Length: 236, dtype: object

In [88]:
pisa_dict

     Unnamed: 0                                                  x
0           CNT                           Country code 3-character
1      SUBNATIO  Adjudicated sub-region code 7-digit code (3-di...
2       STRATUM  Stratum ID 7-character (cnt + region ID + orig...
3          OECD                                       OECD country
4            NC                       National Centre 6-digit Code
5      SCHOOLID  School ID 7-digit (region ID + stratum ID + 3-...
6       STIDSTD                                         Student ID
7       ST01Q01                                International Grade
8       ST02Q01                           National Study Programme
9       ST03Q01                                      Birth - Month
10      ST03Q02                                        Birth -Year
11      ST04Q01                                             Gender
12      ST05Q01                                   Attend <ISCED 0>
13      ST06Q01                                   Age at <ISCED 1>
14      ST07Q01                                 Repeat - <ISCED 1>
15      ST07Q02                                 Repeat - <ISCED 2>
16      ST07Q03                                 Repeat - <ISCED 3>
17      ST08Q01                          Truancy - Late for School
18      ST09Q01                    Truancy - Skip whole school day
19     ST115Q01           Truancy - Skip classes within school day
20      ST11Q01                                   At Home - Mother
21      ST11Q02                                   At Home - Father
22      ST11Q03                                 At Home - Brothers
23      ST11Q04                                  At Home - Sisters
24      ST11Q05                             At Home - Grandparents
25      ST11Q06                                   At Home - Others
26      ST13Q01                          Mother<Highest Schooling>
27      ST14Q01            Mother Qualifications - <ISCED level 6>
28      ST14Q02           Mother Qualifications - <ISCED level 5A>
29      ST14Q03           Mother Qualifications - <ISCED level 5B>
..          ...                                                ...
605    W_FSTR55           FINAL STUDENT REPLICATE BRR-FAY WEIGHT55
606    W_FSTR56           FINAL STUDENT REPLICATE BRR-FAY WEIGHT56
607    W_FSTR57           FINAL STUDENT REPLICATE BRR-FAY WEIGHT57
608    W_FSTR58           FINAL STUDENT REPLICATE BRR-FAY WEIGHT58
609    W_FSTR59           FINAL STUDENT REPLICATE BRR-FAY WEIGHT59
610    W_FSTR60           FINAL STUDENT REPLICATE BRR-FAY WEIGHT60
611    W_FSTR61           FINAL STUDENT REPLICATE BRR-FAY WEIGHT61
612    W_FSTR62           FINAL STUDENT REPLICATE BRR-FAY WEIGHT62
613    W_FSTR63           FINAL STUDENT REPLICATE BRR-FAY WEIGHT63
614    W_FSTR64           FINAL STUDENT REPLICATE BRR-FAY WEIGHT64
615    W_FSTR65           FINAL STUDENT REPLICATE BRR-FAY WEIGHT65
616    W_FSTR66           FINAL STUDENT REPLICATE BRR-FAY WEIGHT66
617    W_FSTR67           FINAL STUDENT REPLICATE BRR-FAY WEIGHT67
618    W_FSTR68           FINAL STUDENT REPLICATE BRR-FAY WEIGHT68
619    W_FSTR69           FINAL STUDENT REPLICATE BRR-FAY WEIGHT69
620    W_FSTR70           FINAL STUDENT REPLICATE BRR-FAY WEIGHT70
621    W_FSTR71           FINAL STUDENT REPLICATE BRR-FAY WEIGHT71
622    W_FSTR72           FINAL STUDENT REPLICATE BRR-FAY WEIGHT72
623    W_FSTR73           FINAL STUDENT REPLICATE BRR-FAY WEIGHT73
624    W_FSTR74           FINAL STUDENT REPLICATE BRR-FAY WEIGHT74
625    W_FSTR75           FINAL STUDENT REPLICATE BRR-FAY WEIGHT75
626    W_FSTR76           FINAL STUDENT REPLICATE BRR-FAY WEIGHT76
627    W_FSTR77           FINAL STUDENT REPLICATE BRR-FAY WEIGHT77
628    W_FSTR78           FINAL STUDENT REPLICATE BRR-FAY WEIGHT78
629    W_FSTR79           FINAL STUDENT REPLICATE BRR-FAY WEIGHT79
630    W_FSTR80           FINAL STUDENT REPLICATE BRR-FAY WEIGHT80
631    WVARSTRR           RANDOMIZED FINAL VARIANCE STRATUM (1-80)
632    VAR_UNIT                    RANDOMLY ASSIGNED VARIANCE UNIT
633  SENWGT_STU  Senate weight - sum of weight within the count...
634     VER_STU                      Date of the database creation

[635 rows x 2 columns]

In [89]:
# Check for null values in relevant columns
columns = ['STIDSTD', 'ST01Q01', 'ST04Q01', 'ST13Q01', 
            'ST17Q01', 'ST28Q01', 'ST57Q01', 'ST57Q02', 'ST57Q03', 
            'ST57Q04', 'ST57Q05', 'MMINS', 'LMINS', 'SMINS',
            'PV1MATH', 'PV2MATH', 'PV3MATH', 'PV4MATH', 'PV5MATH',  
            'PV1READ', 'PV2READ',  'PV3READ', 'PV4READ', 'PV5READ',
            'PV1SCIE', 'PV2SCIE', 'PV3SCIE', 'PV4SCIE', 'PV5SCIE']

for x in columns:
    print(x, pisa[x].isna().sum())

STIDSTD 0
ST01Q01 0
ST04Q01 0
ST13Q01 27511
ST17Q01 42229
ST28Q01 11725
ST57Q01 184123
ST57Q02 215682
ST57Q03 201677
ST57Q04 205833
ST57Q05 195988
MMINS 202187
LMINS 202624
SMINS 214576
PV1MATH 0
PV2MATH 0
PV3MATH 0
PV4MATH 0
PV5MATH 0
PV1READ 0
PV2READ 0
PV3READ 0
PV4READ 0
PV5READ 0
PV1SCIE 0
PV2SCIE 0
PV3SCIE 0
PV4SCIE 0
PV5SCIE 0

In [90]:
pisa['CNT'].value_counts()

Mexico                      33806
Italy                       31073
Spain                       25313
Canada                      21544
Brazil                      19204
Australia                   14481
United Kingdom              12659
United Arab Emirates        11500
Switzerland                 11229
Qatar                       10966
Colombia                     9073
Finland                      8829
Belgium                      8597
Denmark                      7481
Jordan                       7038
Chile                        6856
Thailand                     6606
Japan                        6351
Chinese Taipei               6046
Peru                         6035
Slovenia                     5911
Argentina                    5908
Kazakhstan                   5808
Portugal                     5722
Indonesia                    5622
Singapore                    5546
Macao-China                  5335
Czech Republic               5327
Uruguay                      5315
Bulgaria                     5282
                            ...
Ireland                      5016
Croatia                      5008
Germany                      5001
United States of America     4978
Vietnam                      4959
Turkey                       4848
Hungary                      4810
Estonia                      4779
Austria                      4755
Montenegro                   4744
Albania                      4743
Sweden                       4736
Norway                       4686
Serbia                       4684
Slovak Republic              4678
Hong Kong-China              4670
Lithuania                    4618
France                       4613
Poland                       4607
Costa Rica                   4602
Netherlands                  4460
Tunisia                      4407
Latvia                       4306
New Zealand                  4291
Iceland                      3508
Florida (USA)                1896
Perm(Russian Federation)     1761
Massachusetts (USA)          1723
Connecticut (USA)            1697
Liechtenstein                 293
Name: CNT, Length: 68, dtype: int64

In [91]:
pisa.duplicated().sum()

0

<a id='issues1'></a>
### Identified Issues
Here we can see some of the issues noticed in the dataframes. These quality issues will be cleaned in the following section.

1. Narrow down the dataframe by only looking at variables of interest since there are more variables than needed
2. Make the variable names readable since they are codes that can only be read with the dictionary
3. Create an average of all Math, Reading, and Science scores since all 5 scores for each are not necessary
4. Missing values in relevant columns ('Mother Highest Schooling', 'Father Highest Schooling', 'How many books at home', 'Out-of-School Study Time - Homework', 'Out-of-School Study Time - Guided Homework', 'Out-of-School Study Time - Personal Tutor','Out-of-School Study Time - Commercial Company', 'Out-of-School Study Time - With Parent', 'Learning time (minutes per week)- Mathematics', 'Learning time (minutes per week)  - test language', 'Learning time (minutes per week) - Science')
5. Create a total for Out-of-School Study Time and Learning time (minutes per week)
6. Single countries have various entries in the country column (Florida (USA), Massachusetts (USA), Connecticut (USA) and United States of America)

<a id='cleaning1'></a>
### First Cleaning

In [92]:
# Create a copy to preserve the original dataframe
pisa_clean = pisa.copy()

### Narrow down the dataframe by only looking at variables of interest

There are 636 columns available in the original dataframe, which is far more than what is necessary. We will rather look at just the following variables.

In [93]:
pisa_clean = pisa_clean[['CNT', 'STIDSTD', 'ST04Q01', 'ST13Q01', 'ST14Q01', 'ST14Q02', 'ST14Q03', 'ST14Q04', 
                         'ST17Q01', 'ST18Q01', 'ST18Q02', 'ST18Q03', 'ST18Q04', 
                         'ST57Q01', 'ST57Q02', 'ST57Q03', 'ST57Q04', 'ST57Q05', 'MMINS', 
                         'LMINS', 'SMINS', 'PV1MATH', 'PV2MATH', 'PV3MATH', 'PV4MATH', 
                         'PV5MATH', 'PV1READ', 'PV2READ',  'PV3READ', 'PV4READ', 'PV5READ',
                         'PV1SCIE', 'PV2SCIE', 'PV3SCIE', 'PV4SCIE', 'PV5SCIE']]

In [94]:
# Check to see if the columns are correctly reduced
list(pisa_clean)

['CNT',
 'STIDSTD',
 'ST04Q01',
 'ST13Q01',
 'ST14Q01',
 'ST14Q02',
 'ST14Q03',
 'ST14Q04',
 'ST17Q01',
 'ST18Q01',
 'ST18Q02',
 'ST18Q03',
 'ST18Q04',
 'ST57Q01',
 'ST57Q02',
 'ST57Q03',
 'ST57Q04',
 'ST57Q05',
 'MMINS',
 'LMINS',
 'SMINS',
 'PV1MATH',
 'PV2MATH',
 'PV3MATH',
 'PV4MATH',
 'PV5MATH',
 'PV1READ',
 'PV2READ',
 'PV3READ',
 'PV4READ',
 'PV5READ',
 'PV1SCIE',
 'PV2SCIE',
 'PV3SCIE',
 'PV4SCIE',
 'PV5SCIE']

### Create an average of all Math, Reading, and Science scores

For each of the Math, Reading, and Science scores, there are 5 scores provided. The variation between these scores is not needed, so rather we will look at the average for each of these major categories and remove the individual scores.

In [95]:
# Create average of Math scores
pisa_clean['Average Math Score']    = (pisa_clean['PV1MATH'] + pisa_clean['PV2MATH'] + pisa_clean['PV3MATH'] + pisa_clean['PV4MATH'] + pisa_clean['PV5MATH']) / 5

# Create average of Reading scores
pisa_clean['Average Reading Score'] = (pisa_clean['PV1READ'] + pisa_clean['PV2READ'] + pisa_clean['PV3READ'] + pisa_clean['PV4READ'] + pisa_clean['PV5READ']) / 5

# Create average of Science scores
pisa_clean['Average Science Score'] = (pisa_clean['PV1SCIE'] + pisa_clean['PV2SCIE'] + pisa_clean['PV3SCIE'] + pisa_clean['PV4SCIE'] + pisa_clean['PV5SCIE']) / 5

# Create average score
pisa_clean['Average Total Score']   = (pisa_clean['Average Math Score'] + pisa_clean['Average Reading Score'] + pisa_clean['Average Science Score']) / 3

In [96]:
# Remove the individual scores for Math, Reading, and Science
pisa_clean.drop(columns=['PV1MATH',  'PV2MATH', 'PV3MATH', 'PV4MATH', 'PV5MATH',   
                         'PV1READ', 'PV2READ',  'PV3READ', 'PV4READ',  'PV5READ',
                         'PV1SCIE',  'PV2SCIE', 'PV3SCIE',  'PV4SCIE', 'PV5SCIE'], inplace=True)

In [97]:
# Test to see accuracy of the Math score
print(pisa_clean['Average Math Score'].describe())
print('-'*22)

# Test to see accuracy of the Reading score
print(pisa_clean['Average Reading Score'].describe())
print('-'*22)

# Test to see accuracy of the Science score
print(pisa_clean['Average Science Score'].describe())

# Test to see accuracy of the Total score
print(pisa_clean['Average Total Score'].describe())

count    485490.000000
mean        469.651234
std         100.786610
min          54.767080
25%         396.019620
50%         465.734520
75%         540.123060
max         903.107960
Name: Average Math Score, dtype: float64
----------------------
count    485490.000000
mean        472.006964
std          98.863310
min           6.445400
25%         405.044200
50%         475.477980
75%         542.831195
max         849.359740
Name: Average Reading Score, dtype: float64
----------------------
count    485490.000000
mean        475.808094
std          97.998470
min          25.158540
25%         405.762800
50%         475.512860
75%         546.381920
max         857.832900
Name: Average Science Score, dtype: float64
count    485490.000000
mean        472.488764
std          96.036271
min          77.114593
25%         403.992595
50%         472.046460
75%         541.455700
max         826.592027
Name: Average Total Score, dtype: float64

In [98]:
pisa_clean.sample(10)

,CNT,STIDSTD,ST04Q01,ST13Q01,ST14Q01,ST14Q02,ST14Q03,ST14Q04,ST17Q01,ST18Q01,...,ST57Q03,ST57Q04,ST57Q05,MMINS,LMINS,SMINS,Average Math Score,Average Reading Score,Average Science Score,Average Total Score
15273,United Arab Emirates,10531,Female,<ISCED level 3A>,NaN,Yes,NaN,NaN,<ISCED level 3A>,NaN,...,2.0,0.0,1.0,240.0,320.0,200.0,488.86898,470.39440,477.75084,479.004740
313716,Macao-China,3349,Male,<ISCED level 2>,No,No,No,No,"<ISCED level 3B, 3C>",No,...,NaN,NaN,NaN,NaN,NaN,NaN,500.63094,471.76602,463.01752,478.471493
371898,New Zealand,3303,Female,"<ISCED level 3B, 3C>",No,No,No,No,"<ISCED level 3B, 3C>",No,...,0.0,0.0,0.0,120.0,160.0,120.0,515.58656,518.92676,510.38790,514.967073
55903,Brazil,638,Female,She did not complete <ISCED level 1>,No,No,No,No,<ISCED level 1>,No,...,NaN,NaN,NaN,NaN,NaN,NaN,386.51660,409.23250,384.12904,393.292713
131408,Czech Republic,3635,Male,"<ISCED level 3B, 3C>",No,No,No,No,"<ISCED level 3B, 3C>",No,...,0.0,0.0,0.0,225.0,180.0,90.0,440.10752,397.58612,439.89184,425.861827
423373,Singapore,598,Female,<ISCED level 3A>,NaN,NaN,NaN,Yes,<ISCED level 2>,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,479.98908,442.27582,424.78554,449.016813
300667,Lithuania,4482,Female,<ISCED level 3A>,No,No,Yes,No,<ISCED level 3A>,No,...,0.0,0.0,1.0,225.0,225.0,225.0,476.09440,490.09328,497.51958,487.902420
96529,Switzerland,516,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,"<ISCED level 3B, 3C>",No,...,0.0,0.0,0.0,350.0,350.0,200.0,425.69712,387.24102,408.56024,407.166127
79679,Canada,5210,Male,<ISCED level 3A>,NaN,Yes,Yes,NaN,<ISCED level 3A>,NaN,...,0.0,0.0,1.0,300.0,300.0,300.0,395.55228,461.82192,412.66318,423.345793
317843,Mexico,2141,Female,<ISCED level 1>,No,No,No,NaN,<ISCED level 1>,No,...,0.0,0.0,1.0,325.0,240.0,300.0,358.47486,418.12880,377.22862,384.610760

### Make the variable names readable

In the original dataframe, the variable names are all codes and unreadable without the dictionary. Therefore, we will change them to accurately reflect the information within the column.

In [99]:
# Rename columns
pisa_clean.rename({'CNT': 'Country',
                   'STIDSTD': 'Student ID',
                   'ST04Q01': 'Gender', 
                   'ST13Q01': 'Mother - Highest Schooling', 
                   'ST14Q01': 'Mother Qualifications - ISCED level 6',
                   'ST14Q02': 'Mother Qualifications - ISCED level 5A',
                   'ST14Q03': 'Mother Qualifications - ISCED level 5B',
                   'ST14Q04': 'Mother Qualifications - ISCED level 4',
                   'ST17Q01': 'Father - Highest Schooling',
                   'ST18Q01': 'Father Qualifications - ISCED level 6',
                   'ST18Q02': 'Father Qualifications - ISCED level 5A',
                   'ST18Q03': 'Father Qualifications - ISCED level 5B',
                   'ST18Q04': 'Father Qualifications - ISCED level 4',
                   'ST57Q01': 'Out-of-School Study Time - Homework',
                   'ST57Q02': 'Out-of-School Study Time - Guided Homework',
                   'ST57Q03': 'Out-of-School Study Time - Personal Tutor',
                   'ST57Q04': 'Out-of-School Study Time - Commercial Company',
                   'ST57Q05': 'Out-of-School Study Time - With Parent',
                   'MMINS': 'Learning Time - Mathematics',
                   'LMINS': 'Learning Time - Test Language',
                   'SMINS': 'Learning Time - Science'}, axis='columns', inplace=True)

In [100]:
# Check to see if the columns are correctly renamed
list(pisa_clean)

['Country',
 'Student ID',
 'Gender',
 'Mother - Highest Schooling',
 'Mother Qualifications - ISCED level 6',
 'Mother Qualifications - ISCED level 5A',
 'Mother Qualifications - ISCED level 5B',
 'Mother Qualifications - ISCED level 4',
 'Father - Highest Schooling',
 'Father Qualifications - ISCED level 6',
 'Father Qualifications - ISCED level 5A',
 'Father Qualifications - ISCED level 5B',
 'Father Qualifications - ISCED level 4',
 'Out-of-School Study Time - Homework',
 'Out-of-School Study Time - Guided Homework',
 'Out-of-School Study Time - Personal Tutor',
 'Out-of-School Study Time - Commercial Company',
 'Out-of-School Study Time - With Parent',
 'Learning Time - Mathematics',
 'Learning Time - Test Language',
 'Learning Time - Science',
 'Average Math Score',
 'Average Reading Score',
 'Average Science Score',
 'Average Total Score']

# Null

In [151]:
pisa_clean.replace(["NaN"], np.nan, inplace = True)
pisa_clean.dropna(inplace = True)

In [152]:
pisa_clean.duplicated().sum()

0

### Education
Multiple columns with the single variable. 

http://uis.unesco.org/sites/default/files/documents/international-standard-classification-of-education-isced-2011-en.pdf

In [153]:
father_edu = pisa_clean.copy()

In [154]:
father_edu[['<ISCED level 1>', 
            '<ISCED level 2>', 
            '<ISCED level 3A>', 
            '<ISCED level 3B, 3C>', 
            'He did not complete <ISCED level 1>']] = pd.get_dummies(father_edu['Father - Highest Schooling'])

In [155]:
father_edu.rename({'He did not complete <ISCED level 1>': '<ISCED level 0>',
                   '<ISCED level 3A>': '<ISCED level 3>', 
                   '<ISCED level 3B, 3C>': '<ISCED level 3>',
                   'Father Qualifications - ISCED level 4': '<ISCED level 4>',
                   'Father Qualifications - ISCED level 5A': '<ISCED level 5>',
                   'Father Qualifications - ISCED level 5B': '<ISCED level 5>',
                   'Father Qualifications - ISCED level 6': '<ISCED level 6>'}, axis='columns', inplace=True)

In [156]:
father_edu['<ISCED level 0>'] = father_edu['<ISCED level 0>'].astype(str)
father_edu['<ISCED level 1>'] = father_edu['<ISCED level 1>'].astype(str)
father_edu['<ISCED level 2>'] = father_edu['<ISCED level 2>'].astype(str)
father_edu['<ISCED level 3>'] = father_edu['<ISCED level 3>'].astype(str)

In [157]:
father_edu['<ISCED level 0>'] = father_edu['<ISCED level 0>'].replace(regex='1', value='<ISCED level 0>')
father_edu['<ISCED level 1>'] = father_edu['<ISCED level 1>'].replace(regex='1', value='<ISCED level 1>')
father_edu['<ISCED level 2>'] = father_edu['<ISCED level 2>'].replace(regex='1', value='<ISCED level 2>')
father_edu['<ISCED level 3>'] = father_edu['<ISCED level 3>'].replace(regex='1', value='<ISCED level 3>')
father_edu['<ISCED level 4>'] = father_edu['<ISCED level 4>'].replace(regex='Yes', value='<ISCED level 4>')
father_edu['<ISCED level 5>'] = father_edu['<ISCED level 5>'].replace(regex='Yes', value='<ISCED level 5>')
father_edu['<ISCED level 6>'] = father_edu['<ISCED level 6>'].replace(regex='Yes', value='<ISCED level 6>')

In [158]:
father_edu.sample(10)

,Country,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Father - Highest Schooling,<ISCED level 6>,...,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,<ISCED level 1>,<ISCED level 2>,<ISCED level 3>,<ISCED level 3>,<ISCED level 0>
286898,Kazakhstan,1847,Female,<ISCED level 3A>,No,No,Yes,No,"<ISCED level 3B, 3C>",No,...,90.0,458.49040,512.81056,470.85042,480.717127,0,0,0,<ISCED level 3>,0
426940,Singapore,4165,Male,<ISCED level 3A>,No,No,No,Yes,He did not complete <ISCED level 1>,No,...,400.0,656.41846,597.91198,577.43380,610.588080,0,0,0,0,<ISCED level 0>
89389,Canada,14920,Male,<ISCED level 3A>,No,No,No,Yes,<ISCED level 3A>,No,...,300.0,607.50116,579.54746,613.52108,600.189900,0,0,<ISCED level 3>,0,0
408257,Florida (USA),1103,Female,<ISCED level 3A>,No,No,No,No,<ISCED level 3A>,No,...,250.0,410.42996,436.55678,438.67960,428.555447,0,0,<ISCED level 3>,0,0
180259,Finland,4585,Male,<ISCED level 3A>,Yes,Yes,No,No,<ISCED level 3A>,<ISCED level 6>,...,90.0,538.25362,546.50730,593.09960,559.286840,0,0,<ISCED level 3>,0,0
80043,Canada,5574,Female,<ISCED level 3A>,No,No,Yes,Yes,<ISCED level 3A>,No,...,375.0,700.89578,756.02832,723.74114,726.888413,0,0,<ISCED level 3>,0,0
148214,Spain,2632,Female,<ISCED level 3A>,No,No,Yes,Yes,<ISCED level 3A>,<ISCED level 6>,...,100.0,450.23368,476.27230,498.63856,475.048180,0,0,<ISCED level 3>,0,0
368247,Norway,4338,Female,<ISCED level 3A>,No,No,No,Yes,"<ISCED level 3B, 3C>",No,...,135.0,546.74404,617.10346,594.49834,586.115280,0,0,0,<ISCED level 3>,0
13912,United Arab Emirates,9170,Female,<ISCED level 3A>,No,No,No,No,"<ISCED level 3B, 3C>",No,...,270.0,449.06526,524.88408,470.57068,481.506673,0,0,0,<ISCED level 3>,0
219730,Hungary,3152,Male,"<ISCED level 3B, 3C>",No,No,No,No,"<ISCED level 3B, 3C>",No,...,135.0,535.13786,527.82198,565.59122,542.850353,0,0,0,<ISCED level 3>,0

In [159]:
father_edu = pd.melt(father_edu, 
                     id_vars=['Country','Student ID', 'Gender',
                            'Mother - Highest Schooling', 
                            'Mother Qualifications - ISCED level 6', 
                            'Mother Qualifications - ISCED level 5A',
                            'Mother Qualifications - ISCED level 5B',
                            'Mother Qualifications - ISCED level 4',
                            'Out-of-School Study Time - Homework',
                            'Out-of-School Study Time - Guided Homework',
                            'Out-of-School Study Time - Personal Tutor',
                            'Out-of-School Study Time - Commercial Company',
                            'Out-of-School Study Time - With Parent',
                            'Learning Time - Mathematics',
                            'Learning Time - Test Language',
                            'Learning Time - Science',
                            'Average Math Score',
                            'Average Reading Score',
                            'Average Science Score',
                            'Average Total Score'], var_name='Completed_edu - Father', value_name='Education - Father')

In [160]:
father_edu.sample(10)

,Country,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Completed_edu - Father,Education - Father
285905,Hong Kong-China,1595,Male,<ISCED level 3A>,No,Yes,No,No,4.0,0.0,...,1.0,210.0,210.0,210.0,716.94190,661.34584,693.99476,690.760833,<ISCED level 5>,<ISCED level 5>
998224,Lithuania,2311,Female,<ISCED level 3A>,No,No,No,No,2.0,1.0,...,1.0,135.0,225.0,180.0,508.18664,513.28714,550.48490,523.986227,<ISCED level 3>,0
828311,Switzerland,3969,Male,<ISCED level 2>,No,No,No,No,1.0,0.0,...,0.0,225.0,360.0,90.0,539.73362,519.96294,470.94366,510.213407,<ISCED level 3>,0
699797,Bulgaria,1163,Female,"<ISCED level 3B, 3C>",No,No,Yes,No,5.0,1.0,...,2.0,200.0,160.0,240.0,366.10844,426.70734,421.42858,404.748120,<ISCED level 2>,0
1140052,Singapore,3875,Female,<ISCED level 3A>,No,No,No,No,4.0,2.0,...,0.0,420.0,210.0,280.0,533.11266,516.46438,502.36850,517.315180,<ISCED level 0>,0
766761,Kazakhstan,1947,Male,<ISCED level 3A>,No,No,Yes,No,1.0,1.0,...,1.0,180.0,180.0,45.0,448.67580,358.13042,402.40584,403.070687,<ISCED level 2>,0
755192,Italy,2047,Male,<ISCED level 2>,No,No,No,No,3.0,0.0,...,0.0,240.0,360.0,120.0,404.74374,464.54854,434.76318,434.685153,<ISCED level 2>,0
798188,Slovak Republic,4224,Female,<ISCED level 3A>,No,No,No,No,3.0,0.0,...,1.0,135.0,135.0,45.0,584.52250,554.59126,539.66804,559.593933,<ISCED level 2>,0
321382,Peru,1357,Male,She did not complete <ISCED level 1>,No,No,No,No,4.0,2.0,...,0.0,480.0,480.0,480.0,336.35304,319.15588,383.38306,346.297327,<ISCED level 5>,No
198180,Latvia,1516,Male,<ISCED level 3A>,No,Yes,No,No,4.0,0.0,...,0.0,200.0,200.0,320.0,633.90714,530.62878,624.43120,596.322373,<ISCED level 6>,No

In [161]:
father_edu = father_edu[(father_edu['Education - Father'] != '0')] 
father_edu = father_edu[(father_edu['Education - Father'] != 'No')]

In [162]:
father_edu.sample(70)

,Country,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Completed_edu - Father,Education - Father
889297,Malaysia,927,Female,<ISCED level 3A>,No,No,Yes,No,6.0,2.0,...,0.0,60.0,60.0,60.0,441.82116,422.73580,417.69860,427.418520,<ISCED level 3>,<ISCED level 3>
259266,Chile,6408,Female,<ISCED level 3A>,No,No,Yes,No,5.0,2.0,...,0.0,315.0,270.0,315.0,535.37156,575.87880,557.19882,556.149727,<ISCED level 5>,<ISCED level 5>
660993,Netherlands,904,Male,<ISCED level 3A>,No,No,No,No,6.0,6.0,...,0.0,200.0,200.0,0.0,642.63126,531.02978,604.19620,592.619080,<ISCED level 1>,<ISCED level 1>
566665,Singapore,3996,Male,<ISCED level 1>,No,No,No,No,6.0,3.0,...,2.0,280.0,245.0,210.0,495.17838,428.30060,463.57702,462.352000,<ISCED level 4>,<ISCED level 4>
60138,Hungary,226,Female,<ISCED level 3A>,No,Yes,No,Yes,20.0,16.0,...,8.0,225.0,225.0,270.0,520.57174,558.00682,510.76092,529.779827,Father - Highest Schooling,<ISCED level 3A>
929693,Bulgaria,3241,Female,"<ISCED level 3B, 3C>",No,Yes,Yes,Yes,10.0,0.0,...,1.0,120.0,120.0,160.0,485.05220,575.64048,529.22418,529.972287,<ISCED level 3>,<ISCED level 3>
489264,Costa Rica,2738,Male,<ISCED level 3A>,No,Yes,No,Yes,8.0,1.0,...,0.0,240.0,200.0,160.0,472.97864,555.24852,492.85712,507.028093,<ISCED level 4>,<ISCED level 4>
60640,Hungary,1412,Male,<ISCED level 3A>,No,Yes,No,No,6.0,0.0,...,10.0,180.0,225.0,270.0,595.19396,576.98122,613.14808,595.107753,Father - Highest Schooling,<ISCED level 3A>
895985,Poland,942,Male,<ISCED level 3A>,No,No,No,No,2.0,1.0,...,1.0,180.0,180.0,180.0,420.94564,335.75616,372.19322,376.298340,<ISCED level 3>,<ISCED level 3>
844006,Spain,11729,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,0.0,0.0,...,0.0,200.0,200.0,150.0,637.17868,559.89980,570.81314,589.297207,<ISCED level 3>,<ISCED level 3>
36135,Denmark,4348,Male,<ISCED level 3A>,No,No,Yes,No,6.0,0.0,...,0.0,135.0,225.0,135.0,510.52344,397.98710,483.99852,464.169687,Father - Highest Schooling,<ISCED level 3A>
944484,Switzerland,7733,Female,"<ISCED level 3B, 3C>",No,No,No,No,1.0,0.0,...,0.0,300.0,360.0,240.0,538.95468,521.78628,530.90264,530.547867,<ISCED level 3>,<ISCED level 3>
887194,Macao-China,594,Male,<ISCED level 1>,No,No,No,No,1.0,1.0,...,0.0,200.0,200.0,160.0,598.62128,576.33966,579.01902,584.659987,<ISCED level 3>,<ISCED level 3>
36623,Denmark,5565,Female,<ISCED level 3A>,No,No,Yes,No,1.0,0.0,...,1.0,180.0,270.0,225.0,523.29802,485.64514,505.16600,504.703053,Father - Highest Schooling,<ISCED level 3A>
88922,Norway,425,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,2.0,0.0,...,0.0,180.0,225.0,180.0,469.78502,473.53030,454.25216,465.855827,Father - Highest Schooling,"<ISCED level 3B, 3C>"
997105,Kazakhstan,5247,Male,<ISCED level 2>,No,No,No,Yes,10.0,4.0,...,4.0,360.0,180.0,180.0,448.52002,401.11468,473.36816,441.000953,<ISCED level 3>,<ISCED level 3>
501742,Spain,17151,Male,<ISCED level 3A>,No,Yes,No,No,10.0,5.0,...,1.0,240.0,240.0,240.0,386.82816,402.07700,436.72136,408.542173,<ISCED level 4>,<ISCED level 4>
727438,Spain,6020,Female,<ISCED level 2>,No,No,No,No,3.0,0.0,...,0.0,165.0,165.0,330.0,506.16140,583.50418,514.86386,534.843147,<ISCED level 2>,<ISCED level 2>
618539,Spain,23612,Male,<ISCED level 2>,No,No,No,No,6.0,2.0,...,0.0,200.0,200.0,150.0,451.09050,435.99928,450.52220,445.870660,<ISCED level 1>,<ISCED level 1>
6567,Australia,12643,Male,<ISCED level 3A>,No,Yes,No,No,3.0,1.0,...,0.0,240.0,240.0,240.0,714.44928,736.72870,751.24954,734.142507,Father - Highest Schooling,<ISCED level 3A>
901072,China-Shanghai,235,Male,"<ISCED level 3B, 3C>",No,No,Yes,Yes,28.0,0.0,...,0.0,360.0,320.0,360.0,595.50554,538.32748,571.55912,568.464047,<ISCED level 3>,<ISCED level 3>
263574,Germany,4114,Male,<ISCED level 3A>,No,Yes,No,No,12.0,0.0,...,0.0,225.0,180.0,315.0,643.64386,685.16364,700.89518,676.567560,<ISCED level 5>,<ISCED level 5>
398252,United Kingdom,9662,Male,"<ISCED level 3B, 3C>",No,No,Yes,Yes,0.0,0.0,...,0.0,180.0,240.0,360.0,513.87288,451.39662,518.59380,494.621100,<ISCED level 5>,<ISCED level 5>
571755,United States of America,406,Male,<ISCED level 3A>,No,No,Yes,Yes,4.0,1.0,...,0.0,275.0,250.0,550.0,592.93504,561.66406,593.75234,582.783813,<ISCED level 4>,<ISCED level 4>
96242,Portugal,3186,Female,<ISCED level 2>,No,No,No,No,16.0,0.0,...,0.0,270.0,180.0,270.0,603.21702,632.91024,595.24430,610.457187,Father - Highest Schooling,<ISCED level 1>
566024,Singapore,2496,Male,<ISCED level 3A>,No,No,No,Yes,2.0,0.0,...,0.0,240.0,240.0,280.0,523.68750,479.14394,524.56172,509.131053,<ISCED level 4>,<ISCED level 4>
906506,Romania,2039,Female,<ISCED level 3A>,No,No,No,No,4.0,0.0,...,0.0,150.0,150.0,0.0,391.81338,406.37302,359.32488,385.837093,<ISCED level 3>,<ISCED level 3>
18036,Canada,4586,Female,<ISCED level 3A>,No,No,No,No,10.0,2.0,...,2.0,300.0,300.0,300.0,404.19844,430.75832,442.87578,425.944180,Father - Highest Schooling,<ISCED level 3A>
917488,United States of America,4936,Female,<ISCED level 3A>,Yes,No,No,No,12.0,8.0,...,2.0,350.0,350.0,350.0,520.57172,600.58180,577.90002,566.351180,<ISCED level 3>,<ISCED level 3>
805241,United Arab Emirates,7206,Male,<ISCED level 3A>,No,No,No,No,6.0,1.0,...,1.0,225.0,225.0,450.0,491.20578,504.72596,490.43268,495.454807,<ISCED level 3>,<ISCED level 3>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945354,Switzerland,9926,Male,"<ISCED level 3B, 3C>",No,No,Yes,No,7.0,5.0,...,1.0,180.0,180.0,180.0,547.28928,479.54490,500.31704,509.050407,<ISCED level 3>,<ISCED level 3>
52967,United Kingdom,6409,Female,"<ISCED level 3B, 3C>",No,No,No,Yes,6.0,1.0,...,1.0,240.0,180.0,240.0,495.87944,447.67714,462.64454,468.733707,Father - Highest Schooling,"<ISCED level 3B, 3C>"
378275,Germany,4164,Male,<ISCED level 2>,No,No,No,Yes,2.0,0.0,...,3.0,180.0,180.0,405.0,565.82798,536.48302,592.81984,565.043613,<ISCED level 5>,<ISCED level 5>
1008489,New Zealand,2084,Male,"<ISCED level 3B, 3C>",No,No,No,No,2.0,1.0,...,1.0,200.0,200.0,200.0,627.59774,602.56328,623.68520,617.948740,<ISCED level 3>,<ISCED level 3>
87086,Malaysia,4251,Female,<ISCED level 3A>,No,Yes,Yes,Yes,7.0,1.0,...,2.0,90.0,120.0,120.0,285.25474,298.42626,299.36594,294.348980,Father - Highest Schooling,<ISCED level 3A>
891113,Netherlands,3029,Female,<ISCED level 3A>,No,No,Yes,Yes,2.0,0.0,...,1.0,100.0,100.0,100.0,368.99050,360.85904,416.02014,381.956560,<ISCED level 3>,<ISCED level 3>
929434,Bulgaria,2197,Female,"<ISCED level 3B, 3C>",No,Yes,Yes,Yes,4.0,1.0,...,3.0,135.0,135.0,270.0,468.61660,550.93746,518.03430,512.529453,<ISCED level 3>,<ISCED level 3>
856753,United Kingdom,8986,Male,"<ISCED level 3B, 3C>",No,No,No,No,2.0,0.0,...,0.0,240.0,240.0,300.0,571.43634,587.32634,622.75270,593.838460,<ISCED level 3>,<ISCED level 3>
998044,Lithuania,1879,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,6.0,0.0,...,1.0,180.0,225.0,270.0,493.07522,495.50360,490.71242,493.097080,<ISCED level 3>,<ISCED level 3>
42667,Spain,16209,Male,<ISCED level 1>,No,No,No,No,2.0,0.0,...,0.0,220.0,220.0,165.0,479.91120,497.02732,547.59420,508.177573,Father - Highest Schooling,"<ISCED level 3B, 3C>"
30548,Costa Rica,2915,Female,She did not complete <ISCED level 1>,No,No,No,No,2.0,1.0,...,1.0,240.0,200.0,200.0,349.90654,425.11870,409.86572,394.963653,Father - Highest Schooling,He did not complete <ISCED level 1>
94407,Poland,2986,Male,<ISCED level 3A>,No,No,No,No,1.0,1.0,...,0.0,180.0,180.0,225.0,384.10188,358.53138,413.40918,385.347480,Father - Highest Schooling,<ISCED level 3A>
984269,Italy,1253,Female,"<ISCED level 3B, 3C>",No,No,No,Yes,4.0,3.0,...,0.0,240.0,360.0,120.0,431.22760,444.73816,440.17160,438.712453,<ISCED level 3>,<ISCED level 3>
575491,United Arab Emirates,5389,Male,<ISCED level 2>,No,No,No,No,3.0,2.0,...,4.0,270.0,270.0,315.0,413.85730,429.34312,451.92094,431.707120,<ISCED level 1>,<ISCED level 1>
310514,Lithuania,3459,Male,<ISCED level 3A>,No,Yes,No,Yes,5.0,1.0,...,1.0,180.0,180.0,270.0,523.99906,447.06612,449.40320,473.489460,<ISCED level 5>,<ISCED level 5>
929915,Bulgaria,4060,Male,"<ISCED level 3B, 3C>",No,Yes,Yes,No,2.0,2.0,...,2.0,160.0,80.0,240.0,372.10624,345.94086,373.96492,364.004007,<ISCED level 3>,<ISCED level 3>
35490,Denmark,2741,Male,<ISCED level 1>,No,No,No,No,3.0,2.0,...,0.0,350.0,630.0,135.0,468.22714,429.98470,391.68218,429.964673,Father - Highest Schooling,<ISCED level 1>
550810,Peru,1735,Male,<ISCED level 3A>,No,No,No,Yes,12.0,10.0,...,0.0,270.0,225.0,225.0,462.46302,555.32872,487.91492,501.902220,<ISCED level 4>,<ISCED level 4>
449364,Russian Federation,1804,Female,<ISCED level 3A>,No,No,Yes,No,5.0,5.0,...,0.0,135.0,180.0,90.0,415.02570,442.43466,454.99816,437.486173,<ISCED level 5>,<ISCED level 5>
812172,Belgium,1933,Female,<ISCED level 3A>,No,No,No,Yes,0.0,0.0,...,2.0,150.0,200.0,360.0,423.20454,427.89880,431.87246,427.658600,<ISCED level 3>,<ISCED level 3>
474450,Brazil,15297,Male,<ISCED level 3A>,No,Yes,Yes,Yes,0.0,0.0,...,0.0,200.0,200.0,150.0,528.75058,564.87186,499.01156,530.878000,<ISCED level 4>,<ISCED level 4>
910254,Singapore,2888,Male,<ISCED level 3A>,No,No,No,No,7.0,0.0,...,0.0,350.0,210.0,350.0,713.12510,604.00680,684.66992,667.267273,<ISCED level 3>,<ISCED level 3>
300571,Italy,12935,Male,"<ISCED level 3B, 3C>",No,No,No,No,14.0,0.0,...,0.0,250.0,200.0,50.0,707.75042,648.27416,674.50578,676.843453,<ISCED level 5>,<ISCED level 5>
775828,Netherlands,1349,Male,<ISCED level 2>,No,No,No,Yes,5.0,0.0,...,1.0,150.0,150.0,350.0,571.59214,545.70538,540.32078,552.539433,<ISCED level 2>,<ISCED level 2>
68024,Italy,4596,Male,"<ISCED level 3B, 3C>",No,No,No,No,20.0,10.0,...,0.0,275.0,275.0,110.0,605.24226,615.31418,607.83290,609.463113,Father - Highest Schooling,<ISCED level 3A>
26,Albania,166,Male,"<ISCED level 3B, 3C>",No,No,No,Yes,3.0,0.0,...,2.0,180.0,225.0,90.0,224.80914,250.26880,370.23498,281.770973,Father - Highest Schooling,<ISCED level 3A>
59552,Croatia,3802,Female,<ISCED level 3A>,No,No,No,No,6.0,1.0,...,0.0,180.0,180.0,270.0,481.46910,535.52784,500.41028,505.802407,Father - Highest Schooling,"<ISCED level 3B, 3C>"
97353,Qatar,4186,Female,"<ISCED level 3B, 3C>",No,No,No,No,1.0,1.0,...,2.0,275.0,220.0,165.0,267.33914,285.39956,309.06380,287.267500,Father - Highest Schooling,<ISCED level 2>
26018,Switzerland,5233,Female,"<ISCED level 3B, 3C>",No,No,Yes,No,4.0,1.0,...,1.0,225.0,180.0,180.0,562.08910,545.53610,535.19210,547.605767,Father - Highest Schooling,"<ISCED level 3B, 3C>"
875045,Italy,15605,Female,<ISCED level 2>,No,No,No,No,2.0,2.0,...,0.0,240.0,180.0,120.0,389.08708,361.89162,281.27564,344.084780,<ISCED level 3>,<ISCED level 3>

In [163]:
father_edu = father_edu[(father_edu['Completed_edu - Father'] != 'Father - Highest Schooling')]

In [164]:
father_edu['Education - Father'].value_counts()

<ISCED level 3>    84496
<ISCED level 5>    49085
<ISCED level 4>    26411
<ISCED level 2>    21955
<ISCED level 6>     6715
<ISCED level 1>     5947
<ISCED level 0>     2290
Name: Education - Father, dtype: int64

In [165]:
father_edu.drop(columns=['Completed_edu - Father'], axis=1, inplace=True)

In [166]:
father_edu.sample(10)

,Country,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father
561917,Romania,492,Male,<ISCED level 3A>,No,No,No,No,3.0,1.0,...,2.0,1.0,180.0,180.0,129.0,334.09410,356.68690,387.95226,359.577753,<ISCED level 4>
965256,Finland,570,Male,<ISCED level 2>,No,No,No,No,0.0,0.0,...,0.0,0.0,180.0,135.0,135.0,454.20628,409.77568,502.46176,455.481240,<ISCED level 3>
223261,Singapore,5509,Male,<ISCED level 3A>,Yes,Yes,Yes,Yes,1.0,1.0,...,1.0,1.0,270.0,270.0,210.0,427.25500,436.80122,466.37448,443.476900,<ISCED level 6>
863429,Hungary,1364,Male,"<ISCED level 3B, 3C>",No,No,Yes,Yes,20.0,15.0,...,0.0,6.0,180.0,180.0,192.0,556.16918,549.07354,598.88102,568.041247,<ISCED level 3>
379483,Denmark,2590,Male,<ISCED level 3A>,No,No,Yes,No,4.0,1.0,...,0.0,1.0,160.0,200.0,160.0,494.16576,499.11236,521.57778,504.951967,<ISCED level 5>
447740,Romania,1981,Female,<ISCED level 3A>,No,Yes,Yes,No,8.0,0.0,...,0.0,0.0,200.0,150.0,350.0,599.71178,567.37964,567.64266,578.244693,<ISCED level 5>
743880,Greece,4420,Female,<ISCED level 2>,No,No,No,No,3.0,0.0,...,4.0,2.0,160.0,160.0,120.0,349.75076,489.45782,392.89442,410.701000,<ISCED level 2>
729785,Spain,13196,Female,"<ISCED level 3B, 3C>",No,No,Yes,No,10.0,4.0,...,4.0,1.0,180.0,180.0,0.0,480.92380,477.22546,504.97946,487.709573,<ISCED level 2>
498794,Spain,8190,Male,"<ISCED level 3B, 3C>",No,No,Yes,Yes,3.0,2.0,...,2.0,0.0,240.0,180.0,180.0,523.68750,500.15488,495.09512,506.312500,<ISCED level 4>
454434,Slovenia,460,Female,<ISCED level 2>,No,No,No,No,0.0,0.0,...,0.0,0.0,180.0,180.0,90.0,551.80712,568.96828,589.55614,570.110513,<ISCED level 5>

In [167]:
father_edu.duplicated().sum()

6947

In [168]:
# https://stackoverflow.com/questions/33042777/removing-duplicates-from-pandas-dataframe-with-condition-for-retaining-original
father_edu['Education - Father'] = father_edu['Education - Father'].astype('category')

father_edu['Education - Father'] = father_edu['Education - Father'].cat.set_categories(['<ISCED level 0>', 
                                                                                        '<ISCED level 1>', 
                                                                                        '<ISCED level 2>', 
                                                                                        '<ISCED level 3>',
                                                                                        '<ISCED level 4>', 
                                                                                        '<ISCED level 5>', 
                                                                                        '<ISCED level 6>'], ordered=True)
father_edu.sort_values(['Education - Father'], inplace=True)
# father_edu_clean = father_edu.drop_duplicates(subset='Student ID', keep='last')

In [169]:
father_edu_clean.duplicated().sum()

0

In [170]:
father_edu.shape

(196899, 21)

In [171]:
father_edu_clean.sample(10)

,Country,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father
1312598,Mexico,25916,Female,<ISCED level 1>,No,No,No,NaN,4.0,2.0,...,0.0,3.0,200.0,200.0,200.0,442.98956,531.23856,467.95974,480.729287,NaN
1234766,Italy,23197,Female,<ISCED level 3A>,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,524.70010,576.91140,619.20924,573.606913,NaN
1315741,Mexico,29059,Male,She did not complete <ISCED level 1>,No,NaN,NaN,NaN,4.0,NaN,...,5.0,4.0,300.0,180.0,180.0,378.41566,399.67116,412.47670,396.854507,NaN
1320155,Mexico,33473,Male,<ISCED level 1>,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,367.89998,397.98710,416.95262,394.279900,NaN
1299705,Mexico,13023,Female,She did not complete <ISCED level 1>,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,341.88348,328.53060,328.17978,332.864620,NaN
1312316,Mexico,25634,Male,<ISCED level 2>,No,No,No,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,464.02088,464.70892,447.25846,458.662753,NaN
2269247,Mexico,11585,Female,<ISCED level 2>,No,No,No,NaN,4.0,0.0,...,0.0,2.0,250.0,250.0,400.0,360.73378,393.50518,354.28942,369.509460,NaN
652077,Spain,21005,Male,<ISCED level 2>,No,No,No,No,7.0,2.0,...,0.0,3.0,200.0,150.0,100.0,393.52704,448.91058,456.30364,432.913753,NaN
650365,Spain,19293,Female,"<ISCED level 3B, 3C>",NaN,NaN,NaN,Yes,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,448.98736,481.67362,464.88250,465.181160,NaN
649264,Spain,18192,Male,NaN,NaN,NaN,NaN,NaN,3.0,NaN,...,NaN,NaN,165.0,275.0,165.0,457.47780,388.36372,433.73740,426.526307,NaN

### Mother Edu

In [172]:
mother_edu = father_edu.copy()

In [173]:
mother_edu.head()

,Country,Student ID,Gender,Mother - Highest Schooling,Mother Qualifications - ISCED level 6,Mother Qualifications - ISCED level 5A,Mother Qualifications - ISCED level 5B,Mother Qualifications - ISCED level 4,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father
1146860,United States of America,4922,Female,She did not complete <ISCED level 1>,No,No,No,No,10.0,0.0,...,0.0,0.0,300.0,300.0,300.0,596.82972,578.02342,547.40770,574.086947,<ISCED level 0>
1062200,Costa Rica,46,Male,She did not complete <ISCED level 1>,No,No,No,No,10.0,1.0,...,2.0,1.0,320.0,240.0,240.0,274.27170,302.31502,343.84560,306.810773,<ISCED level 0>
1062201,Costa Rica,48,Female,<ISCED level 1>,No,No,No,No,4.0,2.0,...,0.0,1.0,160.0,240.0,240.0,343.98660,357.76122,351.30548,351.017767,<ISCED level 0>
1062215,Costa Rica,100,Female,<ISCED level 1>,No,No,No,No,5.0,0.0,...,0.0,0.0,120.0,120.0,240.0,427.64448,444.97648,483.53226,452.051073,<ISCED level 0>
1062219,Costa Rica,126,Male,<ISCED level 3A>,No,No,No,No,1.0,0.0,...,0.0,0.0,200.0,200.0,360.0,427.72240,423.97008,419.65684,423.783107,<ISCED level 0>

In [174]:
mother_edu['Mother - Highest Schooling'].value_counts()

<ISCED level 3A>                         120377
<ISCED level 3B, 3C>                      39451
<ISCED level 2>                           28132
<ISCED level 1>                            6189
She did not complete <ISCED level 1>       2750
Name: Mother - Highest Schooling, dtype: int64

In [175]:
pisa_clean['Mother - Highest Schooling'].value_counts()

<ISCED level 3A>                         63660
<ISCED level 3B, 3C>                     23596
<ISCED level 2>                          19860
<ISCED level 1>                           5189
She did not complete <ISCED level 1>      2383
Name: Mother - Highest Schooling, dtype: int64

In [176]:
mother_edu[['<ISCED level 1>', 
            '<ISCED level 2>', 
            '<ISCED level 3A>', 
            '<ISCED level 3B, 3C>', 
            'She did not complete <ISCED level 1>']] = pd.get_dummies(mother_edu['Mother - Highest Schooling'])

In [177]:
mother_edu.rename({'She did not complete <ISCED level 1>': '<ISCED level 0>',
                   '<ISCED level 3A>': '<ISCED level 3>', 
                   '<ISCED level 3B, 3C>': '<ISCED level 3>',
                   'Mother Qualifications - ISCED level 4': '<ISCED level 4>',
                   'Mother Qualifications - ISCED level 5A': '<ISCED level 5>',
                   'Mother Qualifications - ISCED level 5B': '<ISCED level 5>',
                   'Mother Qualifications - ISCED level 6': '<ISCED level 6>'}, axis='columns', inplace=True)

In [178]:
mother_edu['<ISCED level 0>'] = mother_edu['<ISCED level 0>'].astype(str)
mother_edu['<ISCED level 1>'] = mother_edu['<ISCED level 1>'].astype(str)
mother_edu['<ISCED level 2>'] = mother_edu['<ISCED level 2>'].astype(str)
mother_edu['<ISCED level 3>'] = mother_edu['<ISCED level 3>'].astype(str)

In [179]:
mother_edu['<ISCED level 0>'] = mother_edu['<ISCED level 0>'].replace(regex='1', value='<ISCED level 0>')
mother_edu['<ISCED level 1>'] = mother_edu['<ISCED level 1>'].replace(regex='1', value='<ISCED level 1>')
mother_edu['<ISCED level 2>'] = mother_edu['<ISCED level 2>'].replace(regex='1', value='<ISCED level 2>')
mother_edu['<ISCED level 3>'] = mother_edu['<ISCED level 3>'].replace(regex='1', value='<ISCED level 3>')
mother_edu['<ISCED level 4>'] = mother_edu['<ISCED level 4>'].replace(regex='Yes', value='<ISCED level 4>')
mother_edu['<ISCED level 5>'] = mother_edu['<ISCED level 5>'].replace(regex='Yes', value='<ISCED level 5>')
mother_edu['<ISCED level 6>'] = mother_edu['<ISCED level 6>'].replace(regex='Yes', value='<ISCED level 6>')

In [180]:
mother_edu.sample(10)

,Country,Student ID,Gender,Mother - Highest Schooling,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>,<ISCED level 4>,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,...,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,<ISCED level 1>,<ISCED level 2>,<ISCED level 3>,<ISCED level 3>,<ISCED level 0>
694415,Australia,11538,Male,<ISCED level 3A>,No,<ISCED level 5>,No,No,7.0,0.0,...,490.58262,498.15004,538.54906,509.093907,<ISCED level 2>,0,0,<ISCED level 3>,0,0
837610,Denmark,976,Male,<ISCED level 3A>,No,No,<ISCED level 5>,No,2.0,0.0,...,580.54994,575.21694,565.59120,573.786027,<ISCED level 3>,0,0,<ISCED level 3>,0,0
687660,United States of America,3744,Female,<ISCED level 3A>,No,No,No,No,3.0,0.0,...,521.97382,576.11708,563.53972,553.876873,<ISCED level 1>,0,0,<ISCED level 3>,0,0
983151,Israel,2698,Female,<ISCED level 3A>,No,No,<ISCED level 5>,No,6.0,0.0,...,572.99424,610.82842,535.93808,573.253580,<ISCED level 3>,0,0,<ISCED level 3>,0,0
752466,Iceland,1693,Female,<ISCED level 2>,No,No,No,No,3.0,0.0,...,471.88814,561.74006,509.54866,514.392287,<ISCED level 2>,0,<ISCED level 2>,0,0,0
972143,United Kingdom,10928,Male,"<ISCED level 3B, 3C>",No,No,<ISCED level 5>,<ISCED level 4>,7.0,0.0,...,532.64526,553.08328,583.30848,556.345673,<ISCED level 3>,0,0,0,<ISCED level 3>,0
866859,Iceland,822,Female,<ISCED level 3A>,No,No,No,No,2.0,1.0,...,381.92086,390.24850,366.22528,379.464880,<ISCED level 3>,0,0,<ISCED level 3>,0,0
361002,Canada,1435,Male,<ISCED level 3A>,No,<ISCED level 5>,<ISCED level 5>,No,1.0,0.0,...,631.41456,570.40528,539.94778,580.589207,<ISCED level 5>,0,0,<ISCED level 3>,0,0
879235,Italy,26603,Female,<ISCED level 3A>,No,No,No,No,15.0,2.0,...,478.58700,563.96412,526.05372,522.868280,<ISCED level 3>,0,0,<ISCED level 3>,0,0
574991,United Arab Emirates,3086,Male,<ISCED level 3A>,No,No,No,No,4.0,4.0,...,349.04968,328.77922,346.45656,341.428487,<ISCED level 1>,0,0,<ISCED level 3>,0,0

In [181]:
mother_edu = pd.melt(mother_edu, 
                     id_vars=['Country','Student ID', 'Gender',
                            'Out-of-School Study Time - Homework',
                            'Out-of-School Study Time - Guided Homework',
                            'Out-of-School Study Time - Personal Tutor',
                            'Out-of-School Study Time - Commercial Company',
                            'Out-of-School Study Time - With Parent',
                            'Learning Time - Mathematics',
                            'Learning Time - Test Language',
                            'Learning Time - Science',
                            'Average Math Score',
                            'Average Reading Score',
                            'Average Science Score',
                            'Average Total Score',
                             'Education - Father'], var_name='Completed_edu - Mother', value_name='Education - Mother')

In [182]:
mother_edu.sample(10)

,Country,Student ID,Gender,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Completed_edu - Mother,Education - Mother
961343,United Arab Emirates,714,Female,7.0,2.0,6.0,6.0,0.0,360.0,180.0,0.0,502.65618,610.35184,560.55576,557.854593,<ISCED level 5>,<ISCED level 4>,No
1257000,Austria,1046,Male,6.0,4.0,2.0,2.0,0.0,150.0,150.0,650.0,655.09426,583.47698,647.74336,628.771533,<ISCED level 3>,<ISCED level 2>,0
493938,Norway,1865,Male,5.0,1.0,0.0,0.0,1.0,120.0,120.0,120.0,427.09924,394.29816,420.12310,413.840167,<ISCED level 3>,<ISCED level 5>,No
843446,Qatar,5050,Female,6.0,0.0,1.0,0.0,1.0,275.0,275.0,275.0,327.23944,325.67108,293.39800,315.436173,<ISCED level 3>,<ISCED level 4>,No
918137,Belgium,7827,Female,10.0,0.0,0.0,0.0,3.0,250.0,250.0,150.0,587.24878,617.10350,620.23500,608.195760,<ISCED level 4>,<ISCED level 4>,No
53839,Netherlands,1471,Female,10.0,0.0,0.0,0.0,0.0,120.0,120.0,60.0,527.97162,582.15382,587.22494,565.783460,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 2>
69529,Estonia,1001,Female,3.0,1.0,0.0,0.0,1.0,225.0,180.0,225.0,436.21280,497.24210,507.77694,480.410613,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 3A>
1382650,Singapore,4575,Male,5.0,4.0,0.0,0.0,0.0,385.0,210.0,245.0,530.23056,530.30802,498.63856,519.725713,<ISCED level 1>,<ISCED level 3>,<ISCED level 3>
161768,Spain,20625,Male,10.0,0.0,0.0,0.0,0.0,220.0,220.0,330.0,650.57642,527.10026,619.95524,599.210640,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
81391,Switzerland,6920,Female,10.0,0.0,0.0,0.0,0.0,250.0,300.0,50.0,562.47858,590.09694,544.33048,565.635333,<ISCED level 3>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"

In [183]:
mother_edu = mother_edu[(mother_edu['Education - Mother'] != '0')] 
mother_edu = mother_edu[(mother_edu['Education - Mother'] != 'No')]

In [184]:
mother_edu.sample(70)

,Country,Student ID,Gender,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Completed_edu - Mother,Education - Mother
1514072,Israel,2212,Female,8.0,0.0,0.0,0.0,1.0,180.0,225.0,405.0,702.84312,729.33950,693.24876,708.477127,<ISCED level 4>,<ISCED level 3>,<ISCED level 3>
1447720,Estonia,737,Male,8.0,3.0,2.0,0.0,1.0,225.0,180.0,270.0,565.98378,506.57044,577.80676,550.120327,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
186410,Spain,8548,Female,3.0,0.0,0.0,3.0,0.0,240.0,240.0,180.0,626.50724,601.05840,608.11266,611.892767,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
1038654,Macao-China,5331,Female,1.0,1.0,2.0,0.0,0.0,245.0,245.0,315.0,511.30236,480.87930,540.22752,510.803060,<ISCED level 3>,<ISCED level 1>,<ISCED level 1>
177311,Australia,2021,Male,10.0,3.0,1.0,2.0,2.0,320.0,320.0,320.0,454.51784,496.06496,530.43640,493.673067,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
183368,Kazakhstan,797,Male,9.0,0.0,0.0,0.0,0.0,160.0,160.0,160.0,557.96074,421.80486,539.48152,506.415707,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
156101,Switzerland,4381,Female,2.0,0.0,0.0,0.0,1.0,225.0,225.0,90.0,470.09660,541.64402,528.66468,513.468433,<ISCED level 5>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
8501,Australia,12223,Female,1.0,0.0,0.0,0.0,1.0,210.0,210.0,210.0,433.64230,505.34404,462.73778,467.241373,<ISCED level 2>,Mother - Highest Schooling,<ISCED level 2>
57635,Poland,966,Female,3.0,0.0,0.0,2.0,0.0,180.0,180.0,180.0,544.09564,536.87816,522.69676,534.556853,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 3A>
907032,Luxembourg,1569,Male,2.0,0.0,0.0,0.0,1.0,200.0,200.0,150.0,423.51614,403.44030,421.80156,416.252667,<ISCED level 4>,<ISCED level 4>,<ISCED level 4>
1531601,Romania,4411,Male,3.0,0.0,0.0,0.0,0.0,200.0,200.0,500.0,544.40726,501.91916,547.22118,531.182533,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
49744,Romania,4328,Male,3.0,1.0,0.0,0.0,0.0,150.0,150.0,100.0,399.29118,368.55570,360.63036,376.159080,<ISCED level 3>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
519688,Connecticut (USA),1347,Male,30.0,10.0,5.0,20.0,10.0,250.0,240.0,315.0,439.56222,523.49148,491.27188,484.775193,<ISCED level 4>,<ISCED level 5>,<ISCED level 5>
135190,Hong Kong-China,3131,Female,2.0,0.0,0.0,6.0,0.0,245.0,245.0,0.0,624.48200,588.74658,592.35362,601.860733,<ISCED level 4>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
1759341,Lithuania,3105,Male,2.0,0.0,1.0,0.0,0.0,135.0,180.0,270.0,454.12838,486.60200,520.64526,487.125213,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
122142,Slovenia,3562,Female,4.0,3.0,0.0,0.0,0.0,135.0,135.0,90.0,375.92304,379.44590,398.67588,384.681607,<ISCED level 4>,Mother - Highest Schooling,<ISCED level 2>
148331,Slovak Republic,4329,Male,0.0,0.0,0.0,0.0,0.0,225.0,225.0,225.0,596.67392,541.45506,518.03432,552.054433,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
646852,Qatar,6520,Female,4.0,4.0,4.0,0.0,2.0,250.0,150.0,150.0,343.75292,428.53426,369.02276,380.436647,<ISCED level 3>,<ISCED level 5>,<ISCED level 5>
717569,Canada,17251,Male,1.0,1.0,0.0,0.0,0.0,50.0,50.0,50.0,407.47000,335.35518,394.85266,379.225947,<ISCED level 4>,<ISCED level 5>,<ISCED level 5>
1538769,Estonia,3217,Male,2.0,1.0,2.0,0.0,1.0,225.0,270.0,90.0,547.28930,499.75394,569.78740,538.943547,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
96198,Denmark,1229,Female,3.0,2.0,0.0,0.0,0.0,315.0,315.0,135.0,395.39648,426.54848,374.43118,398.792047,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 3A>
4419,Singapore,3570,Female,14.0,0.0,3.0,0.0,0.0,210.0,210.0,210.0,468.46082,460.54496,483.34576,470.783847,<ISCED level 1>,Mother - Highest Schooling,<ISCED level 3A>
787550,Malaysia,4879,Male,14.0,10.0,8.0,10.0,4.0,200.0,200.0,320.0,517.06652,443.37720,456.21038,472.218033,<ISCED level 6>,<ISCED level 5>,<ISCED level 5>
106006,Italy,6469,Male,2.0,2.0,2.0,2.0,2.0,300.0,300.0,0.0,392.67018,358.29080,368.92952,373.296833,<ISCED level 3>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
691437,Norway,353,Male,2.0,0.0,0.0,0.0,0.0,180.0,180.0,120.0,507.01824,500.15490,480.17530,495.782813,<ISCED level 3>,<ISCED level 5>,<ISCED level 5>
170866,Denmark,3648,Female,3.0,0.0,0.0,0.0,0.0,225.0,270.0,225.0,513.63918,568.72998,541.90598,541.425047,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
1198466,Malaysia,1880,Female,1.0,1.0,1.0,1.0,1.0,200.0,240.0,200.0,329.49838,289.84770,325.28908,314.878387,<ISCED level 2>,<ISCED level 2>,<ISCED level 2>
138377,Denmark,1994,Female,10.0,7.0,0.0,0.0,2.0,180.0,225.0,90.0,510.36768,545.53612,463.95002,506.617940,<ISCED level 4>,Mother - Highest Schooling,<ISCED level 3A>
72626,Brazil,14869,Female,5.0,0.0,5.0,5.0,0.0,200.0,200.0,150.0,415.33728,496.60664,377.04216,429.662027,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 2>
1426,Poland,1137,Female,10.0,0.0,0.0,0.0,0.0,180.0,180.0,135.0,606.95590,612.17878,591.70084,603.611840,<ISCED level 0>,Mother - Highest Schooling,<ISCED level 2>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113360,Slovenia,4325,Male,9.0,1.0,0.0,0.0,0.0,135.0,180.0,225.0,593.86976,549.07354,620.51474,587.819347,<ISCED level 3>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
1424594,China-Shanghai,2408,Male,10.0,3.0,0.0,0.0,1.0,200.0,168.0,240.0,733.45536,668.72374,667.23238,689.803827,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
896365,Lithuania,1383,Female,3.0,3.0,0.0,0.0,0.0,135.0,180.0,315.0,442.60010,448.55086,469.35844,453.503133,<ISCED level 3>,<ISCED level 4>,<ISCED level 4>
1669442,Austria,1443,Female,1.0,0.0,0.0,0.0,0.0,0.0,150.0,100.0,481.54696,529.33222,515.98284,508.954007,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
1448902,United Kingdom,10305,Male,5.0,1.0,0.0,0.0,0.0,216.0,216.0,486.0,704.24520,643.22190,680.84670,676.104600,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
568605,Romania,1239,Female,6.0,0.0,0.0,0.0,2.0,200.0,200.0,400.0,653.84794,622.42538,623.21896,633.164093,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
1412236,Lithuania,3093,Female,2.0,0.0,0.0,0.0,0.0,180.0,180.0,270.0,635.85450,641.40936,662.94294,646.735600,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
147170,Italy,15675,Male,2.0,1.0,0.0,0.0,1.0,220.0,275.0,110.0,467.29242,499.59352,509.92168,492.269207,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 2>
564367,Denmark,6043,Male,5.0,0.0,0.0,0.0,0.0,270.0,270.0,135.0,512.78238,477.29946,529.31740,506.466413,<ISCED level 5>,<ISCED level 5>,<ISCED level 5>
194061,Chile,4831,Male,8.0,7.0,0.0,0.0,5.0,360.0,360.0,315.0,574.47422,535.19988,572.49160,560.721900,<ISCED level 6>,Mother - Highest Schooling,<ISCED level 3A>
353851,Canada,18554,Male,2.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,657.66474,606.73338,646.81088,637.069667,<ISCED level 5>,<ISCED level 6>,<ISCED level 6>
178548,Italy,18497,Female,21.0,4.0,0.0,3.0,0.0,300.0,200.0,100.0,482.32590,523.93088,490.89892,499.051900,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>
1423929,Romania,1552,Male,1.0,1.0,1.0,1.0,1.0,200.0,150.0,100.0,377.94828,373.52776,384.31556,378.597200,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
23208,Italy,28449,Male,10.0,3.0,0.0,0.0,3.0,220.0,330.0,110.0,431.14970,398.06728,418.35136,415.856113,<ISCED level 2>,Mother - Highest Schooling,<ISCED level 2>
836689,Slovak Republic,456,Male,1.0,1.0,0.0,0.0,0.0,180.0,135.0,315.0,478.58702,505.12696,507.68370,497.132560,<ISCED level 3>,<ISCED level 4>,<ISCED level 4>
15373,Slovak Republic,2129,Female,2.0,1.0,3.0,4.0,6.0,225.0,225.0,180.0,282.84002,340.44526,331.44348,318.242920,<ISCED level 2>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
190512,Bulgaria,1032,Male,14.0,5.0,4.0,2.0,0.0,280.0,120.0,200.0,588.33932,608.49768,587.87766,594.904887,<ISCED level 6>,Mother - Highest Schooling,"<ISCED level 3B, 3C>"
1540113,Spain,17640,Female,12.0,0.0,0.0,0.0,0.0,240.0,180.0,360.0,653.53638,702.73010,630.02610,662.097527,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
1712266,Iceland,2997,Female,1.0,0.0,0.0,0.0,0.0,160.0,240.0,120.0,466.04612,564.91730,563.63298,531.532133,<ISCED level 4>,<ISCED level 3>,<ISCED level 3>
1676691,New Zealand,1294,Female,0.0,0.0,0.0,0.0,0.0,240.0,240.0,240.0,428.73500,471.18872,460.96606,453.629927,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
1457132,Canada,21215,Male,4.0,3.0,0.0,0.0,3.0,180.0,180.0,180.0,486.68794,491.97506,476.91160,485.191533,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
841010,Latvia,2231,Female,3.0,0.0,0.0,4.0,1.0,240.0,200.0,320.0,492.37422,523.85146,491.92464,502.716773,<ISCED level 3>,<ISCED level 4>,<ISCED level 4>
793761,Australia,13104,Female,5.0,0.0,0.0,0.0,0.0,200.0,200.0,200.0,440.02958,536.16326,496.68034,490.957727,<ISCED level 1>,<ISCED level 4>,<ISCED level 4>
1207389,Spain,10114,Male,2.0,0.0,0.0,0.0,1.0,200.0,150.0,200.0,453.58310,446.82556,457.51586,452.641507,<ISCED level 2>,<ISCED level 2>,<ISCED level 2>
982038,Spain,8511,Male,5.0,2.0,0.0,0.0,3.0,200.0,200.0,150.0,598.38760,531.67132,604.94218,578.333700,<ISCED level 6>,<ISCED level 4>,<ISCED level 4>
1422591,Massachusetts (USA),1238,Female,16.0,2.0,0.0,0.0,0.0,430.0,430.0,430.0,526.10220,553.24094,528.94444,536.095860,<ISCED level 3>,<ISCED level 3>,<ISCED level 3>
108330,Luxembourg,1731,Female,1.0,0.0,0.0,0.0,2.0,135.0,135.0,45.0,435.90124,451.72810,450.80194,446.143760,<ISCED level 3>,Mother - Highest Schooling,<ISCED level 3A>
1716581,Luxembourg,2936,Male,6.0,0.0,0.0,0.0,1.0,200.0,200.0,200.0,510.83502,527.74178,513.46514,517.347313,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
1733669,United Arab Emirates,3169,Male,4.0,1.0,0.0,0.0,1.0,360.0,360.0,360.0,543.78406,543.70052,546.47520,544.653260,<ISCED level 5>,<ISCED level 3>,<ISCED level 3>
157981,United States of America,3265,Male,2.0,2.0,0.0,0.0,1.0,240.0,240.0,240.0,513.56132,529.02490,536.31108,526.299100,<ISCED level 5>,Mother - Highest Schooling,<ISCED level 3A>

In [185]:
mother_edu = mother_edu[(mother_edu['Completed_edu - Mother'] != 'Mother - Highest Schooling')]

In [186]:
mother_edu['Education - Mother'].value_counts()

<ISCED level 3>    159828
<ISCED level 5>    115513
<ISCED level 4>     55348
<ISCED level 2>     28132
<ISCED level 6>     14532
<ISCED level 1>      6189
<ISCED level 0>      2750
Name: Education - Mother, dtype: int64

In [187]:
mother_edu.drop(columns=['Completed_edu - Mother'], axis=1, inplace=True)

In [188]:
mother_edu.sample(10)

,Country,Student ID,Gender,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother
521779,Canada,7271,Female,2.0,0.0,0.0,0.0,0.0,375.0,0.0,375.0,653.30268,707.73424,663.59566,674.877527,<ISCED level 4>,<ISCED level 5>
433266,Australia,7449,Female,10.0,0.0,0.0,0.0,0.0,232.0,232.0,232.0,622.30100,615.59428,626.48264,621.459307,<ISCED level 3>,<ISCED level 5>
1561185,Kazakhstan,5617,Male,12.0,0.0,0.0,0.0,0.0,225.0,90.0,135.0,595.73924,525.09538,589.74266,570.192427,<ISCED level 5>,<ISCED level 3>
816663,Spain,21684,Female,8.0,2.0,4.0,4.0,0.0,165.0,220.0,165.0,542.61566,492.31736,540.22752,525.053513,<ISCED level 2>,<ISCED level 4>
1426950,Slovak Republic,2120,Female,3.0,0.0,0.0,0.0,0.0,225.0,225.0,270.0,631.10298,609.95468,620.70122,620.586293,<ISCED level 3>,<ISCED level 3>
536643,New Zealand,846,Male,5.0,4.0,0.0,0.0,4.0,200.0,200.0,200.0,460.04830,465.67122,442.31630,456.011940,<ISCED level 5>,<ISCED level 5>
445517,Norway,103,Male,4.0,0.0,0.0,0.0,0.0,180.0,225.0,135.0,647.77222,643.38228,709.19432,666.782940,<ISCED level 3>,<ISCED level 5>
1001581,Malaysia,1360,Female,3.0,2.0,1.0,3.0,4.0,320.0,245.0,180.0,378.57142,375.71260,355.40844,369.897487,<ISCED level 2>,<ISCED level 1>
1552936,Russian Federation,1803,Female,4.0,3.0,2.0,0.0,0.0,135.0,180.0,270.0,422.42562,492.07906,487.82172,467.442133,<ISCED level 5>,<ISCED level 3>
895635,Italy,8670,Female,21.0,2.0,2.0,0.0,0.0,300.0,240.0,120.0,562.63438,573.65468,580.04476,572.111273,<ISCED level 3>,<ISCED level 4>

In [189]:
mother_edu['Student ID'].duplicated().sum()

358707

In [190]:
# mother_edu.replace(["NaN"], np.nan, inplace = True)
# mother_edu.dropna(inplace = True)

In [191]:
mother_edu['Education - Mother'] = mother_edu['Education - Mother'].astype('category')

mother_edu['Education - Mother'] = mother_edu['Education - Mother'].cat.set_categories(['<ISCED level 0>', 
                                                                                        '<ISCED level 1>', 
                                                                                        '<ISCED level 2>', 
                                                                                        '<ISCED level 3>',
                                                                                        '<ISCED level 4>', 
                                                                                        '<ISCED level 5>', 
                                                                                        '<ISCED level 6>'], ordered=True)
mother_edu.sort_values(['Education - Mother'], inplace=True)
mother_edu_clean = mother_edu.drop_duplicates(subset='Student ID', keep='last')

In [192]:
mother_edu['Student ID'].duplicated().sum()

358707

In [193]:
mother_edu.shape

(382292, 17)

In [194]:
mother_edu_clean.shape

(23585, 17)

In [195]:
mother_edu_clean.duplicated().sum()

0

In [196]:
mother_edu_clean.sample(10)

,Country,Student ID,Gender,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother
967364,Italy,25736,Male,4.0,4.0,0.0,0.0,0.0,250.0,250.0,200.0,593.94766,594.14284,542.27900,576.789833,<ISCED level 5>,<ISCED level 4>
269995,Brazil,5275,Female,2.0,2.0,2.0,3.0,0.0,200.0,200.0,150.0,454.59574,427.18392,468.98544,450.255033,<ISCED level 3>,<ISCED level 6>
1410099,Italy,23364,Female,12.0,0.0,0.0,0.0,0.0,250.0,200.0,100.0,634.91980,685.97018,593.09960,637.996527,<ISCED level 3>,<ISCED level 3>
905579,Italy,29462,Male,24.0,0.0,0.0,3.0,0.0,300.0,240.0,120.0,638.11344,592.13800,598.04178,609.431073,<ISCED level 4>,<ISCED level 4>
1203354,Italy,24082,Female,5.0,0.0,0.0,0.0,1.0,180.0,360.0,180.0,502.18882,488.42524,486.88924,492.501100,<ISCED level 2>,<ISCED level 2>
1711213,Italy,7704,Male,12.0,4.0,0.0,0.0,6.0,300.0,420.0,360.0,456.54306,467.19494,529.31746,484.351820,<ISCED level 4>,<ISCED level 3>
472545,Canada,20961,Male,3.0,1.0,0.0,0.0,0.0,275.0,275.0,275.0,518.00124,515.07106,544.79674,525.956347,<ISCED level 3>,<ISCED level 5>
673216,Canada,8918,Female,1.0,0.0,0.0,0.0,0.0,225.0,225.0,375.0,579.14784,597.72232,532.58112,569.817093,<ISCED level 3>,<ISCED level 5>
417537,Italy,12040,Male,0.0,0.0,0.0,0.0,0.0,150.0,200.0,100.0,440.96434,476.25692,460.40658,459.209280,<ISCED level 2>,<ISCED level 5>
472842,Canada,20484,Male,2.0,1.0,2.0,1.0,2.0,75.0,75.0,75.0,477.02912,499.51334,497.05332,491.198593,<ISCED level 3>,<ISCED level 5>

In [197]:
pisa_clean = mother_edu_clean.copy()

In [198]:
pisa_clean.shape

(23585, 17)

In [199]:
pisa_clean.duplicated().sum()

0

In [200]:
pisa_clean = mother_edu.copy()

In [201]:
pisa_clean.shape

(382292, 17)

### 4. Missing values in relevant columns 
('Mother Highest Schooling', 'Father Highest Schooling', 'How many books at home', 'Out-of-School Study Time - Homework', 'Out-of-School Study Time - Guided Homework', 'Out-of-School Study Time - Personal Tutor','Out-of-School Study Time - Commercial Company', 'Out-of-School Study Time - With Parent', 'Learning time (minutes per week)- Mathematics', 'Learning time (minutes per week)  - test language', 'Learning time (minutes per week) - Science')

Due to the amount of rows in this dataframe, we can comfortably remove the rows with missing values.

In [202]:

# pisa_clean.replace(["NaN"], np.nan, inplace = True)
# pisa_clean.dropna(inplace = True)

In [203]:
# Check to see if null values correctly dropped
pisa_clean

,Country,Student ID,Gender,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother
1968985,Netherlands,1647,Male,2.0,1.0,0.0,0.0,0.0,150.0,200.0,350.0,449.53266,478.18156,474.20738,467.307200,<ISCED level 6>,<ISCED level 0>
1774983,Macao-China,2513,Female,5.0,1.0,0.0,0.0,2.0,280.0,280.0,0.0,542.61568,527.82302,527.17270,532.537133,<ISCED level 1>,<ISCED level 0>
1774972,Macao-China,2954,Male,10.0,3.0,0.0,0.0,0.0,240.0,240.0,240.0,603.52856,550.83780,568.48190,574.282753,<ISCED level 1>,<ISCED level 0>
1774965,Macao-China,3032,Female,12.0,6.0,0.0,0.0,1.0,270.0,240.0,80.0,612.72004,587.95230,626.01640,608.896247,<ISCED level 1>,<ISCED level 0>
1774961,Macao-China,3094,Male,12.0,2.0,8.0,12.0,2.0,320.0,320.0,320.0,576.03210,497.90946,531.64864,535.196733,<ISCED level 1>,<ISCED level 0>
1774944,Macao-China,2717,Male,1.0,1.0,3.0,0.0,0.0,245.0,210.0,0.0,611.00640,541.85604,559.71654,570.859660,<ISCED level 1>,<ISCED level 0>
1774939,Macao-China,2798,Male,1.0,1.0,0.0,0.0,0.0,280.0,200.0,160.0,500.31938,463.34560,508.80268,490.822553,<ISCED level 1>,<ISCED level 0>
1774932,Malaysia,1261,Male,14.0,7.0,0.0,0.0,0.0,175.0,175.0,175.0,257.44664,271.35994,331.25702,286.687867,<ISCED level 1>,<ISCED level 0>
1774923,Macao-China,5249,Female,12.0,2.0,0.0,0.0,0.0,360.0,280.0,440.0,658.13212,588.50832,653.05858,633.233007,<ISCED level 1>,<ISCED level 0>
1774912,Malaysia,1227,Female,3.0,2.0,3.0,2.0,4.0,175.0,175.0,175.0,359.17586,334.48794,350.00000,347.887933,<ISCED level 1>,<ISCED level 0>
1774910,Malaysia,879,Female,5.0,2.0,0.0,0.0,1.0,360.0,360.0,360.0,484.66274,524.32806,441.10408,483.364960,<ISCED level 1>,<ISCED level 0>
1774905,Macao-China,5314,Female,23.0,7.0,0.0,0.0,5.0,315.0,315.0,0.0,527.50428,565.31444,576.68780,556.502173,<ISCED level 1>,<ISCED level 0>
1774900,Malaysia,126,Male,2.0,1.0,0.0,0.0,1.0,120.0,180.0,120.0,424.45086,455.16576,452.29392,443.970180,<ISCED level 1>,<ISCED level 0>
1774898,Malaysia,383,Female,10.0,10.0,10.0,10.0,10.0,300.0,360.0,240.0,360.81166,396.04698,334.52070,363.793113,<ISCED level 1>,<ISCED level 0>
1774892,Malaysia,807,Female,15.0,1.0,2.0,8.0,12.0,320.0,480.0,320.0,496.26888,589.06432,497.23986,527.524353,<ISCED level 1>,<ISCED level 0>
1774890,Malaysia,2196,Male,2.0,2.0,2.0,0.0,2.0,200.0,240.0,200.0,460.98302,514.91068,480.08208,485.325260,<ISCED level 1>,<ISCED level 0>
1774880,Malaysia,4236,Male,6.0,5.0,2.0,9.0,4.0,180.0,180.0,120.0,394.61754,429.90452,433.83064,419.450900,<ISCED level 1>,<ISCED level 0>
1774879,Malaysia,4250,Female,2.0,1.0,2.0,3.0,1.0,180.0,90.0,120.0,383.40086,376.82466,399.04886,386.424793,<ISCED level 1>,<ISCED level 0>
1774990,Macao-China,2290,Male,4.0,1.0,0.0,22.0,0.0,320.0,240.0,0.0,527.34846,424.29088,492.67062,481.436653,<ISCED level 1>,<ISCED level 0>
1775026,Macao-China,2368,Female,30.0,2.0,0.0,0.0,0.0,240.0,280.0,160.0,456.15362,487.07488,486.42298,476.550493,<ISCED level 1>,<ISCED level 0>
1775031,Macao-China,4049,Female,3.0,0.0,0.0,0.0,0.0,280.0,200.0,80.0,573.69530,543.07376,537.43006,551.399707,<ISCED level 1>,<ISCED level 0>
1775051,Macao-China,3844,Female,14.0,5.0,6.0,0.0,0.0,280.0,240.0,120.0,565.59434,577.07024,557.57180,566.745460,<ISCED level 1>,<ISCED level 0>
1775322,Hong Kong-China,1977,Male,3.0,0.0,0.0,0.0,0.0,240.0,240.0,160.0,578.83626,493.73934,528.85116,533.808920,<ISCED level 1>,<ISCED level 0>
1775321,Hong Kong-China,1994,Male,18.0,0.0,0.0,1.0,0.0,240.0,280.0,240.0,737.89530,603.92658,651.75306,664.524980,<ISCED level 1>,<ISCED level 0>
1775319,Hong Kong-China,2001,Male,4.0,0.0,0.0,0.0,0.0,240.0,240.0,400.0,699.64948,610.90352,638.88472,649.812573,<ISCED level 1>,<ISCED level 0>
1775200,Hong Kong-China,4187,Female,1.0,1.0,1.0,2.0,1.0,240.0,120.0,160.0,329.03102,369.51700,357.83290,352.126973,<ISCED level 1>,<ISCED level 0>
1775185,Hong Kong-China,3842,Female,4.0,0.0,0.0,0.0,0.0,270.0,270.0,225.0,452.18102,480.79986,454.62514,462.535340,<ISCED level 1>,<ISCED level 0>
1775182,Hong Kong-China,3855,Male,21.0,5.0,0.0,0.0,0.0,220.0,275.0,220.0,542.45988,525.49638,512.62588,526.860713,<ISCED level 1>,<ISCED level 0>
1775166,Hong Kong-China,4633,Male,1.0,0.0,0.0,0.0,0.0,220.0,220.0,165.0,567.07432,575.37734,586.94516,576.465607,<ISCED level 1>,<ISCED level 0>
1775147,Hungary,1200,Female,2.0,1.0,1.0,2.0,2.0,120.0,90.0,168.0,318.28166,322.41442,335.63968,325.445253,<ISCED level 1>,<ISCED level 0>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329541,United Arab Emirates,6439,Male,10.0,9.0,8.0,4.0,6.0,100.0,100.0,100.0,390.33340,345.45966,374.89744,370.230167,<ISCED level 4>,<ISCED level 6>
329542,United Arab Emirates,6450,Male,16.0,2.0,6.0,0.0,4.0,400.0,400.0,900.0,522.75278,499.03216,529.87692,517.220620,<ISCED level 4>,<ISCED level 6>
329544,United Arab Emirates,6835,Male,2.0,0.0,0.0,0.0,1.0,630.0,90.0,270.0,429.20236,395.82180,435.97536,420.333173,<ISCED level 4>,<ISCED level 6>
329549,United Arab Emirates,7218,Female,14.0,0.0,0.0,0.0,0.0,255.0,255.0,510.0,541.83672,522.97772,583.68146,549.498633,<ISCED level 4>,<ISCED level 6>
329407,United Arab Emirates,7592,Male,1.0,1.0,1.0,1.0,1.0,90.0,90.0,45.0,435.04438,404.80362,417.13914,418.995713,<ISCED level 4>,<ISCED level 6>
329400,United Arab Emirates,7793,Male,7.0,3.0,0.0,0.0,10.0,270.0,270.0,270.0,435.43388,414.26658,434.11040,427.936953,<ISCED level 4>,<ISCED level 6>
329387,United Arab Emirates,8054,Male,10.0,6.0,2.0,0.0,2.0,160.0,160.0,480.0,492.60790,558.45630,565.59120,538.885133,<ISCED level 4>,<ISCED level 6>
329377,United Arab Emirates,7895,Male,1.0,1.0,1.0,2.0,2.0,200.0,200.0,120.0,458.80198,445.38204,482.78626,462.323427,<ISCED level 4>,<ISCED level 6>
329201,United Arab Emirates,5712,Male,4.0,2.0,0.0,0.0,1.0,400.0,160.0,280.0,374.75464,370.48036,377.97462,374.403207,<ISCED level 4>,<ISCED level 6>
329231,United Arab Emirates,5281,Male,1.0,1.0,1.0,1.0,1.0,315.0,315.0,315.0,336.04142,283.38912,310.83550,310.088680,<ISCED level 4>,<ISCED level 6>
329232,United Arab Emirates,5283,Male,3.0,2.0,2.0,0.0,0.0,360.0,280.0,400.0,400.22590,392.13288,420.02984,404.129540,<ISCED level 4>,<ISCED level 6>
329237,United Arab Emirates,5366,Male,2.0,2.0,2.0,2.0,2.0,270.0,315.0,315.0,320.93006,318.19354,367.34428,335.489293,<ISCED level 4>,<ISCED level 6>
329241,United Arab Emirates,5498,Male,1.0,1.0,1.0,1.0,1.0,400.0,400.0,150.0,348.50444,331.34546,341.23462,340.361507,<ISCED level 4>,<ISCED level 6>
329253,United Arab Emirates,4356,Male,3.0,2.0,0.0,0.0,2.0,220.0,220.0,550.0,498.44994,520.84506,511.13392,510.142973,<ISCED level 4>,<ISCED level 6>
329263,United Arab Emirates,3277,Male,2.0,2.0,3.0,5.0,4.0,150.0,100.0,200.0,262.82132,261.57620,292.74526,272.380927,<ISCED level 4>,<ISCED level 6>
329276,United Arab Emirates,3424,Female,14.0,13.0,0.0,0.0,7.0,240.0,240.0,300.0,446.88426,531.00026,522.13728,500.007267,<ISCED level 4>,<ISCED level 6>
329278,United Arab Emirates,3435,Female,8.0,3.0,2.0,6.0,1.0,240.0,240.0,300.0,527.97164,529.33220,525.68072,527.661520,<ISCED level 4>,<ISCED level 6>
338206,Luxembourg,3269,Female,4.0,0.0,2.0,0.0,1.0,200.0,250.0,200.0,567.54166,604.39452,593.09958,588.345253,<ISCED level 5>,<ISCED level 6>
329282,United Arab Emirates,3167,Male,12.0,12.0,15.0,16.0,17.0,160.0,120.0,200.0,376.31250,313.30170,347.20254,345.605580,<ISCED level 4>,<ISCED level 6>
329302,United Arab Emirates,3062,Female,6.0,0.0,0.0,0.0,0.0,450.0,400.0,400.0,513.79496,513.92260,543.95750,523.891687,<ISCED level 4>,<ISCED level 6>
329304,United Arab Emirates,3109,Male,1.0,1.0,2.0,1.0,2.0,360.0,360.0,315.0,445.71584,460.77940,447.35174,451.282327,<ISCED level 4>,<ISCED level 6>
329314,United Arab Emirates,4012,Male,1.0,1.0,2.0,1.0,1.0,105.0,280.0,70.0,391.19020,434.15480,398.11638,407.820460,<ISCED level 4>,<ISCED level 6>
329322,United Arab Emirates,4112,Female,4.0,3.0,5.0,4.0,5.0,200.0,200.0,200.0,388.38604,398.90650,408.37374,398.555427,<ISCED level 4>,<ISCED level 6>
329340,United Arab Emirates,3984,Male,14.0,4.0,5.0,18.0,18.0,384.0,270.0,360.0,372.57360,335.59574,336.94518,348.371507,<ISCED level 4>,<ISCED level 6>
329343,United Arab Emirates,3483,Female,1.0,1.0,2.0,3.0,1.0,270.0,315.0,225.0,395.39650,331.86672,358.76538,362.009533,<ISCED level 4>,<ISCED level 6>
329353,United Arab Emirates,3655,Male,1.0,1.0,0.0,0.0,0.0,360.0,240.0,385.0,378.02616,355.80476,375.73666,369.855860,<ISCED level 4>,<ISCED level 6>
329364,United Arab Emirates,3789,Female,10.0,2.0,0.0,0.0,0.0,200.0,160.0,480.0,479.59962,520.11822,511.22714,503.648327,<ISCED level 4>,<ISCED level 6>
329374,United Arab Emirates,7835,Female,7.0,1.0,0.0,0.0,2.0,280.0,240.0,240.0,432.16234,525.83724,477.75084,478.583473,<ISCED level 4>,<ISCED level 6>
329289,United Arab Emirates,2893,Female,6.0,2.0,2.0,0.0,1.0,225.0,315.0,360.0,460.59354,566.18820,496.12084,507.634193,<ISCED level 4>,<ISCED level 6>
196993,Denmark,134,Male,4.0,1.0,0.0,0.0,0.0,540.0,720.0,540.0,458.49040,483.23384,390.46996,444.064733,<ISCED level 0>,<ISCED level 6>

In [204]:
# Confirm with smaller shape of dataframe
pisa_clean.shape

(382292, 17)

### 5. Create a total for Out-of-School Study Time and Learning time (minutes per week)

In [205]:
# Create total of Out-of-School Study Time
pisa_clean['Out-of-School Study Time - Total'] = pisa_clean['Out-of-School Study Time - Homework'] + pisa_clean['Out-of-School Study Time - Guided Homework'] + pisa_clean['Out-of-School Study Time - Personal Tutor'] + pisa_clean['Out-of-School Study Time - Commercial Company'] + pisa_clean['Out-of-School Study Time - With Parent']

# Create total of Learning time (minutes per week)
pisa_clean['Learning Time - Total'] = pisa_clean['Learning Time - Mathematics'] + pisa_clean['Learning Time - Test Language'] + pisa_clean['Learning Time - Science']

In [206]:
list(pisa_clean)

['Country',
 'Student ID',
 'Gender',
 'Out-of-School Study Time - Homework',
 'Out-of-School Study Time - Guided Homework',
 'Out-of-School Study Time - Personal Tutor',
 'Out-of-School Study Time - Commercial Company',
 'Out-of-School Study Time - With Parent',
 'Learning Time - Mathematics',
 'Learning Time - Test Language',
 'Learning Time - Science',
 'Average Math Score',
 'Average Reading Score',
 'Average Science Score',
 'Average Total Score',
 'Education - Father',
 'Education - Mother',
 'Out-of-School Study Time - Total',
 'Learning Time - Total']

<a id='assessing2'></a>
### Final Assessment

In this section, we will do the preliminary visual and programmatic assessment of the pisa datasets to determine whether or not it holds any major quality or tidiness issues.

In [207]:
pisa_clean

,Country,Student ID,Gender,Out-of-School Study Time - Homework,Out-of-School Study Time - Guided Homework,Out-of-School Study Time - Personal Tutor,Out-of-School Study Time - Commercial Company,Out-of-School Study Time - With Parent,Learning Time - Mathematics,Learning Time - Test Language,Learning Time - Science,Average Math Score,Average Reading Score,Average Science Score,Average Total Score,Education - Father,Education - Mother,Out-of-School Study Time - Total,Learning Time - Total
1968985,Netherlands,1647,Male,2.0,1.0,0.0,0.0,0.0,150.0,200.0,350.0,449.53266,478.18156,474.20738,467.307200,<ISCED level 6>,<ISCED level 0>,3.0,700.0
1774983,Macao-China,2513,Female,5.0,1.0,0.0,0.0,2.0,280.0,280.0,0.0,542.61568,527.82302,527.17270,532.537133,<ISCED level 1>,<ISCED level 0>,8.0,560.0
1774972,Macao-China,2954,Male,10.0,3.0,0.0,0.0,0.0,240.0,240.0,240.0,603.52856,550.83780,568.48190,574.282753,<ISCED level 1>,<ISCED level 0>,13.0,720.0
1774965,Macao-China,3032,Female,12.0,6.0,0.0,0.0,1.0,270.0,240.0,80.0,612.72004,587.95230,626.01640,608.896247,<ISCED level 1>,<ISCED level 0>,19.0,590.0
1774961,Macao-China,3094,Male,12.0,2.0,8.0,12.0,2.0,320.0,320.0,320.0,576.03210,497.90946,531.64864,535.196733,<ISCED level 1>,<ISCED level 0>,36.0,960.0
1774944,Macao-China,2717,Male,1.0,1.0,3.0,0.0,0.0,245.0,210.0,0.0,611.00640,541.85604,559.71654,570.859660,<ISCED level 1>,<ISCED level 0>,5.0,455.0
1774939,Macao-China,2798,Male,1.0,1.0,0.0,0.0,0.0,280.0,200.0,160.0,500.31938,463.34560,508.80268,490.822553,<ISCED level 1>,<ISCED level 0>,2.0,640.0
1774932,Malaysia,1261,Male,14.0,7.0,0.0,0.0,0.0,175.0,175.0,175.0,257.44664,271.35994,331.25702,286.687867,<ISCED level 1>,<ISCED level 0>,21.0,525.0
1774923,Macao-China,5249,Female,12.0,2.0,0.0,0.0,0.0,360.0,280.0,440.0,658.13212,588.50832,653.05858,633.233007,<ISCED level 1>,<ISCED level 0>,14.0,1080.0
1774912,Malaysia,1227,Female,3.0,2.0,3.0,2.0,4.0,175.0,175.0,175.0,359.17586,334.48794,350.00000,347.887933,<ISCED level 1>,<ISCED level 0>,14.0,525.0
1774910,Malaysia,879,Female,5.0,2.0,0.0,0.0,1.0,360.0,360.0,360.0,484.66274,524.32806,441.10408,483.364960,<ISCED level 1>,<ISCED level 0>,8.0,1080.0
1774905,Macao-China,5314,Female,23.0,7.0,0.0,0.0,5.0,315.0,315.0,0.0,527.50428,565.31444,576.68780,556.502173,<ISCED level 1>,<ISCED level 0>,35.0,630.0
1774900,Malaysia,126,Male,2.0,1.0,0.0,0.0,1.0,120.0,180.0,120.0,424.45086,455.16576,452.29392,443.970180,<ISCED level 1>,<ISCED level 0>,4.0,420.0
1774898,Malaysia,383,Female,10.0,10.0,10.0,10.0,10.0,300.0,360.0,240.0,360.81166,396.04698,334.52070,363.793113,<ISCED level 1>,<ISCED level 0>,50.0,900.0
1774892,Malaysia,807,Female,15.0,1.0,2.0,8.0,12.0,320.0,480.0,320.0,496.26888,589.06432,497.23986,527.524353,<ISCED level 1>,<ISCED level 0>,38.0,1120.0
1774890,Malaysia,2196,Male,2.0,2.0,2.0,0.0,2.0,200.0,240.0,200.0,460.98302,514.91068,480.08208,485.325260,<ISCED level 1>,<ISCED level 0>,8.0,640.0
1774880,Malaysia,4236,Male,6.0,5.0,2.0,9.0,4.0,180.0,180.0,120.0,394.61754,429.90452,433.83064,419.450900,<ISCED level 1>,<ISCED level 0>,26.0,480.0
1774879,Malaysia,4250,Female,2.0,1.0,2.0,3.0,1.0,180.0,90.0,120.0,383.40086,376.82466,399.04886,386.424793,<ISCED level 1>,<ISCED level 0>,9.0,390.0
1774990,Macao-China,2290,Male,4.0,1.0,0.0,22.0,0.0,320.0,240.0,0.0,527.34846,424.29088,492.67062,481.436653,<ISCED level 1>,<ISCED level 0>,27.0,560.0
1775026,Macao-China,2368,Female,30.0,2.0,0.0,0.0,0.0,240.0,280.0,160.0,456.15362,487.07488,486.42298,476.550493,<ISCED level 1>,<ISCED level 0>,32.0,680.0
1775031,Macao-China,4049,Female,3.0,0.0,0.0,0.0,0.0,280.0,200.0,80.0,573.69530,543.07376,537.43006,551.399707,<ISCED level 1>,<ISCED level 0>,3.0,560.0
1775051,Macao-China,3844,Female,14.0,5.0,6.0,0.0,0.0,280.0,240.0,120.0,565.59434,577.07024,557.57180,566.745460,<ISCED level 1>,<ISCED level 0>,25.0,640.0
1775322,Hong Kong-China,1977,Male,3.0,0.0,0.0,0.0,0.0,240.0,240.0,160.0,578.83626,493.73934,528.85116,533.808920,<ISCED level 1>,<ISCED level 0>,3.0,640.0
1775321,Hong Kong-China,1994,Male,18.0,0.0,0.0,1.0,0.0,240.0,280.0,240.0,737.89530,603.92658,651.75306,664.524980,<ISCED level 1>,<ISCED level 0>,19.0,760.0
1775319,Hong Kong-China,2001,Male,4.0,0.0,0.0,0.0,0.0,240.0,240.0,400.0,699.64948,610.90352,638.88472,649.812573,<ISCED level 1>,<ISCED level 0>,4.0,880.0
1775200,Hong Kong-China,4187,Female,1.0,1.0,1.0,2.0,1.0,240.0,120.0,160.0,329.03102,369.51700,357.83290,352.126973,<ISCED level 1>,<ISCED level 0>,6.0,520.0
1775185,Hong Kong-China,3842,Female,4.0,0.0,0.0,0.0,0.0,270.0,270.0,225.0,452.18102,480.79986,454.62514,462.535340,<ISCED level 1>,<ISCED level 0>,4.0,765.0
1775182,Hong Kong-China,3855,Male,21.0,5.0,0.0,0.0,0.0,220.0,275.0,220.0,542.45988,525.49638,512.62588,526.860713,<ISCED level 1>,<ISCED level 0>,26.0,715.0
1775166,Hong Kong-China,4633,Male,1.0,0.0,0.0,0.0,0.0,220.0,220.0,165.0,567.07432,575.37734,586.94516,576.465607,<ISCED level 1>,<ISCED level 0>,1.0,605.0
1775147,Hungary,1200,Female,2.0,1.0,1.0,2.0,2.0,120.0,90.0,168.0,318.28166,322.41442,335.63968,325.445253,<ISCED level 1>,<ISCED level 0>,8.0,378.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
329541,United Arab Emirates,6439,Male,10.0,9.0,8.0,4.0,6.0,100.0,100.0,100.0,390.33340,345.45966,374.89744,370.230167,<ISCED level 4>,<ISCED level 6>,37.0,300.0
329542,United Arab Emirates,6450,Male,16.0,2.0,6.0,0.0,4.0,400.0,400.0,900.0,522.75278,499.03216,529.87692,517.220620,<ISCED level 4>,<ISCED level 6>,28.0,1700.0
329544,United Arab Emirates,6835,Male,2.0,0.0,0.0,0.0,1.0,630.0,90.0,270.0,429.20236,395.82180,435.97536,420.333173,<ISCED level 4>,<ISCED level 6>,3.0,990.0
329549,United Arab Emirates,7218,Female,14.0,0.0,0.0,0.0,0.0,255.0,255.0,510.0,541.83672,522.97772,583.68146,549.498633,<ISCED level 4>,<ISCED level 6>,14.0,1020.0
329407,United Arab Emirates,7592,Male,1.0,1.0,1.0,1.0,1.0,90.0,90.0,45.0,435.04438,404.80362,417.13914,418.995713,<ISCED level 4>,<ISCED level 6>,5.0,225.0
329400,United Arab Emirates,7793,Male,7.0,3.0,0.0,0.0,10.0,270.0,270.0,270.0,435.43388,414.26658,434.11040,427.936953,<ISCED level 4>,<ISCED level 6>,20.0,810.0
329387,United Arab Emirates,8054,Male,10.0,6.0,2.0,0.0,2.0,160.0,160.0,480.0,492.60790,558.45630,565.59120,538.885133,<ISCED level 4>,<ISCED level 6>,20.0,800.0
329377,United Arab Emirates,7895,Male,1.0,1.0,1.0,2.0,2.0,200.0,200.0,120.0,458.80198,445.38204,482.78626,462.323427,<ISCED level 4>,<ISCED level 6>,7.0,520.0
329201,United Arab Emirates,5712,Male,4.0,2.0,0.0,0.0,1.0,400.0,160.0,280.0,374.75464,370.48036,377.97462,374.403207,<ISCED level 4>,<ISCED level 6>,7.0,840.0
329231,United Arab Emirates,5281,Male,1.0,1.0,1.0,1.0,1.0,315.0,315.0,315.0,336.04142,283.38912,310.83550,310.088680,<ISCED level 4>,<ISCED level 6>,5.0,945.0
329232,United Arab Emirates,5283,Male,3.0,2.0,2.0,0.0,0.0,360.0,280.0,400.0,400.22590,392.13288,420.02984,404.129540,<ISCED level 4>,<ISCED level 6>,7.0,1040.0
329237,United Arab Emirates,5366,Male,2.0,2.0,2.0,2.0,2.0,270.0,315.0,315.0,320.93006,318.19354,367.34428,335.489293,<ISCED level 4>,<ISCED level 6>,10.0,900.0
329241,United Arab Emirates,5498,Male,1.0,1.0,1.0,1.0,1.0,400.0,400.0,150.0,348.50444,331.34546,341.23462,340.361507,<ISCED level 4>,<ISCED level 6>,5.0,950.0
329253,United Arab Emirates,4356,Male,3.0,2.0,0.0,0.0,2.0,220.0,220.0,550.0,498.44994,520.84506,511.13392,510.142973,<ISCED level 4>,<ISCED level 6>,7.0,990.0
329263,United Arab Emirates,3277,Male,2.0,2.0,3.0,5.0,4.0,150.0,100.0,200.0,262.82132,261.57620,292.74526,272.380927,<ISCED level 4>,<ISCED level 6>,16.0,450.0
329276,United Arab Emirates,3424,Female,14.0,13.0,0.0,0.0,7.0,240.0,240.0,300.0,446.88426,531.00026,522.13728,500.007267,<ISCED level 4>,<ISCED level 6>,34.0,780.0
329278,United Arab Emirates,3435,Female,8.0,3.0,2.0,6.0,1.0,240.0,240.0,300.0,527.97164,529.33220,525.68072,527.661520,<ISCED level 4>,<ISCED level 6>,20.0,780.0
338206,Luxembourg,3269,Female,4.0,0.0,2.0,0.0,1.0,200.0,250.0,200.0,567.54166,604.39452,593.09958,588.345253,<ISCED level 5>,<ISCED level 6>,7.0,650.0
329282,United Arab Emirates,3167,Male,12.0,12.0,15.0,16.0,17.0,160.0,120.0,200.0,376.31250,313.30170,347.20254,345.605580,<ISCED level 4>,<ISCED level 6>,72.0,480.0
329302,United Arab Emirates,3062,Female,6.0,0.0,0.0,0.0,0.0,450.0,400.0,400.0,513.79496,513.92260,543.95750,523.891687,<ISCED level 4>,<ISCED level 6>,6.0,1250.0
329304,United Arab Emirates,3109,Male,1.0,1.0,2.0,1.0,2.0,360.0,360.0,315.0,445.71584,460.77940,447.35174,451.282327,<ISCED level 4>,<ISCED level 6>,7.0,1035.0
329314,United Arab Emirates,4012,Male,1.0,1.0,2.0,1.0,1.0,105.0,280.0,70.0,391.19020,434.15480,398.11638,407.820460,<ISCED level 4>,<ISCED level 6>,6.0,455.0
329322,United Arab Emirates,4112,Female,4.0,3.0,5.0,4.0,5.0,200.0,200.0,200.0,388.38604,398.90650,408.37374,398.555427,<ISCED level 4>,<ISCED level 6>,21.0,600.0
329340,United Arab Emirates,3984,Male,14.0,4.0,5.0,18.0,18.0,384.0,270.0,360.0,372.57360,335.59574,336.94518,348.371507,<ISCED level 4>,<ISCED level 6>,59.0,1014.0
329343,United Arab Emirates,3483,Female,1.0,1.0,2.0,3.0,1.0,270.0,315.0,225.0,395.39650,331.86672,358.76538,362.009533,<ISCED level 4>,<ISCED level 6>,8.0,810.0
329353,United Arab Emirates,3655,Male,1.0,1.0,0.0,0.0,0.0,360.0,240.0,385.0,378.02616,355.80476,375.73666,369.855860,<ISCED level 4>,<ISCED level 6>,2.0,985.0
329364,United Arab Emirates,3789,Female,10.0,2.0,0.0,0.0,0.0,200.0,160.0,480.0,479.59962,520.11822,511.22714,503.648327,<ISCED level 4>,<ISCED level 6>,12.0,840.0
329374,United Arab Emirates,7835,Female,7.0,1.0,0.0,0.0,2.0,280.0,240.0,240.0,432.16234,525.83724,477.75084,478.583473,<ISCED level 4>,<ISCED level 6>,10.0,760.0
329289,United Arab Emirates,2893,Female,6.0,2.0,2.0,0.0,1.0,225.0,315.0,360.0,460.59354,566.18820,496.12084,507.634193,<ISCED level 4>,<ISCED level 6>,11.0,900.0
196993,Denmark,134,Male,4.0,1.0,0.0,0.0,0.0,540.0,720.0,540.0,458.49040,483.23384,390.46996,444.064733,<ISCED level 0>,<ISCED level 6>,5.0,1800.0

In [208]:
pisa_clean.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 382292 entries, 1968985 to 196993
Data columns (total 19 columns):
Country                                          382292 non-null object
Student ID                                       382292 non-null int64
Gender                                           382292 non-null object
Out-of-School Study Time - Homework              382292 non-null float64
Out-of-School Study Time - Guided Homework       382292 non-null float64
Out-of-School Study Time - Personal Tutor        382292 non-null float64
Out-of-School Study Time - Commercial Company    382292 non-null float64
Out-of-School Study Time - With Parent           382292 non-null float64
Learning Time - Mathematics                      382292 non-null float64
Learning Time - Test Language                    382292 non-null float64
Learning Time - Science                          382292 non-null float64
Average Math Score                               382292 non-null float64
Average Reading Score                            382292 non-null float64
Average Science Score                            382292 non-null float64
Average Total Score                              382292 non-null float64
Education - Father                               382292 non-null category
Education - Mother                               382292 non-null category
Out-of-School Study Time - Total                 382292 non-null float64
Learning Time - Total                            382292 non-null float64
dtypes: category(2), float64(14), int64(1), object(2)
memory usage: 53.2+ MB

In [209]:
pisa_clean.shape

(382292, 19)

In [210]:
pisa_clean.drop_duplicates(keep='last', inplace=True)

In [211]:
pisa_clean.duplicated().sum()

0

In [212]:
pisa_clean['Student ID'].drop_duplicates(keep='last', inplace=True)

In [213]:
pisa_clean['Student ID'].duplicated().sum()

0

In [214]:
pisa_clean.shape

(346570, 19)

<a id='sav'></a>
## Store

In [215]:
# Store the clean DataFrame in a CSV file
pisa_clean.to_csv("pisa_df.csv", index=False, encoding='utf8')

<a id='conclusion'></a>
## Conclusion

<a id='references'></a>
## References